#!/bin/bash

#############################################################
# Script for testing of DGAS services                       # 
# Basic tests: ping to host, ping to services               #  
#############################################################
#                                                           #
# Returned values:                                          #
#                                                           #
#                 SAME_OK:     Test Passed                  #
#                 SAME_ERROR:  Test Failed                  #
#                 2:           Wrong Input                  #
#                                                           #
#############################################################

# Sourcing basic functions
. $SAME_SENSOR_HOME/../functions.sh

if [ $? -gt 0 ]; then
  exit 2
fi

# Sourcing the configuration and the utilities

. $SAME_SENSOR_HOME/config.sh
. $SAME_SENSOR_HOME/utilities.sh

function test_ping
{
  samPrintINFO ; echo " Testing ping to $HLR host..." ; samNewLine
  
  ping -c 5 $HLR &> /dev/null

  result=$?

  if [ $result -gt 0 ] ; then
    samPrintFAILED ; echo " >>> The ping command returns error number $result <<<" ; samNewLine
    exit $SAME_ERROR
  else
    samPrintOK ; echo " The HLR machine is up!" ; samNewLine
  fi
}


function test_hlrping
{
  samPrintINFO ; echo " Testing ping to $HLR services..." ; samNewLine

  $GLITE_LOCATION/bin/glite-dgas-ping -s $HLR:$HLR_PORT: --debug -t 0 &> /dev/null
  result=$?

  if [ $result -gt 0 ]; then
    samPrintFAILED ; echo " >>> Returned error is: $result <<<"; samNewLine
    exit $SAME_ERROR
  else
    samPrintOK ; echo " The HLR services are running!" ; samNewLine
  fi
}


#################
# Start testing #
#################

check_env "GLITE_LOCATION HLR_HOSTNAME HLR_PORT"
check_command "$GLITE_LOCATION/bin/glite-dgas-ping"

HLR=$HLR_HOSTNAME

samPrintINFO ; echo " Start testing with settings: HLR_HOST = $HLR " ; samNewLine

test_ping
test_hlrping 

samPrintPASSED ; echo " DGAS Basic Test completed." ; samNewLine

exit $SAME_OK
