#!/bin/bash
SENSOR=VOMS

export vo_name=test
export SAME_ERROR=1
export SAME_OK=0
export SAME_SENSOR_HOME=$HOME/same/client-ctb/sensors/$SENSOR
export SAME_SENSOR_WORK=$HOME/same/client-ctb/sensors/$SENSOR/work
export nodeName="lxb2026.cern.ch"

mkdir -p $SAME_SENSOR_WORK/nodes/$nodeName

#source tests/maarten
#export nodeName="lxb2026.cern.ch"