#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove one user using its user certificate                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - file config_file  (User certificate file path)                                    #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#                                                                                           #
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "VOMS-delUser - started, VO=$vo_name, User=$USER"

echo "-------- Extract by openssl from usercert.pem ------"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`

echo "DN=$user_subject"

echo "SCENARIO 1: User doesn't exist"

echo "Remove  not existing user"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER 2> $voms_stderr
#cat $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr # > /dev/null

if [ $? == 1 ]; then
    echo "Noncorrect diagnose: <<"    
    cat $voms_stderr
    echo ">> Test has failed"
   exit $SAME_ERROR
fi

echo "SCENARIO 2, Create and then remove user"
voms-admin --vo=$vo_name -h $voms_host create-user $USER

echo "Remove created user"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER


echo "Check list users after user deletion"
voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp


grep "$user_subject" $voms_tmp # > /dev/null


if [ $? == 0 ]; then
   echo "User not deleted: <<"
    cat $voms_tmp
    echo ">>,    Test has failed"
   exit $SAME_ERROR
fi
   rm -rf $voms_tmp
   rm -rf $voms_stderr
 
   echo "Test is OK"
   exit $SAME_OK

