#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove user's Role                                               #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - User certificate file path                                                        #
#       - VO host name                                                                      #
#       - Role                                                                              #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
###########################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "test VOMS-dismissRole - started, VO=$vo_name, Role=$ROLE, Group=$GROUP User=$USER"

echo "SCENARIO: VO - empty"

echo "Remove nonexisting Role of nonexisting user in nonexisting group"

voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr

grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr

if [ $? == 1 ]; then
    echo "Noncorrect diagnose: <<"
    cat $voms_stderr
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "OK, Create new Role"
voms-admin --vo=$vo_name -h $voms_host create-role $ROLE

echo "OK, Again dismiss Role"
voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr

grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
if [ $? == 1 ]; then
    echo "Noncorrect diagnose: <<"
    cat $voms_stderr
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "OK, Create new group"
voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP

echo "Again dismiss Role"
voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr

if [ $? == 1 ]; then
    echo "Noncorrect diagnose: <<"
    cat $voms_stderr
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "OK, Create user"
voms-admin --vo=$vo_name -h $voms_host create-user $USER

echo "Again dismiss Role"
voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER 2> $voms_stderr
grep "does not have role" $voms_stderr

if [ $? == 1 ]; then
    echo "Noncorrect diagnose: <<"
    cat $voms_stderr
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "Assign Role"
voms-admin --vo=$vo_name -h $voms_host  assign-role "/"$vo_name"/"$GROUP $ROLE $USER

echo "List user roles:"
voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER > $voms_tmp
#cat $voms_tmp 

echo "Check assign result:"
 
grep "$ROLE" $voms_tmp
if [ $? == 1 ]; then
    echo "Nonexpected result: <<"
    cat $voms_tmp
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "Again dismiss Role"
voms-admin --vo=$vo_name -h $voms_host  dismiss-role "/"$vo_name"/"$GROUP $ROLE $USER

echo "User Role has removed, check it"
voms-admin --vo=$vo_name -h $voms_host  list-user-roles $USER > $voms_tmp
#cat $voms_tmp 

grep "$ROLE" $voms_tmp
if [ $? == 0 ]; then
    echo "Nonexpected result: <<"
    cat $voms_tmp
    echo ">>,  Test has failed"
   exit $SAME_ERROR
fi

echo "Test - ok, leave empty VO"
echo "Delete user"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER

echo "Delete group"
voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP

echo "Delete Role"
voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test is OK"
exit $SAME_OK

