#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete group for VO                                              #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                       #
#       - VO host name                                                                      #
#       - Group name                                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
###########################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################

source $SAME_SENSOR_HOME/tests/config_file

voms_host=$1

voms_tmp=/tmp/$voms_host"_tmp"
voms_stderr=/tmp/$voms_host"_stderr"
tempo=/tmp/$voms_host"_string"


rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo ""
date
echo "test VOMS-delGroup - started, VO=$vo_name, Group=$GROUP" 


echo "            SCENARIO 1: group - not exist             "


echo "Delete group"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP" 2> $voms_stderr

#echo "check error message:<<"
#cat $voms_stderr
#echo ">>"

grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr  # > /dev/null

if [ $? == 1 ]; then
    echo "Not defined ERROR<"
    cat $voms_stderr
    echo ">, Test has failed"
    exit $SAME_ERROR
fi

echo "           SCENARIO 2: Group exists              "

echo "Create new group"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name" "/$GROUP"

echo "Delete this group"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"


echo "Check if this group exists already"
voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp

grep "$GROUP" $voms_tmp > /dev/null

if [ $? == 0 ]; then 
    echo "Group not removed! Test has failed"
    exit $SAME_ERROR
fi

echo "    Test is OK"
exit $SAME_OK