#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove  one user as member from group                            #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - User certificate file path                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#       - user certificate                                                                  #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "VOMS-removeMember - started, VO=$vo_name, User=$USER, Group=$GROUP"

echo "-------- Extract by openssl from usercert.pem ------"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`

echo "DN=$user_subject"
echo "SCENARIO 1: VO - empty"

voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr

grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr

if [ $? == 1 ]; then
   echo "Noncorrect diagnose <<"
   cat $voms_stderr
   echo ">>"
   echo "Test has failed"
   exit $SAME_ERROR
else
   echo "Diag  - correct"
fi

echo "Create group $GROUP"

voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name "/"$GROUP

echo "Group has created, again remove member"
voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr


grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr

if [ $? == 1 ]; then
   echo "Noncorrect diagnose <"
   cat $voms_stderr
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
else
   echo "Diag  - correct"
fi

echo "Create user"

voms-admin --vo=$vo_name -h $voms_host create-user $USER

echo "User has created, add member to group"

voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER

echo "Check members list"
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp
#echo "Members list:"
#cat $voms_tmp
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
   echo "Member  not created, LIST:<<"
   cat $voms_tmp
   echo ">>, DN=$user_subject"
   echo "Test has failed"
   exit $SAME_ERROR
fi

echo "Last remove member"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER

echo "Check members list"
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
#echo "Members list:"
#cat $voms_tmp

grep "No users are returned" $voms_stderr

if [ $? == 1 ]; then
   echo "Member  not removed, LIST:<<"
   cat $voms_tmp
   echo ">>, Test has failed"
   exit $SAME_ERROR
fi


echo "Test - Ok, leave empty VO"

echo "Delete group"
voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
echo "Delete user"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test - OK"
exit $SAME_OK
