#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: List members of group                                            #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - User certificate file path                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#       - user certificate                                                                  #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "VOMS-listMembers - started, VO=$vo_name, Group=$GROUP"

echo "SCENARIO 1: VO - empty"
echo "Try list command for nonexisting group" 
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr

grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr

if [ $? == 1 ]; then
   echo "Noncorrect diagnose <<"
   cat $voms_stderr
   echo ">>"
   echo "Test has failed"
   exit $SAME_ERROR
else
    echo "Diag - correct"
fi

echo "Create group $GROUP"
voms-admin --vo=$vo_name  -h $voms_host  create-group "/"$vo_name "/"$GROUP

echo "List members again"
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr

grep "No users are returned" $voms_stderr

if [ $? == 1 ]; then
   echo "Noncorrect diagnose <"
   cat $voms_stderr
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
else
   echo "Diag  - correct"
fi
echo "Create new users and add members to this group"
user1="DN_USER1"
user2="DN_USER2"
user3="DN_USER3"
user4="DN_USER4"

echo "Step 1: Create 4 nocert users: $user1, $user2, $user3, $user4"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user2" "$CA" "CN-User2" "user2@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user3" "$CA" "CN-User3" "user3@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user4" "$CA" "CN-User4" "user4@cern.ch"
echo "OK"

echo "add this users as members to group"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"

echo "List new 4 members this group"
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp

echo "check this members list"

grep "$user1" $voms_tmp
if [ $? == 1 ]; then
   echo "Member  $user2 not exist LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user2" $voms_tmp
if [ $? == 1 ]; then
   echo "Member  $user2 not exist LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user3" $voms_tmp
if [ $? == 1 ]; then
   echo "Member $user3  not exist LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user4" $voms_tmp
if [ $? == 1 ]; then
   echo "Member $user4  not exist LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi


echo "Test - Ok, leave empty VO"

echo "Remove group members"

voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"

echo "Delete group"
voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP

echo "Delete users"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user1 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user2 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user3 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user4 "$CA"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test - OK"
exit $SAME_OK