#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test group list command                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "VOMS-listGroups - started, VO=$vo_name"


group1="GROUP1"
group2="GROUP2"
group3="GROUP3"
group4="GROUP4"

echo "Step 1: Create 4 groups: $group1, $group2, $group3, $group4"

voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name" "/$group1"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name" "/$group2"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name" "/$group3"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name" "/$group4"

echo "OK"

echo "Step 2: Check group list"

voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp

#cat $voms_tmp

echo "Check 4 groups, "

grep "$group1" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $group1 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$group2" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $group2 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$group3" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $group3 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$group4" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $group4 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi
echo "OK"

echo "Clear Created groups"
voms-admin --vo=$vo_name delete-group $vo_name/$group1
voms-admin --vo=$vo_name delete-group $vo_name/$group2
voms-admin --vo=$vo_name delete-group $vo_name/$group3
voms-admin --vo=$vo_name delete-group $vo_name/$group4

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test is OK"
exit $SAME_OK
