#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test roles list command                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################

source $SAME_SENSOR_HOME/tests/config_file

voms_host=$1

voms_tmp=/tmp/$voms_host"_tmp"
voms_stderr=/tmp/$voms_host"_stderr"
tempo=/tmp/$voms_host"_string"


rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo ""
date
echo "VOMS-listRoles - started, VO=$vo_name"


role1="ROLE1"
role2="ROLE2"
role3="ROLE3"
role4="ROLE4"

echo "Step 1: Create 4 Roles : $role1, $role2, $role3, $role4"

voms-admin --vo=$vo_name -h $voms_host create-role  $role1
voms-admin --vo=$vo_name -h $voms_host create-role  $role2
voms-admin --vo=$vo_name -h $voms_host create-role  $role3
voms-admin --vo=$vo_name -h $voms_host create-role  $role4

echo "OK"

echo "Step 2: Check roles list"

voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp

#cat $voms_tmp

echo "Check 4 roles, "

grep "$role1" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $role1 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$role2" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $role2 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$role3" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $role3 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$role4" $voms_tmp

if [ $? == 1 ]; then
   echo "Group $role4 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi
echo "OK"

echo "Clear Created roles"
voms-admin --vo=$vo_name delete-role $role1
voms-admin --vo=$vo_name delete-role $role2
voms-admin --vo=$vo_name delete-role $role3
voms-admin --vo=$vo_name delete-role $role4

echo "Test is OK"
exit $SAME_OK
