log_user 0 #suppress interactive output

#get AFS user and pass from arguments
set afs_user "[lindex $argv 0]"
set afs_password "[lindex $argv 1]"

spawn kinit $afs_user
expect "Password for " {send "$afs_password\r"}
expect ">" {puts "AFS token retrieved"
            exit 0} \
       "Unable to " {puts "Error retrieving AFS token"
                     exit 1} \
       "Password incorrect " {puts "Error retrieving AFS token: password incorrect"
                     exit 1}


