FILELIST= Api.java \
	Event.java \
	InfoLB.java \
	JobCollectionException.java \
	JobCollection.java \
	JobException.java \
	JobId.java \
	Job.java \
	JobStatus.java \
	ListenerConsole.java \
	Listener.java \
	Query.java \
	ReadingPipe.java \
	Result.java \
	Shadow.java \
	Url.java \
	UserCredential.java \
	UserJobs.java



all:
	for  i in $(FILELIST)
	do echo $i
	done


