# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4-p5 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /opt/edg
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/edg-wl
pkglibdir = $(libdir)/edg-wl
pkgincludedir = $(includedir)/edg-wl

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
ARES_CFLAGS = 
ARES_INSTALL_PATH = /usr
ARES_LIBS =  -lares
AS = @AS@
BOOST_CFLAGS = 
BOOST_FS_LIBS = 
BOOST_INSTALL_PATH = 
BOOST_LIBS = 
BOOST_PYTHON_LIBS = 
BOOST_REGEX_LIBS = 
BOOST_THREAD_LIBS = 
CC = gcc
CFLAGS = -g -O2 -mcpu=i486
CLASSADJ_INSTALL_PATH = 
CLASSADJ_JAR_PATH = 
CLASSAD_CFLAGS = 
CLASSAD_DL_LIBS = 
CLASSAD_INSTALL_PATH = 
CLASSAD_LIBS = 
CLASSAD_PATH = 
COG_INSTALL_PATH = 
COG_JAR_PATH = 
CONDORG_CFLAGS = 
CONDORG_INSTALL_PATH = 
CONDORG_LIBS = 
CPP = gcc -E
CPPUNIT_CFLAGS = @CPPUNIT_CFLAGS@
CPPUNIT_LIBS = @CPPUNIT_LIBS@
CXX = c++
CXXCPP = c++ -E
CXXFLAGS = -g -O2 -mcpu=i486
DLLTOOL = @DLLTOOL@
ECHO = echo
EDGTOP_CXXFLAGS = @EDGTOP_CXXFLAGS@
EXEEXT = 
EXPAT_CFLAGS = 
EXPAT_INSTALL_PATH = /usr
EXPAT_LIBS =  -lexpat
EXPAT_STATIC_LIBS = /usr/lib/libexpat.a
GACL_CFLAGS = -I/opt/edg/include
GACL_INSTALL_PATH = /opt/edg
GACL_LIBS =  -lxml2 -L/opt/edg/lib -lgacl -lxml2
GACL_STATIC_LIBS = /opt/edg/lib/libgacl.a
GCCVER = _gcc3_2_2
GLOBUS_CFLAGS = -I/opt/globus/include/gcc32dbgpthr/openssl -I/opt/globus/include/gcc32dbg/openssl  -I/opt/globus/include/gcc32dbg
GLOBUS_COMMON_NOTHR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lglobus_common_gcc32dbg
GLOBUS_COMMON_THR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lglobus_common_gcc32dbgpthr
GLOBUS_FTP_CLIENT_NOTHR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lglobus_ftp_client_gcc32dbg
GLOBUS_FTP_CLIENT_THR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lglobus_ftp_client_gcc32dbgpthr
GLOBUS_LDAP_CFLAGS = 
GLOBUS_LDAP_FLAVOR = 
GLOBUS_LDAP_INSTALL_PATH = 
GLOBUS_LDAP_LIBS = 
GLOBUS_LIBS =  -L/opt/globus/lib -L/opt/globus/lib  -lglobus_gass_copy_gcc32dbg -lglobus_ftp_client_gcc32dbg -lglobus_gass_transfer_gcc32dbg -lglobus_ftp_control_gcc32dbg -lglobus_io_gcc32dbg -lglobus_gss_assist_gcc32dbg -lglobus_gssapi_gsi_gcc32dbg -lglobus_gsi_proxy_core_gcc32dbg -lglobus_gsi_credential_gcc32dbg -lglobus_gsi_callback_gcc32dbg -lglobus_oldgaa_gcc32dbg -lglobus_gsi_sysconfig_gcc32dbg -lglobus_gsi_cert_utils_gcc32dbg -lglobus_openssl_error_gcc32dbg -lglobus_openssl_gcc32dbg -lglobus_proxy_ssl_gcc32dbg -lssl_gcc32dbg -lcrypto_gcc32dbg -lglobus_common_gcc32dbg
GLOBUS_LOCATION = /opt/globus
GLOBUS_NOTHR_FLAVOR = gcc32dbg
GLOBUS_SSL_NOTHR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lssl_gcc32dbg -lcrypto_gcc32dbg
GLOBUS_SSL_THR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib -lssl_gcc32dbgpthr -lcrypto_gcc32dbgpthr
GLOBUS_SSL_UTILS_CFLAGS = -I$(top_srcdir)/thirdparty/globus_ssl_utils
GLOBUS_SSL_UTILS_LIBS = $(top_srcdir)/thirdparty/globus_ssl_utils/libglobus_ssl_utils.la
GLOBUS_STATIC_LIBS =  -L/opt/globus/lib -L/opt/globus/lib  /opt/globus/lib/libglobus_gass_copy_gcc32dbg.a /opt/globus/lib/libglobus_ftp_client_gcc32dbg.a /opt/globus/lib/libglobus_gass_transfer_gcc32dbg.a /opt/globus/lib/libglobus_ftp_control_gcc32dbg.a /opt/globus/lib/libglobus_io_gcc32dbg.a /opt/globus/lib/libglobus_gss_assist_gcc32dbg.a /opt/globus/lib/libglobus_gssapi_gsi_gcc32dbg.a /opt/globus/lib/libglobus_gsi_proxy_core_gcc32dbg.a /opt/globus/lib/libglobus_gsi_credential_gcc32dbg.a /opt/globus/lib/libglobus_gsi_callback_gcc32dbg.a /opt/globus/lib/libglobus_oldgaa_gcc32dbg.a /opt/globus/lib/libglobus_gsi_sysconfig_gcc32dbg.a /opt/globus/lib/libglobus_gsi_cert_utils_gcc32dbg.a /opt/globus/lib/libglobus_openssl_error_gcc32dbg.a /opt/globus/lib/libglobus_openssl_gcc32dbg.a /opt/globus/lib/libglobus_proxy_ssl_gcc32dbg.a /opt/globus/lib/libssl_gcc32dbg.a /opt/globus/lib/libcrypto_gcc32dbg.a /opt/globus/lib/libglobus_common_gcc32dbg.a -lglobus_gss_assist_gcc32dbg
GLOBUS_THR_CFLAGS =  -I/opt/globus/include/gcc32dbgpthr
GLOBUS_THR_FLAVOR = gcc32dbgpthr
GLOBUS_THR_LIBS =  -L/opt/globus/lib -L/opt/globus/lib  -lglobus_gass_copy_gcc32dbgpthr -lglobus_ftp_client_gcc32dbgpthr -lglobus_gass_transfer_gcc32dbgpthr -lglobus_ftp_control_gcc32dbgpthr -lglobus_io_gcc32dbgpthr -lglobus_gss_assist_gcc32dbgpthr -lglobus_gssapi_gsi_gcc32dbgpthr -lglobus_gsi_proxy_core_gcc32dbgpthr -lglobus_gsi_credential_gcc32dbgpthr -lglobus_gsi_callback_gcc32dbgpthr -lglobus_oldgaa_gcc32dbgpthr -lglobus_gsi_sysconfig_gcc32dbgpthr -lglobus_gsi_cert_utils_gcc32dbgpthr -lglobus_openssl_error_gcc32dbgpthr -lglobus_openssl_gcc32dbgpthr -lglobus_proxy_ssl_gcc32dbgpthr -lssl_gcc32dbgpthr -lcrypto_gcc32dbgpthr -lglobus_common_gcc32dbgpthr
GSOAP_BIN_PATH = @GSOAP_BIN_PATH@
GSOAP_CFLAGS = @GSOAP_CFLAGS@
GSOAP_INSTALL_PATH = @GSOAP_INSTALL_PATH@
GSOAP_LIBS = @GSOAP_LIBS@
GSOAP_STATIC_LIBS = @GSOAP_STATIC_LIBS@
ISODATE = 2004-06-08
JAVA_BIN_PATH = /usr/java/j2sdk1.4.1_01/bin
JAVA_CFLAGS = -I/usr/java/j2sdk1.4.1_01/include -I/usr/java/j2sdk1.4.1_01/include/linux
JAVA_INSTALL_PATH = /usr/java/j2sdk1.4.1_01
JAVA_LIBS = -L/usr/java/j2sdk1.4.1_01/lib
JAVA_VERSION = 1.4.1
LEX = flex
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LOG4CPP_CFLAGS = @LOG4CPP_CFLAGS@
LOG4CPP_LIBS = @LOG4CPP_LIBS@
LOG4J_INSTALL_PATH = /usr
LOG4J_JAR_PATH = /usr/share/java
MAKEINFO = makeinfo
MYPROXY_CFLAGS = 
MYPROXY_INSTALL_PATH = 
MYPROXY_LIBS = 
MYSQL_CFLAGS = 
MYSQL_INSTALL_PATH = /usr
MYSQL_LIBS =  -lmysqlclient -lz
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = edg-wl
PERL_BIN_PATH = 
PERL_INSTALL_PATH = 
PERL_VERSION = 
PJAVA = /usr/java/j2sdk1.4.1_01/bin/java
PMYSQL = /usr/bin/mysql
PPYTHON = 
PRPM = /bin/rpm
PSWIG = 
PYTHON_BIN_PATH = 
PYTHON_CFLAGS = 
PYTHON_INSTALL_PATH = 
PYTHON_VERSION = 
RANLIB = ranlib
RELEASE = 1
RELEASEO = 25
RGMAJ_INSTALL_PATH = /opt/edg
RGMAJ_JAR_PATH = /opt/edg/share/java
RGMA_CFLAGS = @RGMA_CFLAGS@
RGMA_LIBS = @RGMA_LIBS@
RM_CFLAGS = 
RM_INSTALL_PATH = 
RM_LIBS = 
RPMLCTN = 
RPM_BIN_PATH = /bin
RPM_BUILD_PATH = /home1/forge/head/workload/BUILD
RPM_CFLAGS = -I/usr/include -I/usr/include/rpm
RPM_DIR = /home1/forge/head/workload
RPM_INSTALL_PATH = /usr
RPM_LIBS = -L/usr/lib -lrpm -lrpmbuild
RPM_RPMS_PATH = /home1/forge/head/workload/RPMS
RPM_SOURCES_PATH = /home1/forge/head/workload/SOURCES
RPM_SPEC_PATH = /home1/forge/head/workload/SPECS
RPM_SRPMS_PATH = /home1/forge/head/workload/SRPMS
RUNGSOAP = @RUNGSOAP@
RUNPERL = 
RUN_CONDOR_VER = 
SECURITYJ_INSTALL_PATH = /opt/edg
SECURITYJ_JAR_PATH = /opt/edg/share/java
STRIP = strip
SWIG_BIN_PATH = 
SWIG_INSTALL_PATH = 
SWIG_VERSION = 
VERSION = 2.3.0
VOMS_CFLAGS = -I/opt/edg/include
VOMS_CPP_LIBS = -L/opt/edg/lib -lvomsapi_gcc32dbgpthr
VOMS_INSTALL_PATH = /opt/edg
VOMS_LIBS = -L/opt/edg/lib -lvomsc_gcc32dbgpthr
VOMS_STATIC_LIBS = /opt/edg/lib/libvomsc.a
W3C_CFLAGS = @W3C_CFLAGS@
W3C_LIBS = @W3C_LIBS@
WORKDIR = /home1/forge/head/workload
X11R6_CFLAGS = -I/usr/X11R6/include
X11R6_INSTALL_PATH = /usr/X11R6
X11R6_LIBS = -L/usr/X11R6/lib -lXt -lXext -lX11
XERCESJ_INSTALL_PATH = /usr
XERCESJ_JAR_PATH = /usr/share/java
XERCES_CFLAGS = @XERCES_CFLAGS@
XERCES_LIBS = @XERCES_LIBS@
XML2_CFLAGS = -I/usr/include/libxml2
XML2_INSTALL_PATH = /usr
XML2_LIBS =  -lxml2
XML2_STATIC_LIBS = /usr/lib/libxml2.a
YACC = bison -y

wletcddir = $(datadir)/doc/edg-wl-config-2.3.0
wletcd_DATA = LICENSE README

wletcdddir = $(datadir)/doc/edg-wl-services-common-2.3.0
wletcdd_DATA = LICENSE README

wletcdir = $(sysconfdir)
wletc_SCRIPTS = edg-wl-vars.sh edg-wl-vars.csh
wletcutilsdir = $(sysconfdir)/profile.d
wletcutils_SCRIPTS = edg-wl.sh edg-wl.csh

libexec_SCRIPTS = \
	edg-wl-check-daemons.sh \
	edg-wl-services-certs.sh \
	edg-wl-parse-configuration.sh
#ETC_VAL_WM = #wm
ETC_VAL_WM = nowm
#wletcwmdir = #$(sysconfdir)
#wletcwm_DATA = #edg_wl.conf

#wletcwmsdir = #$(sysconfdir)/profile.d
#wletcwms_SCRIPTS = #edg-wl-config.sh

EXTRA_DIST = \
        edg_wl.conf \
        edg-wl.csh.in \
        edg-wl.sh.in \
        edg-wl-vars.sh.in \
        edg-wl-vars.csh.in \
	edg-wl-config.sh.in \
	edg-wl-parse-configuration.sh.in \
	edg-wl-check-daemons.sh.in \
	edg-wl-services-certs.sh \
        LICENSE \
        README.in


CLEANFILES = \
	edg-wl.csh \
	edg-wl-parse-configuration.sh \
	edg-wl.sh \
	edg-wl-vars.sh \
	edg-wl-vars.csh \
	edg-wl-check-daemons.sh \
	edg-wl-config.sh 


MAINTAINERCLEANFILES = Makefile.in *~ *.*~
mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES =  README edg-wl.csh edg-wl.sh edg-wl-config.sh \
edg-wl-vars.csh edg-wl-vars.sh edg-wl-check-daemons.sh \
edg-wl-parse-configuration.sh
SCRIPTS =  $(libexec_SCRIPTS) $(wletc_SCRIPTS) $(wletcutils_SCRIPTS) \
$(wletcwms_SCRIPTS)

DATA =  $(wletcd_DATA) $(wletcdd_DATA) $(wletcwm_DATA)

DIST_COMMON =  README Makefile.am Makefile.in README.in \
edg-wl-check-daemons.sh.in edg-wl-config.sh.in \
edg-wl-parse-configuration.sh.in edg-wl-vars.csh.in edg-wl-vars.sh.in \
edg-wl.csh.in edg-wl.sh.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --foreign etc/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

README: $(top_builddir)/config.status README.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl.csh: $(top_builddir)/config.status edg-wl.csh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl.sh: $(top_builddir)/config.status edg-wl.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl-config.sh: $(top_builddir)/config.status edg-wl-config.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl-vars.csh: $(top_builddir)/config.status edg-wl-vars.csh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl-vars.sh: $(top_builddir)/config.status edg-wl-vars.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl-check-daemons.sh: $(top_builddir)/config.status edg-wl-check-daemons.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
edg-wl-parse-configuration.sh: $(top_builddir)/config.status edg-wl-parse-configuration.sh.in
	cd $(top_builddir) && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

install-libexecSCRIPTS: $(libexec_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libexecdir)
	@list='$(libexec_SCRIPTS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(libexecdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $$p $(DESTDIR)$(libexecdir)/`echo $$p|sed '$(transform)'`; \
	  else if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(libexecdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(libexecdir)/`echo $$p|sed '$(transform)'`; \
	  else :; fi; fi; \
	done

uninstall-libexecSCRIPTS:
	@$(NORMAL_UNINSTALL)
	list='$(libexec_SCRIPTS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(libexecdir)/`echo $$p|sed '$(transform)'`; \
	done

install-wletcSCRIPTS: $(wletc_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcdir)
	@list='$(wletc_SCRIPTS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcdir)/`echo $$p|sed '$(transform)'`; \
	  else if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcdir)/`echo $$p|sed '$(transform)'`; \
	  else :; fi; fi; \
	done

uninstall-wletcSCRIPTS:
	@$(NORMAL_UNINSTALL)
	list='$(wletc_SCRIPTS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcdir)/`echo $$p|sed '$(transform)'`; \
	done

install-wletcutilsSCRIPTS: $(wletcutils_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcutilsdir)
	@list='$(wletcutils_SCRIPTS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcutilsdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcutilsdir)/`echo $$p|sed '$(transform)'`; \
	  else if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcutilsdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcutilsdir)/`echo $$p|sed '$(transform)'`; \
	  else :; fi; fi; \
	done

uninstall-wletcutilsSCRIPTS:
	@$(NORMAL_UNINSTALL)
	list='$(wletcutils_SCRIPTS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcutilsdir)/`echo $$p|sed '$(transform)'`; \
	done

install-wletcwmsSCRIPTS: $(wletcwms_SCRIPTS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcwmsdir)
	@list='$(wletcwms_SCRIPTS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcwmsdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $$p $(DESTDIR)$(wletcwmsdir)/`echo $$p|sed '$(transform)'`; \
	  else if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcwmsdir)/`echo $$p|sed '$(transform)'`"; \
	    $(INSTALL_SCRIPT) $(srcdir)/$$p $(DESTDIR)$(wletcwmsdir)/`echo $$p|sed '$(transform)'`; \
	  else :; fi; fi; \
	done

uninstall-wletcwmsSCRIPTS:
	@$(NORMAL_UNINSTALL)
	list='$(wletcwms_SCRIPTS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcwmsdir)/`echo $$p|sed '$(transform)'`; \
	done

install-wletcdDATA: $(wletcd_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcddir)
	@list='$(wletcd_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcddir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcddir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(wletcddir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(wletcddir)/$$p; \
	  fi; fi; \
	done

uninstall-wletcdDATA:
	@$(NORMAL_UNINSTALL)
	list='$(wletcd_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcddir)/$$p; \
	done

install-wletcddDATA: $(wletcdd_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcdddir)
	@list='$(wletcdd_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcdddir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcdddir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(wletcdddir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(wletcdddir)/$$p; \
	  fi; fi; \
	done

uninstall-wletcddDATA:
	@$(NORMAL_UNINSTALL)
	list='$(wletcdd_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcdddir)/$$p; \
	done

install-wletcwmDATA: $(wletcwm_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(wletcwmdir)
	@list='$(wletcwm_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcwmdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(wletcwmdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(wletcwmdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(wletcwmdir)/$$p; \
	  fi; fi; \
	done

uninstall-wletcwmDATA:
	@$(NORMAL_UNINSTALL)
	list='$(wletcwm_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(wletcwmdir)/$$p; \
	done
tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = etc

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --foreign etc/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libexecSCRIPTS
install-exec: install-exec-am

install-data-am: install-wletcSCRIPTS install-wletcutilsSCRIPTS \
		install-wletcwmsSCRIPTS install-wletcdDATA \
		install-wletcddDATA install-wletcwmDATA
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libexecSCRIPTS uninstall-wletcSCRIPTS \
		uninstall-wletcutilsSCRIPTS uninstall-wletcwmsSCRIPTS \
		uninstall-wletcdDATA uninstall-wletcddDATA \
		uninstall-wletcwmDATA
uninstall: uninstall-am
all-am: Makefile $(SCRIPTS) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libexecdir) $(DESTDIR)$(wletcdir) \
		$(DESTDIR)$(wletcutilsdir) $(DESTDIR)$(wletcwmsdir) \
		$(DESTDIR)$(wletcddir) $(DESTDIR)$(wletcdddir) \
		$(DESTDIR)$(wletcwmdir)


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: uninstall-libexecSCRIPTS install-libexecSCRIPTS \
uninstall-wletcSCRIPTS install-wletcSCRIPTS uninstall-wletcutilsSCRIPTS \
install-wletcutilsSCRIPTS uninstall-wletcwmsSCRIPTS \
install-wletcwmsSCRIPTS uninstall-wletcdDATA install-wletcdDATA \
uninstall-wletcddDATA install-wletcddDATA uninstall-wletcwmDATA \
install-wletcwmDATA tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


install-data-hook:
	if [ $(ETC_VAL_WM) = wm ] ; then \
           /bin/cp $(DESTDIR)$(sysconfdir)/edg_wl.conf $(DESTDIR)$(sysconfdir)/edg_wl.conf.template; \
	fi

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
