disconnect_image = [
"21 21 12 1",
"i c #000000",
"d c #000080",
"e c #0000fe",
"c c #008000",
"f c #008080",
"b c #00ff00",
"g c #00ffff",
"h c #800080",
"# c #808080",
". c #e6e6e6",
"j c #fefefe",
"a c #ff0000",
".....................",
".....................",
".....................",
"......###............",
"....a#.bccc#...a.#...",
"...aaabcccd.ddaaa#...",
"...#aaaceed.daaaf#...",
"..#eeaaaeed.aaagf#...",
"..e.##aaa#daaaffeh...",
"..i.jjjaaaaaaj.j.#...",
"..i.jdddaaaa#.#.##...",
"..i.jd..aaaadddddd...",
"..i.jf.aaaaaa.g......",
"..i#jeaaaejaaa.......",
"...i.aaajjjiaaaig....",
"..i.aaaiiiid.aaa.g...",
"..iaaaj.j.j#diaaai...",
"..iia.#.#.#.d..a.....",
"...iddddddddd........",
".....................",
"....................."
]
connect_image = [
"23 20 11 1",
"a c #000000",
"d c #000080",
"e c #0000fe",
"c c #008000",
"g c #008080",
"b c #00ff00",
"f c #00ffff",
"h c #800080",
"# c #808080",
". c #e6e6e6",
"i c #fefefe",
".......................",
".......................",
".......###.............",
".....##abccc#.....#....",
"....#abbcccdaddddd#....",
"....#cbcceedadfffg#....",
"...#eeceeeedagfffg#....",
"...e.######dhegggeh....",
"...a.iiiiiiiaiiai.#....",
"...a.idddddia#i#.##....",
"...a.idiifgiadddddd....",
"...a.igifigia..f.......",
"...a#iegggeia..a.......",
"....aaiiiiiia...af.....",
"...a.aaaaaaad.faf.f....",
"...a#aaiaiai#daaaaa....",
"...aa#.#.#.#.d.........",
"...iaddddddddd.........",
".......................",
"......................."
]

submit_button = [\
"22 24 180 2",
"aw c #41711b",
"at c #426724",
"as c #436825",
".s c #446328",
"av c #446a1d",
"ar c #446a21",
".i c #446b2c",
"au c #456921",
".o c #466320",
".q c #466426",
".t c #466a2a",
".e c #466a2d",
".r c #47642a",
".N c #476a2a",
"aF c #476f26",
".z c #496825",
"aS c #4a6727",
"aM c #4a6d2b",
".p c #4b6826",
"#0 c #4b6c27",
"ac c #4b6f25",
"ao c #4b732a",
"#f c #4c6c29",
"#O c #4c9506",
".b c #4d6a30",
"#K c #4d6d2a",
"#5 c #4e940f",
"#x c #4f9510",
"#P c #4f9809",
"#R c #4f9b07",
"#A c #50970b",
"#N c #509b0b",
"#4 c #51950e",
"#y c #519712",
"#z c #51980c",
"#Q c #519b0a",
"aa c #52782d",
"aB c #52782f",
"#w c #529813",
"#S c #52a10a",
".L c #53703a",
".c c #547733",
".0 c #547735",
"#6 c #549d10",
"#Y c #557933",
"#2 c #55951b",
"#M c #559815",
"#3 c #569a13",
"#7 c #56a50c",
"aJ c #577736",
"#v c #58981d",
".y c #5b7744",
"aT c #5b7a36",
"aq c #5c7941",
"#d c #5c813b",
"#B c #5ca019",
"#8 c #5cab12",
"#T c #5dac15",
"ak c #5fa618",
"#U c #60ac18",
".n c #617844",
"al c #63ab1b",
"#9 c #64ad1e",
"#I c #668945",
"#C c #66aa23",
"aO c #678b45",
"#k c #68a82d",
"#V c #68af25",
"aP c #69844d",
".g c #69884c",
"#s c #698e48",
"#j c #6bab31",
"ay c #6ca82e",
".m c #6e8859",
"#i c #6eb035",
"#D c #6eb42d",
"aW c #718256",
"#l c #71af30",
"aI c #749e48",
"#h c #75b13f",
"#m c #77b536",
"#F c #78b93b",
".l c #79985c",
".4 c #79b74a",
"#E c #79bc38",
".3 c #7cb650",
"#n c #7cba3f",
"aU c #7d946a",
"#p c #7dba43",
"#o c #7ebe43",
".# c #7f946b",
".5 c #7fb94b",
"aA c #80b24f",
".9 c #80b849",
"## c #80ba4c",
".Q c #81b757",
".6 c #81b94a",
".7 c #82b74b",
".W c #82b954",
"#. c #83bd4d",
"#a c #84bb53",
"#t c #859c70",
".S c #86b557",
"#J c #879e74",
".x c #87aa6a",
".R c #87b958",
".U c #88b75b",
".X c #88bb5c",
".P c #88bb5e",
"an c #88bc57",
".V c #88bc58",
".8 c #88bd51",
".h c #89a072",
"#G c #89c353",
"#W c #8dc850",
".T c #8fbb62",
".H c #90c06c",
".K c #92b771",
".I c #93c36d",
"#q c #93cc61",
"a# c #96c964",
"a. c #96d759",
"#Z c #97ae82",
"#e c #98b380",
"aj c #98d762",
"#1 c #99cd68",
"#L c #99ce66",
"af c #99d068",
"az c #9ad45b",
"am c #9ad85b",
"ad c #9bcb68",
"ai c #9bd469",
"aX c #9caf81",
"aN c #9cc576",
"aG c #9ccd71",
"#u c #9dd06b",
"ah c #9dd266",
"ag c #9ed266",
"ax c #9ed56f",
"aH c #9fce6e",
"#b c #9fd36f",
"ae c #a0d470",
".Z c #a1ca7c",
".v c #a2cc82",
"#c c #a2d078",
".d c #a3ba8c",
"#X c #a3d272",
".Y c #a3d47b",
"ab c #a4be8e",
"#g c #a8da79",
"aK c #a9c094",
"#H c #a9d77d",
"#r c #a9da7f",
"ap c #abc797",
".2 c #abdc81",
"aQ c #acc09b",
"aC c #acc898",
".O c #b0de86",
".J c #b4df8f",
".1 c #b5cfa0",
".w c #b6de95",
".B c #b6e188",
".f c #b7df96",
".A c #b8e088",
".C c #b9e58e",
".G c #bbe599",
"aR c #bcc8b4",
"aL c #bccab3",
".j c #bde79d",
".F c #bee69d",
".a c #bfd6a8",
".u c #bfe8a2",
"aE c #c1dab0",
".D c #c1e897",
".k c #c2e7a1",
".E c #c3e99c",
"aV c #c4d2bb",
"aD c #c7d9bf",
".M c #d0e4bf",
"Qt c #e6e6e6",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.#.aQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.b.c.dQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.e.f.g.hQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.i.j.k.l.mQtQtQtQtQtQtQtQt",
"QtQtQt.n.o.p.q.r.s.t.u.v.w.x.yQtQtQtQtQtQtQt",
"QtQtQt.z.A.B.C.D.E.F.G.H.I.J.K.L.MQtQtQtQtQt",
"QtQtQt.N.O.P.Q.R.S.T.U.V.W.X.Y.Z.0.1QtQtQtQt",
"QtQtQt.N.2.3.4.5.6.7.8.9#.###a#b#c#d#eQtQtQt",
"QtQtQt#f#g#h#i#j#k#l#m#n#n#o#o#p#q#r#s#tQtQt",
"QtQtQt#f#u#v#w#x#y#z#A#B#C#D#E#F#G#H#I#JQtQt",
"QtQtQt#K#L#M#N#O#P#Q#R#S#T#U#V#W#X#Y#ZQtQtQt",
"QtQtQt#0#1#2#y#3#4#5#6#7#8#9a.a#aaabQtQtQtQt",
"QtQtQtacadaeafagahaiajakalamanaoapQtQtQtQtQt",
"QtQtQtaqarasatauavawaxayazaAaBaCaDQtQtQtQtQt",
"QtQtQtQtQtQtQtQtaEaFaGaHaIaJaKaLQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtaMaNaOaPaQaRQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtaSaTaUaVQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtaWaXQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"
]


stop_button=[\
"25 25 363 2",
"aO c #5a080a",
"b2 c #5a0c0c",
"dC c #5d0c09",
"a7 c #630a0e",
"dv c #640a0c",
"dy c #650507",
"bo c #660a0d",
"dB c #660c04",
"bI c #670d0f",
"dA c #680903",
"dz c #680a08",
"dw c #6a070c",
"dx c #6c070d",
"ci c #7c211e",
"dn c #7f1b19",
"#z c #7f4d4e",
"cA c #801c1a",
"bJ c #803f43",
"c9 c #81181d",
"cR c #851b1f",
"cE c #861d1a",
"b4 c #86272d",
"do c #864647",
"cY c #871a17",
"#T c #885051",
"d. c #894145",
"de c #8a1d1a",
"av c #8a4947",
"#S c #8a504e",
"aP c #8b4744",
"cl c #8d2526",
".h c #8d4d4e",
"ab c #8d504f",
"bp c #8e484a",
"dD c #8e5251",
"aa c #8f4949",
"cS c #90504e",
".a c #90514c",
".g c #914d4a",
"au c #924646",
".e c #924c4c",
"a8 c #934d4d",
".b c #93504a",
".c c #944f4a",
".d c #954f4f",
".f c #98534e",
"cD c #98605f",
"cX c #995552",
"du c #9b5555",
"a1 c #a11611",
"cB c #a1645f",
"cf c #a4090d",
"cj c #a67370",
"bT c #a70a11",
".H c #a75c60",
"#d c #a85658",
".k c #a85859",
"#x c #a85c5c",
"#g c #a85e5d",
".t c #a95a5f",
".K c #aa5c58",
".X c #ab5c61",
"b3 c #ab7b7b",
".w c #ac5c5b",
"c# c #ad1210",
".0 c #ad5f5b",
"cc c #ae0f14",
"ck c #af6d6f",
"bS c #b01116",
"bY c #b10c08",
"c6 c #b40701",
"cx c #b4090f",
"bj c #b40d07",
"bG c #b50709",
"bE c #b50a03",
"a5 c #b6090f",
"cO c #b70505",
"aM c #b71b1c",
"#y c #b88c8b",
"bZ c #b90300",
"bm c #b9060c",
"cw c #b9080e",
"b8 c #b91514",
"cP c #b9191b",
"cv c #bc0308",
"b0 c #bc1e1d",
"#f c #bd9490",
"cy c #be1920",
"c7 c #be1f1c",
"c4 c #bf0302",
"cp c #bf0506",
"c5 c #bf0804",
"ca c #c00403",
"a4 c #c00705",
"a2 c #c00903",
"bN c #c01913",
"cg c #c01a1c",
"aU c #c05451",
"a0 c #c08685",
".I c #c08f92",
".u c #c09396",
"c3 c #c10305",
"a3 c #c10400",
"aI c #c14744",
".Z c #c18e8a",
"c2 c #c20106",
"cq c #c20809",
"c1 c #c2080b",
"b7 c #c20c08",
".J c #c2928e",
"bl c #c30101",
"bF c #c30300",
"bk c #c30602",
"cN c #c30604",
"co c #c30d0c",
"cM c #c40000",
"cb c #c40809",
"dm c #c44743",
"#e c #c48e8c",
".Y c #c49190",
"aL c #c52118",
"b1 c #c54a4c",
"cu c #c60307",
".i c #c69598",
"cH c #c70a08",
"ch c #c74545",
".j c #c7999b",
"aB c #c85454",
".v c #c89793",
"cr c #c90809",
"dp c #c9a5a5",
".# c #ca9897",
"cI c #cb0407",
"#I c #cb5553",
"c0 c #cc1e1d",
"c8 c #cc4444",
"#J c #cc5654",
"cQ c #cd4249",
"#k c #cd544c",
"aV c #cd9b9a",
"cJ c #ce0004",
"aC c #ce9c9b",
"cL c #cf0000",
"ct c #cf0101",
"#O c #cf4d4b",
"ap c #cf4e48",
"ba c #cf4f4c",
"#t c #cf5250",
"#q c #cf5554",
"d# c #cfaca8",
"cs c #d00300",
"aK c #d02920",
"cz c #d04447",
"#8 c #d04b44",
"bM c #d11e1a",
"cn c #d12420",
"dq c #d1c2bf",
"b6 c #d22622",
"aJ c #d23129",
"a. c #d24c4b",
"#n c #d25251",
"cG c #d32723",
"#a c #d34b4b",
"#j c #d34c49",
".3 c #d34e49",
"aH c #d3a0a5",
"ad c #d44950",
"#V c #d54c54",
"dE c #d5b6b4",
"cK c #d60405",
"as c #d64645",
"dl c #d64b44",
"Qt c #d6d6d6",
"#p c #d74643",
"bH c #d74b4e",
"#u c #d74c4f",
"bL c #d84244",
".A c #d8474a",
"#P c #d84a48",
"#D c #d84e4c",
"#Q c #d85e5d",
"da c #d8cdc7",
"ag c #d94d4e",
"bU c #d97f81",
".z c #da4b51",
"ax c #da4d53",
"df c #da5252",
"bR c #da7b77",
"#H c #da9091",
"#. c #db494a",
"dk c #db4a45",
".E c #db4a4d",
".C c #db4c44",
".U c #db4c4e",
".4 c #db4d49",
"aq c #dc483e",
".N c #dc494f",
"#X c #dc4a4a",
"## c #dc4e4c",
"bz c #dc7177",
"#K c #dc9291",
"bn c #dd4c53",
"a6 c #dd5058",
"#B c #dd6066",
"#3 c #dd8f8d",
"ar c #de453d",
".D c #de4849",
"#C c #de494b",
"#o c #de4a48",
"dj c #de4c4c",
"aT c #de4e4d",
"#9 c #df4c45",
"#v c #df5a5d",
"aN c #df5e62",
"by c #df7076",
"#2 c #df918f",
"dd c #dfbcb8",
"cW c #dfc7c3",
"br c #e04749",
".5 c #e04a4b",
".B c #e0534c",
"bD c #e06d68",
"bO c #e06e6d",
"bt c #e1423e",
".6 c #e14546",
"aA c #e14749",
".9 c #e1484a",
"#b c #e15e64",
".F c #e16064",
".V c #e16567",
"di c #e25053",
".2 c #e26563",
".Q c #e3443e",
"ay c #e34448",
".T c #e3474b",
"b# c #e34846",
"dF c #e3d7d7",
"db c #e3e4e1",
"aR c #e4484b",
".O c #e4494f",
"#R c #e48686",
"dr c #e4e3df",
".P c #e54449",
".M c #e56365",
"dK c #e5c3c1",
"ae c #e6454a",
"aS c #e64849",
"b5 c #e65e62",
"cV c #e6e5e1",
"af c #e7464b",
"#W c #e7484c",
"dg c #e75256",
"cZ c #e7534f",
"dJ c #e7c3c3",
"cT c #e7c8c3",
"dc c #e7dcda",
"az c #e84347",
".8 c #e84643",
"b. c #e84644",
"dh c #e84f54",
"cF c #e85955",
".y c #e86269",
"#i c #e86666",
"bi c #e86e69",
".S c #e94448",
".R c #e94742",
".7 c #e94744",
"#Y c #ea8684",
"bb c #ea918d",
"dt c #eac7c5",
"dL c #eac9c4",
"bu c #eb8581",
"dO c #ebe1e1",
"bK c #ee7f85",
"#w c #ee8486",
"a# c #ef8383",
".W c #ef888c",
"#A c #ef9499",
"dI c #efcbcd",
"dM c #efd2ce",
"bs c #f0413e",
"cm c #f05c5a",
"ah c #f0898a",
"#E c #f0938e",
"at c #f17a7c",
"#7 c #f19691",
"aD c #f1e3e2",
"cU c #f1e8e3",
"aE c #f1ebeb",
"aF c #f1ebed",
".l c #f28e8e",
".s c #f28f92",
"aj c #f2dedf",
".G c #f38a8e",
"aX c #f3e9e7",
"#c c #f4858b",
"#N c #f59c98",
"aY c #f5edea",
"#h c #f68f90",
"ds c #f6e8e7",
".L c #f78e8b",
"ao c #f79997",
"#m c #f88582",
".1 c #f98d8d",
"#1 c #f9d2d3",
"dH c #f9d5d9",
"am c #f9e4eb",
"dN c #fadedd",
"aW c #fae8e6",
"cd c #fb6c72",
"c. c #fb6d6b",
"#l c #fb8881",
"bX c #fb8b89",
"#0 c #fbd9da",
"cC c #fbe3e1",
"aZ c #fbeded",
"#U c #fc949d",
".x c #fe8d91",
"#r c #fe8e8d",
".o c #fe918e",
".r c #fe9290",
"ac c #fe9399",
"ai c #fed2d3",
"ak c #fee0e0",
"al c #fee0e2",
"aG c #fef1f8",
"b9 c #ff6c6d",
"ce c #ff797e",
"#s c #ff8c89",
"bq c #ff8f93",
"aQ c #ff9092",
".q c #ff918d",
"a9 c #ff9191",
".m c #ff9391",
".p c #ff948f",
".n c #ff9492",
"aw c #ff9699",
"#Z c #ffcaca",
"#G c #ffcbca",
"#F c #ffcdc7",
"bP c #ffcfcc",
"bv c #ffd2cf",
"bQ c #ffd8d1",
"#L c #ffd8d7",
"bc c #ffdbd8",
"bx c #ffdcd8",
"#M c #ffdcda",
"#6 c #ffdddb",
"bw c #ffded6",
"#4 c #ffdedf",
"be c #ffdfde",
"dG c #ffe0e7",
"bd c #ffe2e0",
"bf c #ffe3e1",
"bW c #ffe4e4",
"bh c #ffe5e3",
"an c #ffe6ea",
"#5 c #ffe8e9",
"bA c #ffe9eb",
"bC c #ffeae5",
"bV c #ffebec",
"bg c #fff0ef",
"bB c #fff4f2",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.#.a.b.c.d.e.f.g.h.iQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.j.k.l.m.n.o.p.q.r.s.t.uQtQtQtQtQtQt",
"QtQtQtQtQtQt.v.w.x.y.z.A.B.C.D.E.F.G.H.IQtQtQtQtQt",
"QtQtQtQtQt.J.K.L.M.N.O.P.Q.R.S.T.U.V.W.X.YQtQtQtQt",
"QtQtQtQt.Z.0.1.2.3.4.5.6.7.8.9#.###a#b#c#d#eQtQtQt",
"QtQtQt#f#g#h#i#j#k#l#m#n#o#p#q#r#s#t#u#v#w#x#yQtQt",
"QtQtQt#z#A#B#C#D#E#F#G#H#I#J#K#L#M#N#O#P#Q#R#SQtQt",
"QtQtQt#T#U#V#W#X#Y#Z#0#1#2#3#4#5#6#7#8#9a.a#aaQtQt",
"QtQtQtabacadaeafagahaiajakalamanaoapaqarasatauQtQt",
"QtQtQtavawaxayazaAaBaCaDaEaFaGaHaIaJaKaLaMaNaOQtQt",
"QtQtQtaPaQ.UaRaSaTaUaVaWaXaYaZa0a1a2a3a4a5a6a7QtQt",
"QtQtQta8a9#.b.b#babbbcbdbebfbgbhbibjbkblbmbnboQtQt",
"QtQtQtbpbqbrbsbtbubvbwbxbybzbAbBbCbDbEbFbGbHbIQtQt",
"QtQtQtbJbKbLbMbNbObPbQbRbSbTbUbVbWbXbYbZb0b1b2QtQt",
"QtQtQtb3b4b5b6b7b8b9c.c#cacbcccdcecfbGcgchcicjQtQt",
"QtQtQtQtckclcmcncocpcqcrcsctcucvcwcxcyczcAcBQtQtQt",
"QtQtQtQtcCcDcEcFcGcHcIcJcKcLcMcNcOcPcQcRcScTcUQtQt",
"QtQtQtQtcVcWcXcYcZc0c1c2c3c4c5c6c7c8c9d.d#dadbQtQt",
"QtQtQtQtQtdcdd.cdedfdgdhdidjdkdldmdndodpdqdrQtQtQt",
"QtQtQtQtQtQtdsdtdudvdwdxdydzdAdBdCdDdEdFQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtdGdHdIdJdKdLdMdNdOQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"
]
dir_image_data = [
"32 32 10 1",
". c None",
"# c #000000",
"b c #00c000",
"e c #303030",
"h c #400000",
"d c #585858",
"g c #a0a0a4",
"f c #c0c0c0",
"a c #c0ffc0",
"c c #ffffff",
"...###..........................",
"...#aa##........................",
".###baaa##......................",
".#cd##baaa##....................",
".#cccd##baaa##..##e.............",
".#cccccd##baaa##aaa##...........",
".#cccccccd##baaaaaaaa##.........",
".#cccccccccd##baaaaaaa#.........",
".#cccccfcffgg#bbbbaaaaa#........",
".#ccccccfcfffd#bbbbbbaa#........",
".#cccfcfcfcffgd##bh#bbba#.......",
".#ccccfcfffffffgd#dd##ba#.......",
".#cfcfcfcfffffffffgfgd#bb#......",
".#ccfcfffffffffgfgfgfgd#b#......",
".#cfcfcfffffffffgfgfggd#b#......",
".#fcfffffffffgfgfgggggd#b#......",
".#cfcfffffffffgfgfggggd#b#......",
".#fffffffffgfgfgggggggdhb#......",
".#ffffffffffgfgfggggggd#b#......",
".#ggfffffgfgfgggggggggd#b#......",
".#ddggffffgfgfggggggggd#b#......",
"..##ddggfgfgggggggggggd#b#......",
"....##ddgggfggggggggggd#b#......",
"......##ddggggggggggggd#b#......",
"........##ddggggggggggd#b#......",
"..........##ddggggggggd#b#......",
"............##ddggggggd#b###....",
"..............##ddggggd#b#####..",
"................##ddggd#b######.",
"..................##ddd#b#####..",
"....................##d#b###....",
"......................####......"
]

file_image_data = [
"32 32 61 1",
"b c #000000",
"c c #010101",
"f c #020202",
"2 c #040404",
"X c #060606",
"d c #070707",
"W c #0a0a0a",
"y c #0b0b0b",
"P c #0c0c0c",
"6 c #0d0d0d",
"e c #0e0e0e",
"Z c #121212",
"T c #131313",
"5 c #171717",
"i c #1c1c1c",
"U c #bcbcbc",
"V c #c1c1c1",
"M c #c5c5c5",
"N c #c9c9c9",
"4 c #cccccc",
"F c #cdcdcd",
"G c #d0d0d0",
"L c #d4d4d4",
"j c #d5d5d5",
"O c #d8d8d8",
"D c #d9d9d9",
"w c #dadada",
"p c #dbdbdb",
"z c #dddddd",
"C c #dedede",
"J c #e1e1e1",
"1 c #e2e2e2",
"x c #e3e3e3",
"Q c #e4e4e4",
"R c #e5e5e5",
"Y c #e6e6e6",
"l c #e7e7e7",
"q c #e8e8e8",
"3 c #e9e9e9",
"o c #eaeaea",
"H c #ebebeb",
"S c #ececec",
"m c #ededed",
"I c #eeeeee",
"K c #efefef",
"k c #f0f0f0",
"u c #f1f1f1",
"B c #f2f2f2",
"r c #f3f3f3",
"t c #f4f4f4",
"h c #f5f5f5",
"v c #f6f6f6",
"0 c #f7f7f7",
"A c #f8f8f8",
"s c #f9f9f9",
"a c #fafafa",
"g c #fbfbfb",
"n c #fcfcfc",
"E c #fdfdfd",
"# c #fefefe",
". c #ffffff",
".#abccbbbbbbbbbbbdbefb.gg.hg#...",
"...ijkklmmmmmmmmno.pabb..a..hqk.",
"rstbgtuvuuuuuuuuj.wrxyzb.Am....B",
"...baCxBoooooooohDuEhbFGy..rBH.v",
"srtbmBhIBBBBBBBB.JsaKbLMNbI.s.O.",
".ngPQhhRSSSSSSSSlIHpoTUpVjW..n.E",
"n..XQYSIIIIIIIIItoSEkbybZbbb.t0.",
"E..bEuItSSSSSSSSkC.JnzgK1.QcE#.k",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
".#.buokIIIIIIIIIIIIIIIIIkoub.n.E",
"E..bEuItSSSSSSSSSSSSSSSSmJ0b.Ag.",
"n..XQYSIIIIIIIIIIIIIIIIIHK0cA.gv",
".ngPQhhRSSSSSSSSSSSSSSSSmSQbB...",
"srtbmBhIBBBBBBBBBBBBBBBBBQJ2.KA.",
"...baCxBooooooooooooooool3ty.s..",
"rstbgtuvuuuuuuuuuuuuuuuuu.Hbkq.S",
"...ijkklmmmmmmmmmmmmmmmmov45....",
".#abccbbbbbbbbbbbbbbbbbbb6ebg.H."
]

cern_logo_image_data = [
"100 100 47 1",
"i c #00294f",
". c #002e53",
"k c #06345a",
"z c #0e3c61",
"d c #103b5f",
"r c #113e62",
"j c #1b476a",
"l c #224c6e",
"h c #234f72",
"B c #2c5576",
"C c #355c7c",
"M c #39607f",
"m c #3c6382",
"L c #466a88",
"# c #4d718d",
"S c #4f7390",
"P c #50738f",
"A c #587a94",
"q c #5f809b",
"Q c #607f97",
"H c #69869d",
"n c #6c8ba3",
"R c #6f90a9",
"F c #718ea5",
"b c #7995ab",
"a c #7e9ab0",
"c c #819aaf",
"y c #839db2",
"I c #8ba3b7",
"e c #94aabb",
"w c #98afc0",
"v c #9ab1c2",
"p c #a7bac9",
"O c #a8bfd1",
"N c #aec1cf",
"u c #afc1d0",
"E c #b1c2ce",
"K c #b8c8d5",
"x c #c1ced9",
"J c #c6d3dd",
"o c #cbd8e1",
"t c #d4dee6",
"G c #dde5eb",
"s c #e2e9ee",
"D c #e6ecf1",
"g c #edf2f5",
"f c #fefefe",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"...#abbbababbbaaaabbbbbabbbbbabbbbbbcbabbabbabbbbbbbaabbabbbbbbbbbbbbabbbbbbaabbbabbbbbabbbbbbad....",
"...efffffffffffffffffffgfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffh....",
"...efii...i.ii.i..iiiii..i...i..i.i.ii.i....i...ii...i..i...ii.i...ii.i..i...i..i.i.ii.i...i.jfh....",
"...efi....................................................................k..................lfj....",
"...efi.......................................................................................jfh....",
"...efi.......................................................................................lfl....",
"...ef........................................................................................lfj....",
"...efi......k...k............................................................................jfh....",
"...ef................................kjhlhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhlhhhhhhhhhhhhmfh....",
"...efi.....k.............k......jnogfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffl....",
"...efi..k....................jpffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffj....",
"...efi.........k...........qgffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffj....",
"...ef................k...#fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffh....",
"...efi.................rsfffffffffffgtuvwwpxgffffffffffffgwvvvvvevvvvvvvvwwveevvvvvvvvvvvvvvvpfj....",
"...efi................afffffffffgyh...........zAoffffffffftk.................................jfj....",
"...efi...............tffffffffer..................AgffffffffB.....k..........................jfh....",
"...ef..............zgfffffffb.......................CDfffffffA...............................jfl....",
"...efi............rfffffffE..............k......i.kjl.AfffffffFi.............................jfj....",
"...efi...........zfffffffm...................CeGfffffglktffffffH.............................jfl....",
"...efi..........kffffffDk.................AGfffffffffffeiIffffff#......................gGeB..jfj....",
"...ef...........Dfffffo................rEfffffffffffffffs.Affffffh.....................fffA..jfj....",
"...ef..........pfffffJ...........z...dKffffffffoyLhrrkzjMF.Lffffff.pC.................lfffj..jfh....",
"...efi........mffffft..............iyffffffgbj..............HfffffxifJk...............Afff...jfl....",
"...efi........fffffg..............rgfffffxl...........k......efffffL#ffA..............Nffg...jfj....",
"...ef........wfffffj.............Afffffxz............k........DfffffisffE............isffJ...rfl....",
"..kefi......zfffffb.............vffffgBi......................dfffffbBfffs............fffy...jfj....",
"...efi......Offffg.............Effffp........................k.cfffff.sfffgk.........kfffm...jfj....",
"...efi.....kfffffC.......k...iKffffP............................fffffHjfffffk........Cfffd...jfh....",
"...efi.....affffG............pffffB........k...k................Affffgi.gfffg........bfff....jfj....",
"...efi.....gffffm...........Hffffj...............k...............fffffj..gfffo.......offD....jfh....",
"...ef.k...jfffffi..........lffffh..........................k.....effffe...gfffb......gffu....jfl....",
"...efi....yffffe....z.....igfffP.................................rfffff...kffffj.....fffH....jfj....",
"...ef.....Dffffj..........BIEte..................................igffffk...Cfffg....rfffh....jfl....",
"...ef.....fffff...................................................vffffP....pfffn...#fff.....jfj....",
"...efi...rfffft......i........ii...i.....i.i......................mffffE.....gfff...wfff.....jfj....",
"...ef....Lffffy.....ygffffKB.jfgffffffk.tfgfgDwk....ffti....gp....dffffgi....Lfffa..Gfft.....jfh....",
"...ef....affffL...rffnrkdPsfijfyCCCCCC..tfCCCyffz...fOfQ...ifO.....fffff......Dfff..fffe.....jfj....",
"...efi...pffffj...ffk......m.jfAi......itf....Bfe...fnKf....fO....ifffffr.....mfffP.fffL.....jfj....",
"...efi...Jffffz..#fA.........jfQ........tf....rfw...fnkfJ..ifO.....DffffQ.....igffGlfffj.....jfl....",
"...ef....offffd..pfk.........jfstttttt..tfi...ufj...fn.PfL..fE.....GffffK......bfffFfff......jfj....",
"...ef....offffz..ofk.........jfObbbFbc..GfoJoffC....fn.itf..fE.....Gffffgi.....zffffffg......jfj....",
"...efi...xffffk..pfk.......k.jfH........tfFaEfH.....fn..dfp.fN.....sfffffk....k.gfffffx.k....jfh....",
"...efi...uffffr..mfb.........jfQ........Gfi.ipfF....fn...bflfO.....ffffffj......wfffffb......jfl....",
"...ef....yffffm...gfhi....ib.jfA........tf....pfb...fn....ggfu.....ffffffn......mfffffB......jfj....",
"...ef....#ffffb...kgfKLmLefgijfKIIIyII..tfi...iefa..fn....jffu....kffffffx......kfffffk......jfl....",
"...ef....lffffJ.....AogffoHk.rtttttttGk.OG......Itn.tA.....yte....Bfffffff.......fffff.......jfj....",
"...efi...kfffff.........i...........ii..i.........................Ifffffff.......ffffGi......jfj....",
"...efi....Dffffz.....................k............................Dfffffffl......gfffp.......jfh....",
"...ef.....vffffR.....BuoG....................k.k.................kffffffffF......GfffA.......jfj....",
"...efi....Cffffg.....Lfff....................k...................Fffffffffx......Gfffj.......jfj....",
"...efi.....fffffj....Lfff.......................z................gfffffffffi.....sfff........jfl....",
"...efi.....DffffJ....Bfffk......................................Cfffffgffff......gffg........jfl....",
"...efi.....vfffffj...rfffj......................................DffffyEffffB.....fffo........jfl....",
"...efi.....mfffffti...fffm...........k........k................Sfffff.Pffffb.....fffI........jfj....",
"...ef.......ffffffL..ifffI.........................k......k....fffffe.jffffoi...jfffm........jfl....",
"...ef.......gffffffk..Gfft...................................ixfffffk.ifffff....nfff....k....jfl....",
"...efi......vffffffG..Ifff....k....................k.........QfffffH...Dffffk...Jffg.........jfj....",
"...ef.......mfffffffpiBfffB.................................Bfffffs....pffffC..ifffv.........jgl....",
"...ef........ffffffffI.Gffp................................jffffffk....#ffffy..CfffB.........jgj....",
"...ef....k...gffffffffIiJff.......k.........k......k......BffffffL.....rfffft..offf..........jgj....",
"...ef........pfffffffffEibfP.............................LffffffI.......fffff.kfffp..........jsl....",
"...efi.......mffffffffffgdjG...................k........effffffpi.......sffffkwfffj......k...rfl....",
"...efi.......kffffffffffffHik.........................lgffffffp.........vffffmIffG...........rfl....",
"...ef.........gffffmfffffffgCi......................kEfffffffJ..........LffffemffB.......k...jfj....",
"...ef.........pffffAjgfffffffDL...................jKfffffffft...........zffffGkft............jfj....",
"...efi........LffffK..offfffffffNC............ijcgfffffffffs.............fffffifj............jfj....",
"...efi.....k..kfffff...PfffffffffffgxyQLmLAROsffffffffffffD..............Gffffkn.............jfl....",
"...ef..........gffffz....pfffffffffffffffffffffffffffffffg.......k.......effffL..........k...jfj....",
"...ef.....k...kOffff#.....dpffffffffffffffffffffffffffffgk...............Lffffv..............jfh....",
"...ef........k.LffffK........Hgfffffffffffffffffffffffffk...............BkffffD............k.jfl....",
"...ef..........kffffgi.........kAJffffffffffffftfffffffk...............Ffifffff..............jfl....",
"...efi..........gffffk.....k..BGnji.jCAHynALjkivffffffz...............Off.offffz.............jfj....",
"...efi..........ufffDB.........hfffgon........effffffj..............jgfffByffff#.............jfh....",
"...efi..........meB.............zgffffsj.....Iffffffj..............wfffffBCffffp.............jfl....",
"...efi..k.........................Jfffffoj..bffffffl.............bfffffgr.kffffDi............jfj....",
"...efi.............................AffffffznffffffC..........ilpffffffe...ifffff.............jfj....",
"...efi......................z........KfffrAffffffm........zLOfffffffGj.....offffr............jfh....",
"...efi.......................k........ror#ffffffLdGoKOoGDfffffffffsm.......bffffA............jfl....",
"...ef...........k.......................LffffffAkgffffffffffffffKli........BffffO............jfl....",
"...efi.....k...........................BffffffnkgffffffffffffKm.............ffffg............jfj....",
"...efi...................k...k........Bffffffb.jHvKtDDGJpRBk................gffff............jfh....",
"...ef.....................k..........lffffffy..................k............xffffj...........jfj....",
"...efi..............................jffffffI................................nffffn...........jfj....",
"...ef..............................rffffffp......k..........................lffffK...........jfl....",
"...ef.................k...........zffffffNi..................................ffffg...........jfh....",
"...efi...k.......................kffffffK.................................k..gffff...........jfl....",
"...efi.....................k...k.gfffffJi..........k.........................Kffffh..........jfl....",
"...efi..........................gfffffti.....................................Hffffn..........jfj....",
"...ef...................k......sfffffG................z............k.........jffffK..........jfh....",
"...efi................k.......GfffffD..........................i..............fffff..........jfj....",
"...efdzjrzrrzrzzrrrrrrrrzrzzztffffffrzdzzzzzkdzzzdzzzzzzddzzddddzdzzzzzzkdzzzkgffffrzzzdzzzzzBfl....",
"...effffffffffffffffffffffffffffffffffffffffffffffffffffffffgfggfffffffffffffffffffffffffffffffl....",
"...jBBBBBCBBBBBBBBBBCBBBBBBBBBBBBBCBBBBCBBBBBBBBCBBBBBBBBBBBBBBBBBBBBBBBBBBBBCBBBCBBBBBBBBBBCBBk....",
"....................................................................................................",
"....k...........k....................................................k..............................",
"....................................................................................................",
"..k................................................................................................."
]
lhcb_logo_image_data = [
"100 68 24 1",
"a c #444388",
"e c #4d4d8e",
"l c #565894",
"h c #5f629a",
"# c #696da1",
"t c #6e396d",
"i c #7278a7",
"o c #7b82ad",
"r c #83345f",
"d c #858db4",
"f c #8e98ba",
"n c #97a2c0",
"m c #a1adc7",
"k c #aab7cd",
"g c #b3c2d3",
"j c #bdcdda",
"s c #c32537",
"b c #c6d7e0",
"q c #ce2330",
"c c #cfe2e6",
". c #d9eded",
"u c #dcc5c5",
"v c #eb3636",
"p c #ee1c1c",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"..........................................................................#aaaaaab..................",
"............................................................................aaaaa...................",
".............................................................................aaaa...................",
".............................................................................aaac...................",
"............................................................................daaa....................",
"............................................................................aaaa....................",
"............................................................................aaaa....................",
"............................................................................aaa.....................",
"...........................................................................aaaa.....................",
"...........................................................eaaaaf...a......aaaa......g..............",
".........aaaaaaaaag........faaaaaaaaaf.aaaaaaaaaa.......aaaae...haaaa......aaa....aaaaaaa...........",
"...........aaaaa..............aaaaa......caaaaa.......#aaaa.......aaa.....iaaa..iaaaaaaaaa..........",
"...........aaaaj..............aaaa........aaaa.......aaaaa........aa......aaaa.aa.....eaaaa.........",
"...........aaaa..............haaaa.......aaaaa......aaaaa.........ka......aaajaa.......aaaa.........",
"..........aaaaa..............aaaaa.......aaaaa.....aaaaa...........a.....aaaaga........aaaa.........",
"..........aaaal..............aaaaj.......aaaa.....baaaa#...........g.....aaaaa.........aaaa.........",
"..........aaaa..............baaaa.......maaaa.....aaaaa..................aaaa..........aaaa.........",
".........aaaaa..............aaaaa.......aaaaa.....aaaaa.................maaaa..........aaaa.........",
".........aaaal..............aaaaaaaaaaaaaaaal....daaaak.................aaaa..........laaa..........",
".........aaaa..............naaaa.......iaaaa.....aaaaa..................aaaa..........aaaa..........",
"........aaaaa..............aaaaa.......aaaaa.....aaaaa.................iaaa..........aaaa...........",
"........aaaaa..............aaaah.......aaaan.....aaaaa.................aaaa..........aaaa...........",
"........aaaa...............aaaa.......baaaa......aaaaa.................aaaa.........aaae............",
".......oaaaa..........a...aaaaa.......aaaaa......oaaaa.................aaac........aaaa.............",
".......aaaaa.........aa...aaaaa.......aaaaa.......aaaaf.........aa....aaaa........aaak..............",
".......aaaa.........aa...baaaa........aaaa.........aaaa.......fae.....aaaa.......aaa................",
"......aaaaa.......aaaa...aaaaa.......aaaaa..........aaaaa...oaaf......aaaa.....aaag.................",
"....aaaaaaaaaaaaaaaaaa.aaaaaaaaa..#aaaaaaaaag.........aaaaaaa...........baaaaaae....................",
"aaaa..................a.........aag.........#aaaaaaaaal.....daaaaaaaaaaaao....gaaaaaaaaaapppppaaaaaa",
"aaaaaa.....aaaaaac....aaa.....aaaaaaa.....aaaaaaaaaa......g....aaaaaaae...jaaad...aaaaapppppaaaaaaaa",
"aaaaaaa....aaaaaaaab..aaam....aaaaaaaa....aaaaaaaaa....gaaaaaa..aaaaaa....aaaaaak..naqppppaaaaaaaaaa",
"aaaaaaa....baaaaaaaaa..aaa....caaaaaaa....maaaaaaa.....aaaaaaaaa.jaaaa....aaaaaaaa...pppaaaaaaaaaaaa",
"aaaaaaa.....aaaaaaaaaa.aaa.....aaaaaaa.....aaaaaal....aaaaaaaaaaaiaaaal...aaaaaaarp...kaaaaaaaaaaaaa",
"aaaaaaaa....aaaaaaaaaaiaaah....aaaaaaan....aaaaaa.....aaaaaaaaaaaaaaaaa....aaaaapppp...eaaaaaaaaaaaa",
"aaaaaaaa.....aaaaaaaaaaaaaa....oaaaaaaa....eaaaaa.....aaaaaaaaaaaaaaaaa....aaappppsaa...haaaaaaaaaaa",
"aaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaaaa....apppppaaaa....aaaaaaaaaaa",
"aaaaaaaal....aaaaaaaaaaaaaab....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaaaaa....pppaaaaaaa....aaaaaaaaaa",
"aaaaaaaaa....daaaaaaaaaaaaaa................oaaaac....aaaaaaaaaaaaaaaaaa....paaaaaaaaa....aaaaaaaaaa",
"aaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaaaaaaaatpu...oaaaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa....aaaaaaaaaaaaaan....aaaaaaaj....aaaaa.....aaaaaaaaaaaaatpppp....aaaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa....daaaaaaaaaaaaaa....aaaaaaaa....aaaaag....eaaaaaaaaaaappppsa.....aaaaaaaaa....aaaaaaaaa",
"aaaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaa.....aaaaaaaaapp.psaaa.....maaaaaaaa....aaaaaaaaa",
"aaaaaaaaaao....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaaa.....aaaaaapppv.aaaaaa...a.caaaaaaa....aaaaaaaaa",
"aaaaaaaaaaa....aaaaaaaaaaaaaaa....aaaaaaal....aaaaaaa....oaaappppp..aaaaaa....a.jaaaaae....aaaaaaaaa",
"aaaaaaaaaaa.....aaaaaaaaaaaaaa.....aaaaaaa.....aaaaaaa.....pppppaa..jaaaaa....aa..cae.....aaaaaaaaaa",
"aaaaaaaaa.........#aaaaaaaaf.........fa..........aaaaaag....ppaaa....aaaaaa...aaaf.......caaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaatpp.......gaa.aaaaaa...kaaaaa...oaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapppppaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapppaaaaaaaaaaaaaaaaaa#...aaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...baaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac...aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.......aaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadmaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
]
image0_data = [
"22 22 7 1",
". c None",
"# c #000000",
"b c #2e2e2e",
"c c #5c5c5c",
"d c #878787",
"e c #c2c2c2",
"a c #ffffff",
"......................",
"....##########........",
"....#aaaaaaa#b#.......",
"....#aaaaaaa#cb#......",
"....#aaaaaaa#dcb#.....",
"....#aaaaaaa#edcb#....",
"....#aaaaaaa#aedcb#...",
"....#aaaaaaa#######...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....###############...",
"......................",
"......................"
]
image1_data = [
"22 22 5 1",
". c None",
"# c #000000",
"c c #848200",
"a c #ffff00",
"b c #ffffff",
"......................",
"......................",
"......................",
"............####....#.",
"...........#....##.##.",
"..................###.",
".................####.",
".####...........#####.",
"#abab##########.......",
"#babababababab#.......",
"#ababababababa#.......",
"#babababababab#.......",
"#ababab###############",
"#babab##cccccccccccc##",
"#abab##cccccccccccc##.",
"#bab##cccccccccccc##..",
"#ab##cccccccccccc##...",
"#b##cccccccccccc##....",
"###cccccccccccc##.....",
"##cccccccccccc##......",
"###############.......",
"......................"
]

image2_data = [
"15 16 194 2",
"aU c #00012a",
"aF c #000a39",
"aq c #030e41",
"aV c #090932",
"ab c #09154b",
"a8 c #0d0d34",
"aG c #0d0d3a",
"ar c #0d0d3c",
"ac c #0d0d3f",
"#Z c #0d0d42",
"#K c #0d0e43",
"#x c #0f1046",
"#Y c #101c55",
"a7 c #111141",
"#i c #111248",
".5 c #13144b",
".Q c #15164d",
".G c #171752",
"#J c #18265f",
"aY c #1a1957",
"a6 c #1a1a50",
"aZ c #1a1a52",
".w c #1c1b50",
"a5 c #1c1c52",
"a9 c #1c1d47",
"a4 c #1d1d53",
"a2 c #202055",
"a3 c #212154",
"a1 c #232357",
"a0 c #252559",
"aX c #262765",
".l c #272965",
"#w c #28366e",
".C c #2f4f90",
"aT c #33396b",
"aI c #363775",
"#h c #36437c",
".4 c #3b4a82",
"#g c #3f548b",
"#v c #41558b",
"aE c #424e81",
"at c #454883",
"#f c #455b91",
".k c #474884",
".P c #495890",
"ap c #4c5787",
".s c #4f6ba5",
"ae c #50548c",
"aa c #566193",
"#e c #576ea3",
".j c #58588e",
"aJ c #586598",
"#u c #58689a",
".B c #5975aa",
"#1 c #5a5e94",
"#t c #5f70a1",
"#X c #616c9e",
".i c #626295",
"#M c #64669b",
".F c #6478ac",
"au c #677dac",
"#d c #6983b3",
".h c #6b6b9b",
"#s c #6b7cac",
"#I c #6c78a5",
"#z c #6e72a2",
".v c #707cb0",
".g c #7575a4",
"#k c #777caa",
"af c #778db8",
"#c c #778fbf",
"#r c #788db8",
"aK c #7d83ad",
".3 c #7e8fb5",
".f c #7f7fab",
"aS c #807faa",
"aR c #8080a9",
"#b c #8199c5",
".7 c #8386b3",
"aC c #8686b7",
"aD c #8887b9",
"aQ c #8a8aaf",
".e c #8a8ab4",
"#q c #8a9bc5",
"#a c #8aa1cb",
"#2 c #8ba1ca",
".S c #8e92ba",
"aB c #9090bf",
"aP c #9191b7",
".r c #93a6cb",
"an c #9494bf",
"av c #949fc6",
"## c #94a9d1",
"ao c #9695c1",
"#p c #98aad0",
".M c #98aed2",
".d c #9999bf",
"aA c #9999c6",
".I c #999bc2",
"aO c #9b9bbe",
"#N c #9baed4",
"am c #9d9dc8",
"a. c #9d9dc9",
"ag c #9eabd0",
"#. c #9eb1d7",
"a# c #a09fca",
"az c #a2a2ce",
"#o c #a3b6d8",
".L c #a4b5d5",
"#A c #a4b7db",
".c c #a5a4c6",
"aN c #a5a5c4",
".y c #a5a6cb",
".b c #a6a6ca",
"al c #a6a6cf",
"#9 c #a7a7d0",
"#m c #a8bbdb",
".m c #a9adbd",
".9 c #a9bbdd",
"#V c #aaaad4",
"ay c #ababd6",
".# c #abadcd",
"#n c #acbddd",
"#W c #aeadd5",
"aM c #afafcd",
".o c #afb0d1",
".a c #afb1d0",
"ak c #b0b0d6",
"#8 c #b1b1d7",
"#3 c #b1bdda",
"#l c #b4c4e3",
"#U c #b5b5da",
"ax c #b5b5dd",
".O c #b5c4dc",
"aj c #babadd",
"#7 c #bbbbdf",
".E c #bdcce4",
".2 c #bec9de",
"#T c #bfbfe2",
"#O c #c0cbe4",
".8 c #c1d0ec",
"aL c #c3c2da",
"ai c #c3c3e5",
".D c #c3cee5",
"#6 c #c4c4e6",
".t c #c6d1e5",
"#B c #c7d3e6",
".T c #c8d6ef",
"#S c #c9c8e8",
"aw c #cac9ec",
".1 c #cad6e9",
"#H c #cdcde5",
"#G c #cdcde6",
"#5 c #ceceed",
".0 c #cfd8eb",
".U c #cfdaee",
".Z c #d1dbec",
"#R c #d2d2f0",
".u c #d3def0",
".J c #d3e0f4",
".Y c #d4deef",
"ah c #d9d7f1",
"#F c #d9d9ee",
".X c #d9e2f3",
"#Q c #dbdbf4",
"b# c #dbdfe3",
"b. c #dce0e4",
"aW c #dde1e5",
"aH c #dee2e6",
".W c #dee6f4",
"as c #dfe3e7",
"ad c #dfe4e8",
"#0 c #e0e5e9",
".z c #e0ebfc",
"#L c #e1e6ea",
".V c #e1e9f7",
"#y c #e2e7eb",
"#4 c #e3e2fb",
"#E c #e3e3f5",
"#j c #e3e7eb",
".6 c #e4e8ec",
".R c #e5e9ed",
".H c #e6eaee",
".x c #e6ebef",
"#P c #e7e6f9",
".n c #e7ecf0",
"Qt c #e8edf1",
".K c #eaf0f9",
"#D c #ededfd",
".N c #eff3fc",
".p c #f1f8ff",
".A c #f4f9ff",
"#C c #fbfbfe",
".q c #fefefe",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.a.b.c.d.e.f.g.h.i.j.k.l.m.n",
".o.p.q.r.s.t.q.q.q.q.q.u.v.w.x",
".y.z.A.B.C.D.q.q.q.q.q.E.F.G.H",
".I.J.K.L.M.N.q.q.q.q.q.O.P.Q.R",
".S.T.U.V.W.X.Y.Z.0.1.2.3.4.5.6",
".7.8.9#.###a#b#c#d#e#f#g#h#i#j",
"#k#l#m#n#o#p#q#r#s#t#u#v#w#x#y",
"#z#A#B.q.q#C#D#E#F#G#H#I#J#K#L",
"#M#N#O#P#Q#R#S#T#U#V#W#X#Y#Z#0",
"#1#2#3#4#5#6#7#8#9a.a#aaabacad",
"aeafagahaiajakalamanaoapaqaras",
"atauavawaxayazaAaBaCaDaEaFaGaH",
"aIaJaKaLaMaNaOaPaQaRaSaTaUaVaW",
"aXaYaZa0a1a2a3a4a5a6a6a7a8a9b.",
"b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#"
]

image3_data = [
"22 22 88 2",
"Qt c None",
".2 c #000000",
".S c #08ff08",
"#v c #100810",
".U c #101010",
"#c c #101018",
".M c #181018",
"#e c #181818",
".A c #181821",
".L c #211821",
"#l c #212121",
".z c #212129",
"#m c #292129",
"#u c #292929",
"#n c #292931",
".R c #29ff29",
"#o c #312931",
".T c #313131",
"#p c #313139",
".Z c #31ff31",
"#q c #393139",
"#t c #393939",
".y c #393942",
"#s c #423942",
".o c #424242",
"#h c #4a4a52",
".n c #5a525a",
"#r c #5a5a63",
".I c #5ace5a",
"#b c #6b636b",
".p c #6b6b6b",
".x c #6b6b73",
".Y c #6bff63",
".l c #736b73",
".t c #7b737b",
".s c #7b7384",
".0 c #7bff7b",
".r c #847b84",
".u c #847b8c",
"#g c #84848c",
".v c #8c7b94",
"#i c #8c848c",
".w c #8c8494",
"#j c #8c8c8c",
".8 c #8c8c94",
".m c #948c94",
"#k c #948c9c",
"#f c #949494",
".q c #94949c",
".J c #94c694",
"#d c #9c949c",
"#a c #9c94a5",
".k c #9c9c9c",
".N c #9c9ca5",
".H c #9ccea5",
".K c #a59ca5",
"#. c #a59cad",
".i c #a5a5a5",
".3 c #a5a5ad",
"## c #ad9cad",
".V c #ada5ad",
".d c #adadad",
".j c #adadb5",
".9 c #b5adb5",
".# c #b5b5b5",
".a c #bdbdbd",
".7 c #bdd6bd",
".c c #c6c6c6",
".5 c #cec6ce",
".b c #cecece",
".4 c #ceced6",
".F c #d6ced6",
".G c #d6cede",
".h c #d6d6d6",
".E c #d6d6de",
".Q c #d6ffd6",
".B c #ded6de",
".1 c #ded6e7",
".g c #dedede",
".D c #dedee7",
".6 c #e7dee7",
".f c #e7e7e7",
".C c #e7e7ef",
".X c #e7ffe7",
".O c #efe7ef",
".e c #efefef",
".W c #f7f7f7",
".P c #ffffff",
"QtQtQtQtQtQt.#.a.b.b.b.b.c.c.a.a.d.aQtQtQtQt",
"QtQtQtQtQtQt.a.e.f.f.f.f.f.e.e.e.g.aQtQtQtQt",
"QtQtQtQtQtQt.a.c.c.c.b.b.c.c.c.c.a.cQtQtQtQt",
"QtQtQtQtQtQt.#.a.a.a.a.#.a.a.#.#.d.aQtQtQtQt",
"QtQtQtQtQt.c.d.c.a.c.c.c.a.a.a.c.#QtQtQtQtQt",
"QtQtQtQtQt.a.a.#.a.a.a.a.a.a.c.c.#QtQtQtQtQt",
"QtQtQtQtQt.a.#.c.a.a.a.a.a.c.a.c.dQtQtQtQtQt",
"QtQtQtQtQt.c.a.a.a.a.a.a.a.a.a.a.#QtQtQtQtQt",
"QtQtQtQtQt.d.b.f.g.g.g.g.g.g.h.g.i.i.jQtQtQt",
"QtQtQt.a.k.l.#.h.b.h.b.h.b.h.g.g.m.n.o.p.#Qt",
"QtQt.a.q.r.s.t.t.t.t.t.t.t.u.v.w.x.y.z.A.o.i",
"Qt.a.k.B.C.D.B.E.E.E.E.F.G.H.I.J.K.o.L.L.M.y",
".a.N.O.P.P.P.P.P.P.P.P.P.Q.R.S.R.b.v.T.A.U.L",
".V.W.P.P.P.P.P.P.P.P.P.P.X.Y.Z.0.P.1.t.A.2.L",
".3.E.4.5.4.h.E.E.g.6.D.B.D.E.7.F.4.5.8.M.2.A",
".m.9.j.V.3#..3.K#.#..i#..K#.###a.q.8#b#c.2.L",
".m.j.j#..3.K.K.K.N.K.N.N.N.N#a#d#d.w#b#c.2#e",
"#f#.#..K.N.K.N.N.N#a.k#a#d#d#d#a.m#g#b.M.2#h",
".m.3.K.K#a.k#a#d#a.k#a#d#a#d.q.m.8#i.x#c#e.d",
"#f#g#i.w#j.w#i.8.w#i.8.8.m.8.m#k.8.w#b#e#fQt",
".#.l.z.A#l.z#m#m#m#n#o#o#p#p#q#q#p#o#p#fQtQt",
"QtQt.d#r#s#s#t#p.T.T.T#u#u.z#e#e#v.o.kQtQtQt"
]
file_small_image_data = [
"22 22 7 1",
". c None",
"# c #000000",
"b c #2e2e2e",
"c c #5c5c5c",
"d c #878787",
"e c #c2c2c2",
"a c #ffffff",
"......................",
"....##########........",
"....#aaaaaaa#b#.......",
"....#aaaaaaa#cb#......",
"....#aaaaaaa#dcb#.....",
"....#aaaaaaa#edcb#....",
"....#aaaaaaa#aedcb#...",
"....#aaaaaaa#######...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....#aaaaaaaaaaaaa#...",
"....###############...",
"......................",
"......................"
]
dir_small_image_data = [
"22 22 5 1",
". c None",
"# c #000000",
"c c #848200",
"a c #ffff00",
"b c #ffffff",
"......................",
"......................",
"......................",
"............####....#.",
"...........#....##.##.",
"..................###.",
".................####.",
".####...........#####.",
"#abab##########.......",
"#babababababab#.......",
"#ababababababa#.......",
"#babababababab#.......",
"#ababab###############",
"#babab##cccccccccccc##",
"#abab##cccccccccccc##.",
"#bab##cccccccccccc##..",
"#ab##cccccccccccc##...",
"#b##cccccccccccc##....",
"###cccccccccccc##.....",
"##cccccccccccc##......",
"###############.......",
"......................"
]

little_folder_open = [
"16 14 41 1",
"E c #605860",
"A c #686868",
"x c #686870",
"r c #808088",
"B c #888888",
"I c #a07008",
"j c #a07818",
"z c #a87810",
"m c #b08018",
"H c #b89828",
"y c #b8a058",
"a c #c09818",
"F c #c0c0a8",
"n c #c0c8b8",
"b c #c89028",
"t c #c89810",
"# c #c89830",
"e c #c8c0b8",
"J c #d0d0d0",
"g c #d8d0e0",
"L c #d8d8d8",
"K c #d8e0d8",
"l c #e0b048",
"p c #e0c078",
"c c #e0e0d8",
"h c #e8f8f8",
"C c #f0e078",
"u c #f0f088",
"M c #f0f0f0",
"d c #f0f0f8",
"v c #f8c860",
"G c #f8d068",
"s c #f8d070",
"o c #f8d878",
"D c #f8e078",
"q c #f8e080",
"k c #f8e880",
"i c #f8f088",
"w c #f8f090",
"f c #f8f898",
". c #f8f8f0",
"..#a#bcd........",
".a....aed.......",
"a.ffff.aaaaaagh.",
"afiiiii.....ajed",
"aklaaaaaaaaaaamn",
"aoap........q.jr",
"astuffffffffvwjx",
"alafwwwwwwwwlyzA",
"aalfkkkkkkkkltAB",
"aaCfDDDDDDDDljEF",
"aafGGGGGGGGGHIAJ",
"gIIIIIIIIIIIIABK",
"derxxxxxxxxxxBed",
".dKJJJJJJJJJJLM."
]
  
little_folder_closed =[
"16 14 42 1",
"J c #404848",
"x c #686868",
"K c #808080",
"o c #888888",
"A c #986800",
"w c #a06808",
"t c #a07008",
"n c #a07818",
"I c #a86810",
"H c #a87810",
"k c #b07818",
"j c #b08018",
"i c #b88020",
"h c #b88820",
"r c #c08828",
"b c #c09028",
"a c #c89028",
"# c #c89830",
"e c #c8c8c8",
"M c #d0d0d0",
"G c #d8a838",
"E c #d8a840",
"c c #d8d0e0",
"L c #d8d8d8",
"C c #e0b048",
"p c #e0d8d8",
"d c #e8f8f8",
"y c #f0b858",
"N c #f0f0f0",
"f c #f0f0f8",
"v c #f8c860",
"F c #f8d068",
"u c #f8d070",
"s c #f8d878",
"D c #f8e078",
"q c #f8e080",
"B c #f8e880",
"m c #f8f088",
"l c #f8f090",
"z c #f8f890",
"g c #f8f898",
". c #f8f8f0",
"..##abcd........",
".#....bef.......",
"#.gggg.hijjjkcd.",
"#lmmmml.....nop.",
"amqbbbbbbrhijjjc",
"bsb.........q.to",
"bu#gggggggggvgwx",
"rv#gllllllllyzAx",
"rvbgBBBBBBBBCgAx",
"hvhgDDDDDDDDEgAx",
"ivigFFFFFFFFGgAx",
"cjjkHHIttwAAAAJK",
"deKxxxxxxxxxxxKe",
".fLMMMMMMMMMMMLN"
]
hourglass = \
    "\x89\x50\x4e\x47\x0d\x0a\x1a\x0a\x00\x00\x00\x0d" \
    "\x49\x48\x44\x52\x00\x00\x00\x0d\x00\x00\x00\x16" \
    "\x08\x06\x00\x00\x00\x1b\xfa\x16\x24\x00\x00\x00" \
    "\x8f\x49\x44\x41\x54\x38\x8d\xbd\x93\xc1\x0e\xc3" \
    "\x30\x08\x43\xed\x6a\xff\xff\xcb\xde\xa1\x25\x02" \
    "\xe2\xb4\x4b\x0f\xe3\x42\x14\x78\x31\x44\x40\x00" \
    "\xc2\xa6\x7d\xe2\x20\x3d\xb3\x24\x4f\xff\x46\x89" \
    "\x92\x40\x52\xbf\x2a\x49\xe2\xb1\xab\x02\x00\x13" \
    "\x34\xea\x6e\xfe\x16\xba\xca\x2d\x7e\x09\xe5\x17" \
    "\x1d\x90\xe3\x8c\x00\x49\x05\xb0\x2a\x59\x12\x8b" \
    "\x52\x5c\xac\x7a\x8a\x78\x51\x4a\xaf\x0e\x45\x07" \
    "\x14\xa5\x1d\x2b\x50\xef\xab\xf7\x3b\x41\x1d\x48" \
    "\xa5\x4d\xe0\x18\xa3\x9c\xe0\x2c\xf7\x97\x7f\xcf" \
    "\x26\xb9\xb8\xfd\x88\x3c\x11\xce\xec\xec\xf5\x51" \
    "\xba\x85\x1c\xe0\xc0\x57\x4b\xf8\xbf\x75\xff\x02" \
    "\x60\x02\x6f\x2c\xe2\xb9\xaa\xd3\x00\x00\x00\x00" \
    "\x49\x45\x4e\x44\xae\x42\x60\x82"

tick = [
"14 15 4 1",
"b c #080808",
"a c #5e5e5e",
"# c #ababab",
". c #e6e6e6",
".........#aa#.",
".........bbb#.",
"........bbb#..",
".......#bba...",
".......bbb....",
"......abb#....",
"......bba.....",
".....abb......",
"#ab#.bba......",
"abbbabb.......",
".bbbbba.......",
".#bbbb#.......",
"..abbb........",
"...ab#........",
".............."
]

circle = [
"13 13 18 1",
"f c #050607",
"i c #0c0d0e",
"k c #0e0f10",
"e c #0f1011",
"h c #141516",
"m c #171819",
"b c #1c1d1d",
"c c #2d2e2f",
"a c #3e3e3f",
"d c #434445",
"g c #555657",
"n c #747475",
"# c #9a9b9b",
"j c #a5a6a6",
"l c #a9a9a9",
"p c #cfcfd0",
"o c #f7f7f7",
". c #e6e6e6",
"....#abc#....",
"..defagafhd..",
".gib.....big.",
".ih.......hi.",
"ji.........kl",
"af.........fa",
"bf.........fm",
"cf.........fc",
"ni.........in",
"oid.......dko",
".bin.....nih.",
"..ekc...cke..",
"...pbhhhbp..."
]
