#!/bin/sh

#This is a simple test to verify glite-brokerinfo is correctly linked
#plus a segfault bug https://savannah.cern.ch/bugs/index.php?48048

function usage() {
echo "Usage: $0"
}

if [ $# -gt 0 ]; then
  usage
  exit 1
fi

failed=0

if [ "x$GLITE_LOCATION" == "x" ]; then
  echo "GLITE_LOCATION is not set"
  exit 1
fi

$GLITE_LOCATION/bin/glite-brokerinfo --help
ret=$?
if [ $ret -ne 0 ]; then
  echo "glite-brokerinfo --help failed"
  failed=1
fi

$GLITE_LOCATION/bin/glite-brokerinfo -f xxx
ret=$?
if [ $ret -ne 0 ]; then
  echo "glite-brokerinfo -f xxx failed"
  failed=1
fi

if [ $failed -ne 0 ]; then
  echo "Test Failed"
else
  echo "Test Passed"
fi

exit 0

