#!/bin/bash

siteName=$1
nodeName=$2
inMaintenance=$3
envName=`cat $SAME_SENSOR_WORK/envName`

if [ "x$1" == "x--publish" ] ; then
    shift    
    echo "$nodeName: published" >&2
else
    echo "$nodeName: started" >&2
    mkdir -p $SAME_SENSOR_WORK/nodes/$nodeName
    cd $SAME_SENSOR_WORK/nodes/$nodeName
    rm -f *.result
    for test in `cat $SAME_SENSOR_HOME/test-sequence.lst` ; do
	same-run-test -v $SAME_VO -t $test -n $nodeName -e $envName -d $SAME_SENSOR_HOME/tests $nodeName > $test.result
    done
    echo "$nodeName: publishing" >&2
    same-publish-tuples TestData *.result >&2
    echo "$nodeName: finished" >&2
fi
