#!/bin/sh
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Gianni Pucciani, CERN
#
##############################################################################

showUsage ()
{
 echo "                                           "
 echo "Usage:  SRM-certtest.sh                   "
 echo "                                           "
}

exitFailure ()
{
echo "------------------------------------------------"
echo "END `date`"
echo "-TEST FAILED-"
exit -1
}

#######################
#Parsing the arguments#
#######################
if [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "--help" ] || [ $# -gt 0 ]; then
  showUsage
  exit 2
fi


###################################
# Check for environment variables #
###################################
  
if [ -e "SRM-certconfig" ]; then
  source ./SRM-certconfig
else
  echo "The file ./SRM-certconfig must be sourced in order to run the tests"
  exit Failure
fi  

if [ -z "$SRM_HOST" ]; then
  echo "You need to set SRM_HOST in SRM-certconfig in order to run the tests"
  exitFailure
else
  hostname=$SRM_HOST
fi

if [ -z "$VO" ]; then
  echo "You need to set VO in SRM-certconfig in order to run the tests"
  exitFailure
fi

if [ -z "$S2_TESTS_LOCATION" ]; then
  echo "You need to set S2_TESTS_LOCATION in SRM-certconfig in order to run the tests"
  exitFailure
else
  export S2_TESTS_LOCATION="$S2_TESTS_LOCATION"
fi

if [ -z "$LOGS_DIR" ]; then
  echo "You need to set LOGS_DIR in SRM-certconfig in order to run the tests"
  exitFailure
fi



#########
# START #
#########

echo "START `date` "
echo "------------------------------------------------"

####################################
# Checking if there is valid proxy #
####################################

ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`

ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
  #nop
  :
else
  echo "Valid proxy is needed for this test!"
  if [ $ProxyExpired -gt 0 ]; then
    echo "Proxy credential expired!"
  fi
  exitFailure
fi

####################################
# Create a directory for log files #
####################################

if [ -z "$LOGS_DIR" ];then
  cp=`pwd`
  id=`date +%y%m%d%H%M%S`
  loglocation=$cp/logs_$id
  mkdir -p $loglocation
else
  loglocation=$LOGS_DIR/logs_$id
  mkdir -p $loglocation
fi

if [ ! -d $loglocation ];then
  echo   "Error while creating log directory $loglocation"
  exitFailure
else
  echo "Log files will be stored in $loglocation"
fi


########################
# Launch S2 tests      #
########################
if [ "$S2" = "yes" ]; then
  echo "*Running S2 test set*"

  declare -a tests_failed
  failed=no

  testdir=./tests
  tests_list=(SRM-s2-srmv2.2-MoU)

  pushd $testdir >> /dev/null

  touch testfile 2> /dev/null
  if [ $? -ne 0 ]; then
    echo "SRM test directory is not writable, if you are on AFS be sure to have a valid token"
    exitFailure
  fi

  for item in ${tests_list[*]}
  do
    rm -rf ${item}_result.txt testfile
    echo "Executing $item"
    ./$item $hostname > ${item}_result.txt 2>&1 &
  
    # show a rotating dash while command is executing
    while ps |grep $! &>/dev/null; do
      echo -en "\b-"
      sleep 1
      echo -en "\b\\"
      sleep 1
      echo -en "\b|"
      sleep 1
      echo -en "\b/"
      sleep 1
    done
  
    res=$?
    grep '\-TEST FAILED\-' ${item}_result.txt >> /dev/null
    if [ "$?" = 0 -o "$res" != 0 ]; then
      echo "$item FAILED"
      failed=yes
      tests_failed=( "${tests_failed[@]}" "$item" )
    else 
      echo "$item PASSED"
    fi
  done
  popd >> /dev/null
else
  echo "*S2 tests skipped"
fi


echo "------------------------------------------------"
echo "END `date`"


#############
# SAME tests #
#############
if [ "$SAME" = "yes" ]; then
  echo "*Running SAME test set*"

  pushd ./tests/SAME/tests >> /dev/null
  touch testfile 2> /dev/null
  if [ $? -ne 0 ]; then
    echo "SAME tests direcotry is not writable, if you are on AFS be sure to have a valid token"
    exitFailure
  fi
  tests_list=( SRMv2-get-SURLs SRMv2-ls-dir SRMv2-put SRMv2-ls SRMv2-gt SRMv2-get SRMv2-del )

  for item in ${tests_list[*]}
  do
    rm -rf ${item}_result.txt testfile
    echo "Executing $item"
    ./$item $SRM_HOST > $loglocation/${item}_result.txt 2>&1
    res=$?
    grep '\-TEST FAILED\-' $loglocation/${item}_result.txt >> /dev/null
    if [ "$?" = 0 -o "$res" != 0 ]; then
      echo "$item FAILED"
      failed=yes
      tests_failed=( "${tests_failed[@]}" "$item" )
    else
      echo "$item PASSED"
    fi
  done
  popd >> /dev/null
else
  echo "*SAME tests skipped"
fi


#########################
# Analyse tests outcome #
#########################

if [ "x$failed" = "xyes" ]; then

  echo "TEST_FAILED"
  echo "The following tests failed:"
  for item in ${tests_failed[*]}
  do
    echo "$item: results in tests/${item}_result.txt"
  done
else 
    echo "TEST_PASSED"
fi



