#!/bin/bash
. $SAME_HOME/sensors/functions.sh
nodeName=$1
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
echo "<pre>"
export LFC_HOST=$nodeName
mydir="lfcmkdir$$"
echo "Doing an lfc-ping on  LFC node $nodeName:"
clear=`lfc-ping -h $nodeName`
RETVAL=$?
echo "$clear"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    echo "Test is "; samPrintOK;
    exit $SAME_OK
else
    echo "Test failed!"; samPrintFAILED;
    exit $SAME_ERROR
fi
