#!/bin/bash
#****** LFC/LFC-ls
# NAME
# LFC-ls - Does an lfc-ls command. This sensors returns OK if: 
# * The lfc-mkdir returns successfuly.
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2007-02-06
#
# LANGUAGE
#
# bash
#
# SOURCE

nodeName=$1
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
echo "Doing an lfc-ls on /grid/$SAME_VO for LFC node $nodeName:"
echo "<pre>"
export LFC_HOST=$nodeName
listing=`lfc-ls /grid/$SAME_VO 2>&1`
RETVAL=$?
echo "$listing"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    exit $SAME_OK
elif ( echo "${listing}" | egrep -q ' No such file' > /dev/null ); then
    echo "summary: VO Not Supported : $SAME_VO"
    touch $SAME_WORK/LFC/no_vodir.$nodeName
    exit $SAME_INFO
else
    exit $SAME_ERROR
fi

#****