#!/bin/bash
. $SAME_HOME/sensors/functions.sh
nodeName=$1
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
echo "<pre>"
export LFC_HOST=$nodeName
mydir="lfcmkdir$RANDOM"
mydir2="lfcmkdir$RANDOM"
echo "Creating a link /grid/$SAME_VO/$mydir2 to /grid/$SAME_VO/$mydir"
cmd1=`lfc-mkdir /grid/$SAME_VO/$mydir`
clear=`lfc-ln -s /grid/$SAME_VO/$mydir /grid/$SAME_VO/$mydir2`
RETVAL=$?
cmd1=`lfc-rm -r /grid/$SAME_VO/$mydir2 2>/dev/null`
cmd1=`lfc-rm -r /grid/$SAME_VO/$mydir 2>/dev/null`
echo "$clear"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    echo "Test is "; samPrintOK;
    exit $SAME_OK
else
    echo "Test failed!"; samPrintFAILED;
    exit $SAME_ERROR
fi
