#!/bin/bash
#****** LFC/LFC-writefile
# NAME
# LFC-writefile - Checks that we can create a file in the LFC for this VO. This sensors returns OK if: 
# * The lfc-mkdir returns successfuly.
# In addition the test prepares /grid/<VO>/SAM directory for use by other sensors (CE, SE, SRM)
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2007-02-06
#
# LANGUAGE
#
# bash
#
# SOURCE

nodeName=$1
if [ -f $SAME_WORK/LFC/no_vodir.$nodeName ]; then
    echo "summary: VO Not Supported : $SAME_VO"
    exit $SAME_INFO
fi
export LFC_HOST=$nodeName
export LFC_HOME=/grid/$SAME_VO/SAM
echo "Make sure that LFC_HOME=$LFC_HOME directory exists on LFC node $nodeName"
echo "<pre>"
set -x
lfc-mkdir -p $LFC_HOME
set +x
echo "</pre>"
filename=$LFC_HOME/sft-sensor-$nodeName
lfc-rm -rf $filename 2>&1 >/dev/null
echo "Creating file on LFC node $nodeName: $filename"
echo "<pre>"
set -x
lfc-mkdir $filename
set +x
RETVAL=$?
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    lfc-rm -rf $filename 2>&1 >/dev/null
    echo "summary: $filename"
    exit $SAME_OK
else
    exit $SAME_ERROR
fi

#****