#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Rename  LFC subdirectories for VO                                #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################

echo "<pre>"
export LFC_HOST=$1
echo  $LFC_HOST

function clear (){
   lfc-rm -r -f $1

}

source $SAME_SENSOR_HOME/tests/config_file
echo $SAME_OK
echo $SAME_VO

rm -rf $lfc_tmp
rm -rf $lfc_stderr

date
echo "<br>"
echo "Test LFC CLI rename diectory. lfc-rename <olddirname> <newdirname"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "<br>"


main_dir="/grid/$vo_name/$LFC_HOST/renamedir"

echo "Scenario: Direcrory exists"
echo "1. Create main directory: $main_dir"
echo "<br>"
lfc-mkdir -p $main_dir


rdname="rdonly"
rdon="$main_dir/$rdname"
newDn="newDname"
newDname="$main_dir/$newDn"

echo "2. Rename 'read only' directory"
lfc-mkdir -m 400 $rdon
lfc-rename $rdon $newDname 2> $lfc_stderr
#cat $lfc_stderr
grep "Permission denied" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Non correct lfc-rm result"
   echo "Test is failed"
   lfc-chmod 777 $rdon
   clear $main_dir
   exit $SAME_ERROR
fi
echo "OK"

echo
echo "2. Rename ordinary directory"
lfc-chmod 777 $rdon
lfc-rename $rdon $newDname
lfc-ls $main_dir > $lfc_tmp

grep $newDn $lfc_tmp  > /dev/null

if [ $? == 1 ]; then 
   echo "Non correct lfc-rename result"
   echo "Test is failed"
   clear $main_dir
   exit $SAME_ERROR
fi

clear $newDname
echo "OK"

echo "2. SCENARIO: Rename nonexisting directory: $main_dir"
echo "<br>"

lfc-rename $rdon $newDname   2> $lfc_stderr
#cat $lfc_stderr
grep "No such file or directory" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Noncorrect diagnose, exit"
   cat $lfc_stderr
   echo "Test is failed"
   clear $main_dir
   exit $SAME_ERROR
fi

echo "OK"

echo
echo "Cleaning tasks"
echo "<br>"
clear $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
