#!/bin/bash

nodeName=$1
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
echo "<pre>"
export LFC_HOST=$nodeName
mydir="lfcmkdir$$"
echo "Doing an lfc-rmdir on /grid/$SAME_VO/$mydir for LFC node $nodeName:"
clear=`lfc-rm -r /grid/$SAME_VO/$mydir 2>&1`
mkdir=`lfc-mkdir /grid/$SAME_VO/$mydir 2>&1`
clear=`lfc-rm -r /grid/$SAME_VO/$mydir 2>&1`
RETVAL=$?
echo "$clear"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    echo "Test is "; echo "<font color="green"> - OK </font>";
    exit $SAME_OK
elif ( echo "${mkdir}" | egrep -q ' No such file' > /dev/null ); then
    echo "summary: VO Not Supported : $SAME_VO"
    touch $SAME_WORK/LFC/no_vodir.$nodeName
    echo "Test is "; echo -n "<font color="blue"> INFO: </font>:";
    exit $SAME_INFO
else
    echo "Test failed!"; echo "<font color="red"> - FAILED </font>";
    exit $SAME_ERROR
fi
