#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete  LFC subdirectories for VO                                #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################

export LFC_HOST=$1
#echo  $LFC_HOST

function clear (){
   $LCG_LOCATION/bin/lfc-rm -r -f $1

}


rm -rf $lfc_tmp
rm -rf $lfc_stderr

date

echo "Test LFC CLI remove diectory. lfc-rm -r <dirname>"


main_dir="$LFCDIR/rmdir"

echo "Scenario: Direcrory exists"
echo "1. Create main directory: $main_dir"
#echo "<br>"
$LCG_LOCATION/bin/lfc-mkdir -p $main_dir

rdon="$main_dir/rdonly"
echo "2. Remove 'read only' directory"
echo "2.1. Create "read only" directory"
$LCG_LOCATION/bin/lfc-mkdir -m 400 $rdon
$LCG_LOCATION/bin/lfc-rm -f -r $rdon 2> $lfc_stderr
#cat $lfc_stderr
grep "Permission denied" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Non correct lfc-rm result"
   echo "Test is failed"
   $LCG_LOCATION/bin/lfc-chmod 777 $rdon
   clear $main_dir
   exit $STATE_CRITICAL
fi
$LCG_LOCATION/bin/lfc-chmod 777 $rdon
clear $rdon
$LCG_LOCATION/bin/lfc-ls $D_LFC
echo "OK"

echo
echo "3.  Create $DMAX subdirectories"
#echo "<br>"
counter=0
dir=$main_dir
pdir=$main_dir

while [ $counter -lt $DMAX ]; do
  subdir="subdir-$counter"
  dir=$dir/$subdir
  #echo "new dir:$dir"
  $LCG_LOCATION/bin/lfc-mkdir $dir
  $LCG_LOCATION/bin/lfc-ls $pdir > $lfc_tmp
  
  grep $subdir $lfc_tmp # > /dev/null
  
  if [ $? == 1 ]; then 
    echo "Test is failed"
    clear $main_dir
    exit $STATE_CRITICAL
  fi
  
  pdir=$dir
  let counter=counter+1
done

echo "4. Remove all subdirectories, use -R option"
#$LCG_LOCATION/bin/lfc-ls $D_LFC
$LCG_LOCATION/bin/lfc-rm -R  -f $main_dir  

echo "5. Check deletion result"
#$LCG_LOCATION/bin/lfc-ls $D_LFC
#$LCG_LOCATION/bin/lfc-ls $main_dir

$LCG_LOCATION/bin/lfc-ls $main_dir 2> $lfc_stderr

grep "No such file or directory" $lfc_stderr  > /dev/null
 
if [ $? == 1 ]; then 
    echo "Test is failed"
    clear $main_dir
    exit $STATE_CRITICAL
fi 
echo "OK"

echo "2. SCENARIO: Delete nonexisting directory: $main_dir"
#echo "<br>"

#$LCG_LOCATION/bin/lfc-ls $D_LFC
#$LCG_LOCATION/bin/lfc-ls $main_dir
$LCG_LOCATION/bin/lfc-rm -r $main_dir  2> $lfc_stderr

grep "No such file or directory" $lfc_stderr  > /dev/null

if [ $? != 0 ]; then 
   echo "Noncorrect diagnose, exit"
   cat $lfc_stderr
   echo "Test is failed"
   clear $main_dir
   exit $STATE_CRITICAL
fi

echo "OK"

echo
echo "Cleaning tasks"
#echo "<br>"
clear $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
exit $STATE_OK
