#!/bin/bash
. $SAME_HOME/sensors/functions.sh
nodeName=$1
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
echo "<pre>"
export LFC_HOST=$nodeName
mydir="lfcmkdir$$"
echo "Doing an lfc-mkdir on /grid/$SAME_VO/$mydir for LFC node $nodeName:"
clear=`lfc-rm -r /grid/$SAME_VO/$mydir 2>&1`
mkdir=`lfc-mkdir /grid/$SAME_VO/$mydir 2>&1`
RETVAL=$?
clear=`lfc-rm -r /grid/$SAME_VO/$mydir 2>&1`
echo "$mkdir"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    echo "Test is "; samPrintOK;
    exit $SAME_OK
elif ( echo "${mkdir}" | egrep -q ' No such file' > /dev/null ); then
    echo "summary: VO Not Supported : $SAME_VO"
    touch $SAME_WORK/LFC/no_vodir.$nodeName
    echo "Test is "; samPrintINFO;
    exit $SAME_INFO
else
    echo "Test failed!"; samPrintFAILED;
    exit $SAME_ERROR
fi
