#!/bin/bash

nodeName=$1
export LFC_HOST=$nodeName
rm -f $SAME_WORK/LFC/no_vodir.$nodeName
RETVAL=0;
echo "<pre>"
bulktest=$SAME_HOME/sensors/LFC/tests/bulk-methods/LFC_DELETE_TEST


for testtype in 1 2 3 ; do

# Setting up a unique target environment
echo "<br><br>"
echo "### Preparing the test #$testtype #########################"
unique=$RANDOM
mylfcdir=/grid/dteam/generated/lfc_bulk_del_$unique
mysrmdir=lxb1921.cern.ch/dpm/cern.ch/home/dteam/generated/lfc_bulk_del_$unique

echo "<br><br>Cleaning possibly existing directories"
lfc-rm -r $mylfcdir
lfc-mkdir -p $mylfcdir
loop="100 101 102"

echo "<br><br>### Creating files for the tests <br><br>"

for i in $loop ; do
echo lcg-cr -v --vo $SAME_VO -d srm://$mysrmdir/bulk_test_$i -l lfn://$mylfcdir/bulk_test_$i file:///etc/hosts
lcg-cr -v --vo $SAME_VO -d srm://$mysrmdir/bulk_test_$i -l lfn://$mylfcdir/bulk_test_$i file:///etc/hosts
done

echo "<br><br>### Launching the test $testtype<br><br>"
echo $bulktest $mylfcdir srm://$mysrmdir 100 103 $LFC_HOST $testtype
$bulktest $mylfcdir srm://$mysrmdir 100 103 $LFC_HOST $testtype

if [ $? -ne 0 ]; then RETVAL=1;fi
done

echo "<br><br>### Cleaning the mess"
#todel=`echo $mysrmdir | cut -d / -f 2-`
#dpns-rm -r /$todel
#lfc-rm -r $mylfcdir


echo "<br><br>"
echo "</pre>"
if [ $RETVAL -eq 0 ] ; then
    echo "Test is "; echo "<font color="green"> - OK </font>";
    exit $SAME_OK
else
    echo "Test failed!"; echo "<font color="red"> - FAILED </font>";
    exit $SAME_ERROR
fi
