#!/usr/bin/env python
# test has been developed by Robert Harakaly and changed for SAM (and Nagios) by Victor Galaktionov
# create  a  new LFC directory in the name server with the specified GUID (lfc_mkdirg) 

import os,lfc, sys, commands
from testClass import _test 
global lfc_vo

class test_create_dir_ok(_test):
    def info(self):
        return "Directory creation"
    def test(self):
        self.name = lfc_vo + "/python_mkdir_test"
        self.guid = commands.getoutput('uuidgen').split('/n')[0]
        ret = lfc.lfc_mkdirg(self.name, self.guid, 0755)
        statg=lfc.lfc_filestatg()
        lfc.lfc_statg("",self.guid, statg)
        return (statg,ret)
    def ret(self):
        statg=lfc.lfc_filestatg()
        statg.guid = self.guid
        return statg
    def compare(self,testVal, retVal):
        (ret, retRetVal) = retVal
        (test, testRetVal) = testVal
        retval = True
        if (retRetVal != testRetVal):
            retval = False
        retval = retval & (ret.guid == test.guid)
        return retval
    def clean(self):
        lfc.lfc_rmdir(self.name)



class test_create_dir_pd(_test):
    def __init__(self):
        self.retVal=-1
    def info(self):
        return "Directory creation (permission denied)"
    def test(self):
        self.name = "/python_mkdir_test"
        self.guid = commands.getoutput('uuidgen').split('/n')[0]
        ret = lfc.lfc_mkdirg(self.name, self.guid, 0755)
        statg=lfc.lfc_filestatg()
        lfc.lfc_statg("",self.guid, statg)
        return (statg,ret)
    def ret(self):
        statg=lfc.lfc_filestatg()
        statg.guid = ""
        return statg
    def clean(self):
        lfc.lfc_rmdir(self.name)
    def compare(self,testVal, retVal):
        (ret, retRetVal) = retVal
        (test, testRetVal) = testVal
        retval = True
        if (retRetVal != testRetVal):
            retval = False
        retval = retval & (ret.guid == test.guid)
        return retval

class lfc_mkdirg_test:
    def __init__(self):
        self.name = "lfc_mkdirg_test"
        self.tests=[test_create_dir_ok, test_create_dir_pd]

    def run(self):
        retVal = True
        for testclass in self.tests:
            testInstance = testclass()
            testInstance.prepare()
            ret1 = testInstance.compare(testInstance.test(), (testInstance.ret(), testInstance.getRetVal()))
            testInstance.clean()
            retVal = retVal & ret1
            if ret1:
                print "%-60s[OK]" % testInstance.info()
            else:
                print "%-60s[FAILED]" % testInstance.info()
        return retVal

#************* Interface for SAM and Python tests ***************
print "<pre>"
print "Start test:  create  a  new LFC directory in the name server with the specified GUID (lfc_mkdirg)"
print "1. Prepare environment"

vo_name=os.environ['VO']
lfc_host = sys.argv[1]
lfc_home = lfc_host + ":/grid/" + vo_name

os.environ['LFC_HOME'] = lfc_home
os.environ['LFC_HOST'] = lfc_host

same_ok   = int(os.environ['STATE_OK'])
same_err  = int(os.environ['STATE_CRITICAL'])
lfc_vo    = "/grid/" + vo_name

print "2. Start test run()"
ret = lfc_mkdirg_test().run()

print "3. Ret test code: %s" % ret
print "Exit"
print "</pre>"

if ( ret == True ):
    print "Test is OK"
    sys.exit(same_ok)
else:
    print "Test is failure"
    sys.exit(same_err)
                        