#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Rename  LFC files  for VO                                        #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################

echo "<pre>"
export LFC_HOST=$1
echo  $LFC_HOST
GUID=""

function delGuid () {
    echo "Delete $GUID"
    $LCG_LOCATION/bin/lcg-del -a $GUID
}
function delLFN () {
    echo "Delete $1"
    $LCG_LOCATION/bin/lcg-del -a $1
}

           
function clear (){
    $LCG_LOCATION/bin/lfc-rm -r -f $1

}

#source $SAME_SENSOR_HOME/tests/config_file

vo_name=$VO
rm -rf $lfc_tmp
rm -rf $lfc_stderr

date
echo "<br>"
echo "Test LFC CLI rename file. lfc-rename <oldfilename> <newfilename>"
echo "<br>"
echo "VO=$vo_name"
echo "FILE=$FILE"
echo "SE=$SE"
echo "LCG_GFAL_INFOSYS=$LCG_GFAL_INFOSYS"
echo "<br>"
echo "<br>"


main_dir="$LFCDIR/renamefile"

echo "Scenario: Direcrory exists"
echo "1. Create main directory: $main_dir"
echo "<br>"
 $LCG_LOCATION/bin/lfc-mkdir -p $main_dir

echo "SCENARIO: Directory and file doesn't exist"
echo "<br>"


echo "<br>"
echo "Strong check if directory nonexists"
echo "List of nonexist directory"
$LCG_LOCATION/bin/lfc-ls -l $main_dir
clear $main_dir
echo "OK"

echo
echo "2. Rename ordinary file"

echo "2.1. Create main directory: $main_dir"
 $LCG_LOCATION/bin/lfc-mkdir -p $main_dir
fname="test_file"
LFN="$main_dir/$fname"
echo "SE=$SE, LFN=$LFN, file=$FILE"

echo "2.2. Create guid and lfn:$LFN"
echo "2.2.1. Prelimenary delete file $LFN"
delLFN "lfn:"$LFN

echo "CLI: $LCG_LOCATION/bin/lcg-cr -l $LFN -d $SE --vo $vo_name file:$FILE"
fguid=`$LCG_LOCATION/bin/lcg-cr -l $LFN -d $SE --vo $vo_name file:$FILE`
GUID=$fguid
echo $fguid
echo $fguid > $lfc_tmp

grep "guid:" $lfc_tmp > /dev/null
if [ $? == 1 ]; then
    echo "Noncorrect create GUID, exit"
    cat $lfc_tmp
    echo "Test is failed"
    delLFN "lfn:"$LFN
    clear $main_dir
    exit $SAME_ERROR
fi
echo "OK"

echo "Rename created LFN"
Fname="newFileName"
newFname="$main_dir/$Fname"
echo "File list before:"
$LCG_LOCATION/bin/lfc-ls $main_dir
echo "File list after:"

 $LCG_LOCATION/bin/lfc-rename $LFN  $newFname
 $LCG_LOCATION/bin/lfc-ls $main_dir > $lfc_tmp
cat $lfc_tmp

grep $Fname $lfc_tmp  > /dev/null
if [ $? == 1 ]; then 
   echo "Non correct lfc-rename result"
   echo "Test is failed"
   delGuid
   clear $main_dir
   exit $SAME_ERROR
fi
echo "OK"

echo "3. Rename 'read only' parent directory"
echo "MAN: This requires write permission in the parent directories."

echo "3.1. Change access to '400' of parent directory anf file"
 $LCG_LOCATION/bin/lfc-chmod 400 $main_dir
 $LCG_LOCATION/bin/lfc-chmod 400 $newFname
echo "3.2. Try rename"
 $LCG_LOCATION/bin/lfc-rename $newFname "$newFname-qwerty" 2> $lfc_stderr
 $LCG_LOCATION/bin/lfc-ls -l $main_dir
echo "Result renaming:"
cat $lfc_stderr
 $LCG_LOCATION/bin/lfc-chmod 777 $main_dir     # Restore access 

grep "Permission denied" $lfc_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Non correct lfc-rm result"
    echo "Test is failed"
     $LCG_LOCATION/bin/lfc-chmod 777 $newFname
     $LCG_LOCATION/bin/lfc-chmod 777 $newFname-qwerty
    delGuid
    clear $main_dir
    exit $SAME_ERROR
fi
echo "OK"

echo "3. Rename by using LFC_HOME"

export LFC_HOME=$main_dir
echo "List before rename:"
 $LCG_LOCATION/bin/lfc-ls $main_dir

 $LCG_LOCATION/bin/lfc-rename $Fname $fname
 $LCG_LOCATION/bin/lfc-ls $main_dir > $lfc_tmp
echo "List after rename:"
cat $lfc_tmp 
grep $fname $lfc_tmp  > /dev/null

if [ $? == 1 ]; then 
   echo "Non correct lfc-rename result"
   echo "Test is failed"
   delGuid
   clear $main_dir
   exit $SAME_ERROR
fi
echo "OK"

echo "4. SCENARIO: Rename nonexisting file"
echo "<br>"

 $LCG_LOCATION/bin/lfc-rename "$main_dir/nonexist" "$main_dir/new"   2> $lfc_stderr
echo "Result nonexisting file rename:"
cat $lfc_stderr
grep "No such file or directory" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Noncorrect diagnose, exit"
   cat $lfc_stderr
   echo "Test is failed"
   del_guid
   clear $main_dir
   exit $SAME_ERROR
fi
echo "OK"

echo
echo "Cleaning tasks"

echo "<br>"
delGuid
clear $main_dir
 $LCG_LOCATION/bin/lfc-ls $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
