#!/bin/bash
#Author Liudmila Stepanova < sli@inr.ru >
MYPROXY_SERVER=$1
if [ "$MYPROXY_SERVER" == "" ]
then 
  echo "******** MYPROXY_SERVER is not defined *********"
  exit 1
fi 
verifyproxy() {
timeleft=`grid-proxy-info -file $1 -timeleft`
#echo TIMELEFT=$timeleft
if [ "$timeleft" == "" ]
then
  echo 
  echo "***** failed to verify proxy; 'grid-proxy-info -timeleft' failed *****"
  echo
fi
if [ "$timeleft" -lt 1 ]
then
   echo
   echo "***** proxy is expired *****"
   echo
   exit 1
fi
  proxytype=`grid-proxy-info -file $1 -type`  
#echo  PROXYTYPE=$proxytype
  proxytype=`echo $proxytype | awk '{ print $2 }'`
  if [ "$proxytype" == "legacy" ]
then 
   typeopt="-old"
else
   typeopt="-rfc"
fi
output=`grid-proxy-init $typeopt -debug -verify -cert $1 -key $1 -valid 0:1 -out /tmp/tmpproxy.$$ 2>&1`
if [ "$?" -ne 0 ]
then
   echo
   echo "****** failed to verify proxy ******"
   echo $output
   echo
if [ -e "/tmp/tmpproxy.$$" ]
then
   rm -f "/tmp/tmpproxy.$$" 
fi
   exit 1
fi
}

. setup_env
cert_subject=`grid-proxy-info -subject`
cert_subject=${cert_subject%/CN=proxy}
cert_subject=${cert_subject%/CN=limited proxy}
cert_subject=${cert_subject%/CN=[0-9]*}
echo $cert_sub
ERR=0
passphrase=`date +%s`
passphrase=$RANDOM
let passphrase=passphrase+1000001
echo $passphrase | myproxy-init -v -a -c 1 -t 1 -S 
if [ "$?" -ne 0 ]
then
   echo
   echo FAILED
   echo "***** myproxy-init is failed *****"
   echo
   exit 1
fi
  echo 
  echo SUCCEEDED
  echo "***** myproxy-init is succeeded *****"
  echo
myproxy-info -v
echo X509_USER_PROXY $X509_USER_PROXY
echo $passphrase | myproxy-logon -t 1 -o /tmp/myproxy-test.$$ -v -S 
if [ "$?" -ne 0 ]
then 
   echo
   echo FAILED
   echo "***** myproxy-logon is failed *****"
   echo
   exit 1
fi
   echo
   echo SUCCEEDED
   echo "***** myproxy-logon  is succeeded *****"
   echo
#grid-proxy-info -file /tmp/myproxy-test.$$
verifyproxy /tmp/myproxy-test.$$
old_passphrase=$passphrase
passphrase=`date +%s`
passphrase=$RANDOM
let passphrase=passphrase+1000001
( echo $old_passphrase ; echo $passphrase ) | myproxy-change-pass-phrase -v -S
if [ "$?" -ne 0 ]
then
   echo
   echo FAILED
   echo "***** myproxy-change-pass-phrase is failed *****"
   echo
fi
   echo
   echo SUCCEEDED
   echo "***** myproxy-change-pass-phrase is succeeded *****"

myproxy-destroy -v -s $MYPROXY_SERVER
testkey="/tmp/myproxy-test.$$.key"
echo $passphrase | openssl rsa -des3 -passout stdin -in $X509_USER_KEY -out $testkey
chmod 0600 $testkey
myproxy-store -x -E '$cert_subject' -v -t 1 -y $testkey
if [ "$?" -ne 0 ]
then
   echo
   echo FAILED
   echo "***** myproxy-store is failed . Server does not support myproxy-store. *****"
   echo
   ERR=1
else
   echo
   echo SUCCEEDED
   echo "***** myproxy-store is succeeded *****"
   echo
   echo "***** get info for stored credential *****"
   myproxy-info -v
   if [ "$?" -eq 0 ]
 then
   echo SUCCEEDED
   echo "***** info for stored credential is succeeded *****"
   echo
   myproxy-destroy -v -s $MYPROXY_SERVER
 fi
fi 
rm -f /tmp/myproxy-test*
