#!/bin/bash
#****** SE/SE-lcg-cr
# NAME
# SE-lcg-cr - Tries to copy and register a file on the SE. This sensors returns OK if: 
# * The lcg-cr operation returned successfuly.
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2008-07-25
#
# LANGUAGE
#
# bash
#
# SOURCE

#. $SAME_SENSOR_HOME/config.sh

export LFC_HOME=/grid/$SAME_VO
export LCG_CATALOG_TYPE=lfc
timestamp=`date +%s`
nodeName=$1

echo "Checking if a file can be copied and registered to $nodeName"

#echo_config

echo "<p>"
echo "Using lcg-utils version:"
echo "<p>"
echo "<pre>"
#set -x
lcg-cr --version
#set +x
echo "</pre>"

echo "<pre>"
lfn="lfn:SE-lcg-cr-$nodeName-$timestamp"
echo $lfn >testFile.lfn
#set -x
echo "This is a tests `date`" > $SAME_SENSOR_WORK/testFile.txt
lcg-cr $LCG_UTIL_TIMEOUT -v --vo $SAME_VO file:$SAME_SENSOR_WORK/testFile.txt -l $lfn -d $nodeName
result=$?
#set +x
echo "</pre>"
if [ $result  == 0 ] ; then
    exit $SAME_OK
else
    exit $SAME_ERROR
fi

