#!/bin/bash
#****** SE/SE-lcg-del
# NAME
# SE-lcg-del - Delete and unregister the test file. This sensors returns OK if: 
# * The lcg-del operation returned successfuly.
#
#
# AUTHOR
#
#  SAM Team sam-devel[at]cern.ch
#
# LAST UPDATED
#
# 2008-07-25
#
# LANGUAGE
#
# bash
#
# SOURCE

#. $SAME_SENSOR_HOME/config.sh

export LFC_HOME=/grid/$SAME_VO
export LCG_CATALOG_TYPE=lfc
timestamp=`date +%s`
nodeName=$1

echo "Checking if a file can be removed from $nodeName"

#echo_config

echo "<p>"
echo "Using lcg-utils version:"
echo "<p>"
echo "<pre>"
#set -x
lcg-del --version
#set +x
echo "</pre>"

echo "<pre>"
lfn=`cat testFile.lfn`
#set -x
lcg-del $LCG_UTIL_TIMEOUT -v --vo $SAME_VO -a $lfn
result=$?
#set +x
echo "</pre>"
if [ $result  == 0 ] ; then
    exit $SAME_OK
else
    exit $SAME_ERROR
fi

#****
