#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Dimitar Shiyachki <Dimitar.Shiyachki@cern.ch>
#
##############################################################################

source helperFunctions

error=0

export DPNS_HOME="/dpm/$CFG_DPNS_DOMAIN/$CFG_DPNS_BASEDIR/$CFG_VO"
TEST_DIR=d`date +%s%N`
TEST_SUBDIR1=s1`date +%s%N`
TEST_SUBDIR2=s2`date +%s%N`
DUMMY_USERNAME=u`date +%s`
G1=g1`date +%s`
G2=g2`date +%s`

POOLNAME=pool`date +%s`
FSNAME1=fs1`date +%s`1
FSNAME2=fs2`date +%s`1

mkdir -p /tmp/$FSNAME1
mkdir -p /tmp/$FSNAME2

TOKEN=t`date +%s`

STD_OUT=/tmp/stdout-`date +%s%N`
STD_ERR=/tmp/stderr-`date +%s%N`

TEMP_FILE=/tmp/_dpm_test_temp`date +%s%N`
TEST_RESULT="SUCCESS"

testName="Test 1:Release space that has a token description using GUID"

r_current=0
dpm-reservespace --gspace 10M --token_desc $TOKEN >$STD_OUT 2>$STD_ERR
ret=$?
if [ $ret -ne 0 ]; then
   reportComponent "$testName:dpm-reservespace returned $ret:FAILURE"
   reportOutput dpm-reservespace $STD_OUT $STD_ERR
   r_current=1
else
   the_guid=$(cat $STD_OUT)
fi

if [ $r_current -ne 1 ]; then
   dpm-releasespace --space_token $the_guid >$STD_OUT 2>$STD_ERR
   ret=$?
   if [ $ret -ne 0 ]; then
      reportComponent "$testName:dpm-releasespace returned $ret:FAILURE"
      reportOutput dpm-reservespace $STD_OUT $STD_ERR
      r_current=1
   else
      dpm-getspacemd --space_token $the_guid >$STD_OUT 2>$STD_ERR
      ret=$?
      if [ $ret -eq 0 ] && grep -q "^$the_guid" $STD_OUT; then
         reportComponent "$testName:dpm-getspacemd returned 0 and space still exists:FAILURE"
         reportOutput dpm-reservespace $STD_OUT $STD_ERR
         r_current=1
      else
         reportComponent "$testName:dpm-releasespace returned 0 and release confirmed:SUCCESS"
      fi
   fi
fi

if [ $r_current -eq 1 ]; then
   error=1
fi

testName="Test 2:Release space that has no token description using GUID"

r_current=0
dpm-reservespace --gspace 10M >$STD_OUT 2>$STD_ERR
ret=$?
if [ $ret -ne 0 ]; then
   reportComponent "$testName:dpm-reservespace returned $ret:FAILURE"
   reportOutput dpm-reservespace $STD_OUT $STD_ERR
   r_current=1
else
   the_guid=$(cat $STD_OUT)
fi

if [ $r_current -ne 1 ]; then
   dpm-releasespace --space_token $the_guid >$STD_OUT 2>$STD_ERR
   ret=$?
   if [ $ret -ne 0 ]; then
      reportComponent "$testName:dpm-releasespace returned $ret:FAILURE"
      reportOutput dpm-reservespace $STD_OUT $STD_ERR
      r_current=1
   else
      dpm-getspacemd --space_token $the_guid >$STD_OUT 2>$STD_ERR
      ret=$?
      if [ $ret -eq 0 ] && grep -q "^$the_guid" $STD_OUT; then
         reportComponent "$testName:dpm-getspacemd returned 0 and space still exists:FAILURE"
         reportOutput dpm-reservespace $STD_OUT $STD_ERR
         r_current=1
      else
         reportComponent "$testName:dpm-releasespace returned 0 and release confirmed:SUCCESS"
      fi
   fi
fi

testName="Test 3:Release space that has token description using it"

r_current=0
dpm-reservespace --gspace 10M --token_desc $TOKEN >$STD_OUT 2>$STD_ERR
ret=$?
if [ $ret -ne 0 ]; then
   reportComponent "$testName:dpm-reservespace returned $ret:FAILURE"
   reportOutput dpm-reservespace $STD_OUT $STD_ERR
   r_current=1
else
   the_guid=$(cat $STD_OUT)
fi
if [ $r_current -ne 1 ]; then
   dpm-releasespace --token_desc $TOKEN >$STD_OUT 2>$STD_ERR
   ret=$?
   if [ $ret -ne 0 ]; then
      reportComponent "$testName:dpm-releasespace returned $ret:FAILURE"
      reportOutput dpm-reservespace $STD_OUT $STD_ERR
      r_current=1
   else
      dpm-getspacemd --space_token $the_guid >$STD_OUT 2>$STD_ERR
      ret=$?
      if [ $ret -eq 0 ] && grep -q "^$the_guid" $STD_OUT; then
         reportComponent "$testName:dpm-getspacemd returned 0 and space still exists:FAILURE"
         reportOutput dpm-reservespace $STD_OUT $STD_ERR
         r_current=1
      else
         reportComponent "$testName:dpm-releasespace returned 0 and release confirmed:SUCCESS"
      fi
   fi
fi

rm -f $STD_OUT
rm -f $STD_ERR

