#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Dimitar Shiyachki <Dimitar.Shiyachki@cern.ch>
#
##############################################################################

source helperFunctions

error=0

export DPNS_HOME="/dpm/$CFG_DPNS_DOMAIN/$CFG_DPNS_BASEDIR/$CFG_VO"
TEST_DIR=d`date +%s%N`
TEST_SUBDIR1=s1`date +%s%N`
TEST_SUBDIR2=s2`date +%s%N`
DUMMY_USERNAME=u`date +%s`
G1=g1`date +%s`
G2=g2`date +%s`

POOLNAME=pool`date +%s`
FSNAME1=fs1`date +%s`1
FSNAME2=fs2`date +%s`1

mkdir -p /tmp/$FSNAME1
mkdir -p /tmp/$FSNAME2

POOLNAME=pn`date +%s`

STD_OUT=/tmp/stdout-`date +%s%N`
STD_ERR=/tmp/stderr-`date +%s%N`

TEMP_FILE=/tmp/_dpm_test_temp`date +%s%N`
TEST_RESULT="SUCCESS"

testName="Test 1:Remove an existing filesystem"

r_current=0
dpm-addpool --poolname $POOLNAME >$STD_OUT 2>$STD_ERR
ret=$?
if [ $ret -ne 0 ]; then
   reportComponent "$testName:dpm-addpool returned $ret:FAILURE"
   reportOutput dpm-addpool $STD_OUT $STD_ERR
   r_current=1
fi

if [ $r_current -ne 1 ]; then
   dpm-addfs --poolname $POOLNAME --server $DPM_HOST --fs /tmp >$STD_OUT 2>$STD_ERR
   ret=$?
   if [ $ret -ne 0 ]; then
      reportComponent "$testName:dpm-addfs returned $ret:FAILURE"
      reportOutput dpm-addfs $STD_OUT $STD_ERR
      r_current=1
   else
      dpm-rmfs --server $DPM_HOST --fs /tmp >$STD_OUT 2>$STD_ERR
      ret=$?
      if [ $ret -eq 0 ]; then
         dpm-listspaces --pool $POOLNAME --long >$STD_OUT 2>$STD_ERR
         if [ $? -eq 0 ] && ( ! grep -q "$DPM_HOST:/tmp" $STD_OUT ); then
            reportComponent "$testName:dpm-rmfs returned 0 and removal confirmed:SUCCESS"
         else
            reportComponent "$testName:dpm-rmfs returned 0 but removal not confirmed:FAILURE"
            r_current=1
         fi
      else
         reportComponent "$testName:dpm-rmfs returned $ret:FAILURE"
         reportOutput dpm-rmfs $STD_OUT $STD_ERR
         r_current=1
      fi
   fi
fi

if [ $r_current -eq 1 ]; then
   error=1
fi
dpm-rmpool --poolname $POOLNAME

testName="Test 2:Remove a non-existing filesystem"

dpm-rmfs --server $DPM_HOST --fs /non-existing-fs >$STD_OUT 2>$STD_ERR
ret=$?
if [ $ret -eq 0 ]; then
   reportComponent "$testName:dpm-rmfs returned 0:FAILURE"
   reportOutput dpm-rmfs $STD_OUT $STD_ERR
   r_current=1
else
   if grep -q "No such filesystem" $STD_ERR; then
      reportComponent "$testName:dpm-rmfs exited with $ret and printed an appropriate error:SUCCESS"
   else
      reportComponent "$testName:dpm-rmfs exited with $ret but did not print the expected error:FAILURE"
      r_current=1
   fi
fi

if [ $r_current -eq 1 ]; then
   error=1
fi


rm -f $STD_OUT
rm -f $STD_ERR

