#!/bin/bash
export vo_name=$SAME_VO
export SE=lxbra1910.cern.ch
export LCG_GFAL_INFOSYS=lxbra2305.cern.ch:2170
export FILE=config_file
export LFCDIR=/grid/$SAME_VO/LFC/$LFC_HOST
#export SHORT=0 		

# Check all access (pointed in var MODE)
export SHORT=1			# Check short access: 000, 777
#export MODE=8			# Check all var acesses: 000 - 777, 512 variants . Running very long time (1 hour)
export MODE=4			# Check acesss: 000 - 222 (--- -wx-wx-wx )
export DMAX=5			# check deletion subdirectories (DMAX chaines)

#--------- temporary files ---------------

mkdir /tmp/$LFC_HOST >> /dev/null 2>&1
export lfc_tmp=/tmp/$LFC_HOST/lfc_tmp
export lfc_stderr=/tmp/$LFC_HOST/lfc_stderr
export tempo=/tmp/$LFC_HOST/lfc_tempo
