#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete  LFC file for VO                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################

echo "<pre>"
export LFC_HOST=$1
echo  $LFC_HOST
GUID=""

function delGuid () {
    echo "Delete $GUID"
    lcg-del -a $GUID
}
        
function clear (){
   lfc-rm -r -f $1

}

source config_file
echo $SAME_OK
echo $SAME_VO

rm -rf $lfc_tmp
rm -rf $lfc_stderr

date
echo "<br>"
echo "Test LFC CLI remove file lfc-rm <LFN>"
echo "<br>"
echo "VO=$vo_name"
echo "FILE=$FILE"
echo "SE=$SE"
echo "LCG_GFAL_INFOSYS=$LCG_GFAL_INFOSYS"

echo "<br>"
echo "<br>"


main_dir="$LFCDIR/rmfile"

echo "<br>"
echo "Strong check if directory nonexists"
echo "List of nonexist directory"
lfc-ls -l $main_dir
clear $main_dir
echo "OK"

echo
echo "2. Remove ordinary file"

echo "2.1. Create main directory: $main_dir"
lfc-mkdir -p $main_dir
fname="test_file"
LFN="$main_dir/$fname"
echo "SE=$SE, LFN=$LFN, file=$FILE"

echo "2.2. Create guid and lfn:$LFN"

fguid=`lcg-cr -l $LFN -d $SE --vo $vo_name file:$FILE`
GUID=$fguid
echo $fguid
echo $fguid > $lfc_tmp

grep "guid:" $lfc_tmp > /dev/null
if [ $? == 1 ]; then
    echo "Noncorrect create GUID, exit"
    cat $lfc_tmp
    echo "-TEST FAILED-"
    clear $main_dir
    exit $SAME_ERROR
fi
echo "OK"
                    
echo "2.3. Remove 'read only' file"
echo "2.3.1. Change access filr mode to 400"
lfc-chmod 400 $LFN
lfc-rm -f $LFN 2> $lfc_stderr
cat $lfc_stderr
grep "File exists" $lfc_stderr > /dev/null    # Because GUID exists!!!

if [ $? == 1 ]; then 
   echo "Non correct lfc-rm result"
    cat $lfc_stderr
   echo "-TEST FAILED-"
   lfc-chmod 777 $LFN
   delGuid
   clear $main_dir
   exit $SAME_ERROR
fi                    
echo "Restore file protection to 777"
lfc-chmod 777 $LFN

                    
echo "Remove created LFN and guid"
echo "File list before:"
lfc-ls $main_dir
echo "Remove LFN without removing GUID"

lfc-rm $LFN 2> $lfc_stderr
cat $lfc_stderr

grep "File exists"  $lfc_stderr  > /dev/null
if [ $? == 1 ]; then
    echo "Non correct lfc-rename result"
    echo "-TEST FAILED-"
    delGuid
    clear $main_dir
    exit $SAME_ERROR
fi
echo "OK"


echo "2. SCENARIO: Delete nonexisting file: $main_dir/nofile"
echo "<br>"

lfc-rm  $main_dir/nofile  2> $lfc_stderr
cat $lfc_stderr
grep "No such file or directory" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Noncorrect diagnose, exit"
   cat $lfc_stderr
   echo "-TEST FAILED-"
   delGuid
   clear $main_dir
   exit $SAME_ERROR
fi

echo "OK"

echo
echo "Cleaning tasks"
echo "<br>"
delGuid
clear $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
