#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Change access mode of  LFC subdirectories for VO                 #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export LFC_HOST=$1
echo $LFC_HOST
access=( --- --x -w- -wx r-- r-x rw- rwx )

function clear (){
   lfc-rm -r -f $1
}


function checkMode () {
    cdir=$4
    mode=$1$2$3
    QAC="d${access[$1]}${access[$2]}${access[$3]}"
    echo -n "   $QAC"    # " $mode"
                
    lfc-chmod $mode $cdir
                    
    lfc-ls -l $main_dir > $lfc_tmp
    grep $QAC $lfc_tmp > /dev/null
    if [ $? == 1 ]; then
        echo "-TEST FAILED-"
        echo "Set mode: $mode"
        echo "Get mode:"
        cat $lfc_tmp
        lfc-chmod 777 $cdir
        clear $main_dir
        exit $SAME_ERROR
    fi
}
                                                                                                    
source config_file
main_dir="$LFCDIR/test-chdir"

rm -rf $lfc_tmp
rm -rf $lfc_stderr

date
echo "<br>"
echo "Test LFC CLI chmod for directory"
echo "<br>"
echo "VO=$vo_name"
echo "LFCDIR=$LFCDIR"
echo "<br>"
echo "<br>"

echo "SCENARIO: Directory doesn't exist"
echo "<br>"

cdir="$main_dir/test-qwerty"
echo "<br>"
echo "Strong check if directory nonexists"
echo "List of nonexist directory"
lfc-ls -l $main_dir
echo "Remove nonexist directory"
lfc-chmod 777 $cdir
clear $cdir
clear $main_dir
echo "OK"

echo
echo "1. Change mode for nonexist directory"
#lfc-chmod 777 $main_dir
lfc-chmod 777 $main_dir 2> $lfc_tmp
grep "No such file or directory" $lfc_tmp > /dev/null
if [ $? == 1 ]; then 
   echo "Noncorrect diagn, exit"
   cat $lfc_tmp
   echo "-TEST FAILED-"
   clear $main_dir
   exit $SAME_ERROR
fi
echo "OK"

echo
echo "SCENARIO: check mode for exist  directory"
echo "SHORT=$SHORT, MODE=$MODE"

echo "Create main directory: $main_dir"
lfc-mkdir -p $main_dir

cdir=$main_dir/test-subdir
echo "Create test subdirectory: $cdir"
lfc-mkdir $cdir

if [ $SHORT == 1 ]; then
    echo "Short mode: 000, 777"
    checkMode 0 0 0 $cdir
    checkMode 2 2 2 $cdir
    checkMode 3 3 3 $cdir
    checkMode 6 6 6 $cdir
    checkMode 7 7 7 $cdir
else
    echo "Long mode: all mode 000-nnn, n<$MODE"
    UMAX=$MODE
    
    owner=0
    while [ $owner -lt $UMAX ]; do              # cycle for owner access
        group=0
        echo
        while [ $group -lt $UMAX ]; do          # cycle for group access
            user=0
            echo
            while [ $user -lt $UMAX ]; do       # cycle for all users
                checkMode $owner $group $user $cdir
                let user=$user+1
            done
            let group=$group+1
        done
        let owner=$owner+1
    done
fi

echo
echo "Cleaning tasks"
echo "<br>"
lfc-chmod 777 $cdir
clear $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
