#!/bin/bash
# Date: 09/11/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete  LFC subdirectories for VO                                #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - LFC host name                                                                     #
# Requisites:                                                                               #
#	- LFC server                                                                        #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################

echo "<pre>"
export LFC_HOST=$1
echo  $LFC_HOST

function clear (){
   lfc-rm -r -f $1

}

source config_file
echo $SAME_OK
echo $SAME_VO

rm -rf $lfc_tmp
rm -rf $lfc_stderr

date
echo "<br>"
echo "Test LFC CLI remove diectory. lfc-rm -r <dirname>"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "<br>"


main_dir="$LFCDIR/rmdir"

echo "Scenario: Direcrory exists"
echo "1. Create main directory: $main_dir"
echo "<br>"
lfc-mkdir -p $main_dir

rdon="$main_dir/rdonly"
echo "2. Remove 'read only' directory"
lfc-mkdir -m 400 $rdon
lfc-rm -f -r $rdon 2> $lfc_stderr
grep "Permission denied" $lfc_stderr > /dev/null

if [ $? == 1 ]; then 
   echo "Non correct lfc-rm result"
   echo "-TEST FAILED-"
   lfc-chmod 777 $rdon
   clear $main_dir
   exit $SAME_ERROR
fi
lfc-chmod 777 $rdon
clear $rdon
echo "OK"

echo
echo "3.  Create $DMAX subdirectories"
echo "<br>"
counter=0
dir=$main_dir
pdir=$main_dir

while [ $counter -lt $DMAX ]; do
  subdir="subdir-$counter"
  dir=$dir/$subdir
  echo "new dir:$dir"
  lfc-mkdir $dir
  lfc-ls $pdir > $lfc_tmp
  grep $subdir $lfc_tmp > /dev/null
  
  if [ $? == 1 ]; then 
    echo "-TEST FAILED-"
    clear $main_dir
    exit $SAME_ERROR
  fi
  
  pdir=$dir
  let counter=counter+1
done

echo "4. Remove all subdirectories, use -R option"
lfc-rm -R  -f $main_dir  
echo "5. Check deletion result"

lfc-ls $main_dir 2> $lfc_stderr
grep "No such file or directory" $lfc_stderr > /dev/null
 
if [ $? == 1 ]; then 
    echo "-TEST FAILED-"
    clear $main_dir
    exit $SAME_ERROR
fi 
echo "OK"

echo "2. SCENARIO: Delete nonexisting directory: $main_dir"
echo "<br>"

lfc-rm -r -f $main_dir  2> $lfc_stderr
cat $lfc_stderr
grep "No such file or directory" $lfc_stderr > /dev/null

if [ $? == 0 ]; then 
   echo "Noncorrect diagnose, exit"
   cat $lfc_stderr
   echo "-TEST FAILED-"
   clear $main_dir
   exit $SAME_ERROR
fi

echo "OK"

echo
echo "Cleaning tasks"
echo "<br>"
clear $main_dir
rm -rf $lfc_tmp
rm -rf $lfc_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
