#!/bin/bash
#
######
#	Copyright (c) Members of the EGEE Collaboration. 2004.
#	See http://www.eu-egee.org/partners/ for details on the copyright holders.
#
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#
#	    http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#########


#
# Startup script for the WMProxy Service Apache Web Server
#
#############
# processname: httpd
# pidfile: ${WMS_LOCATION_VAR}/httpd-wmproxy.pid 
# config: ${WMS_LOCATION_ETC}/glite_wms_wmproxy_httpd.conf 

#########################################################
. /opt/glite/yaim/etc/grid-env-funcs.sh
. /etc/profile.d/grid-env.sh 
#########################################################


httpdpath=${GLITE_WMS_WMPROXY_HTTPD-/usr/sbin/httpd}
httpd=`basename $httpdpath`
config=${GLITE_WMS_CONFIG_DIR}/glite_wms_wmproxy_httpd.conf
port=${GLITE_WMS_WMPROXY_PORT-7443}
RETVAL=0

# See how we were called.
case "$1" in
  status)
        if ( netstat -lten | grep "^tcp .*:$port .*LISTEN" ) >/dev/null 2>&1 ;then
         echo WMProxy $httpd listening on port $port
         httpd_pids=`/sbin/pidof $httpdpath`
         RETVAL=$?
         if [ ${RETVAL} -eq 0 ]; then
          echo $httpd \(pid $httpd_pids\) is running ....
          echo "==="
          echo WMProxy Server running instances:
          echo "`ps -fC glite_wms_wmproxy_server`"
         fi
        else
         echo WMProxy $httpd NOT listening on port $port
         echo "==="
         echo Checking for other $httpd running instances .....
         if ( /sbin/pidof $httpd ) >/dev/null 2>&1 ; then
          echo $httpd \(pid `/sbin/pidof $httpd`\) is running ....
         else 
          echo None found
         fi
         RETVAL=1
        fi
	;;
  start|stop|restart)
	ps auxwww | awk '/^glite .*[_]wmproxy/ { print $2 }' | xargs -r kill -15 2>/dev/null
	sleep 10 
	ps auxwww | awk '/^glite .*[_]wmproxy/ { print $2 }' | xargs -r kill -9 2>/dev/null 
	#$apachectl -k $@ -f $config
	$httpdpath -k $@ -f $config
	RETVAL=$?
	;;
  graceful)
  $httpdpath -k $@ -f $config
  RETVAL=$?
  ;;
  configtest)
	$httpdpath -t -f $config
	RETVAL=$?
	;;
  *)
	echo $"Usage: glite-wms-wmproxy {start|stop|restart|status|help|configtest}"
	exit 1
esac

exit $RETVAL
