<?xml version="1.0" encoding="UTF-8"?>
<definitions name="DataLocationInterface"
 targetNamespace="urn:DataLocationInterface"
 xmlns:tns="urn:DataLocationInterface"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:datalocationinterface="urn:DataLocationInterface"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:DataLocationInterface"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:datalocationinterface="urn:DataLocationInterface"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
  <complexType name="ArrayOfstring">
   <complexContent>
    <restriction base="SOAP-ENC:Array">
     <sequence>
      <element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
     </sequence>
     <attribute ref="SOAP-ENC:arrayType" WSDL:arrayType="xsd:string[]"/>
    </restriction>
   </complexContent>
  </complexType>
 </schema>

</types>

<message name="listReplicas">
 <part name="inputDataType" type="xsd:string"/>
 <part name="inputData" type="xsd:string"/>
</message>

<message name="listReplicasResponse">
 <part name="urlList" type="datalocationinterface:ArrayOfstring"/>
</message>

<portType name="DataLocationInterfacePortType">
 <operation name="listReplicas">
  <documentation>Service definition of function datalocationinterface__listReplicas</documentation>
  <input message="tns:listReplicas"/>
  <output message="tns:listReplicasResponse"/>
 </operation>
</portType>

<binding name="DataLocationInterface" type="tns:DataLocationInterfacePortType">
 <SOAP:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="listReplicas">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="urn:DataLocationInterface" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="urn:DataLocationInterface" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="DataLocationInterface">
 <documentation>gSOAP 2.7.6b generated service definition</documentation>
 <port name="DataLocationInterface" binding="tns:DataLocationInterface">
  <SOAP:address location="http://localhost:8085"/>
 </port>
</service>

</definitions>
