#!/bin/bash
# Revised: March 2008                                                                       #

#    Config file for test of voms-admin command
export vo_name="test"         # Virtuale organization

PROJECT="/afs/cern.ch/project/gd/yaim-server/BitFaceCA/user_certificates"

export USER="$PROJECT/test_user_1_cert.pem"
export USER1="$PROJECT/test_user_1_cert.pem"
export USER2="$PROJECT/test_user_2_cert.pem"
export USER3="$PROJECT/test_user_3_cert.pem"
export USER4="$PROJECT/test_user_4_cert.pem"

export CA="/C=CH/O=CERN/OU=GD/CN=The Certification CA"
export CA_CERN="/C=CH/O=CERN/OU=GRID/CN=CERN CA"
export GRIDMAP="$SAME_SENSOR_HOME/tests/gridmap-test-1928" # gridmap config for "test" & "lxb1928"
export ACCOUNT=".$vo_name"    # Mapped user account for grid_mapfile
export ROLE="sam_tester"      # Greate/delete Role
export GROUP="sam_group"      # Create/delete Group
export OP="list"              # Operation value (list, all, add,... ) for test ACL management
export ALLOW="allow"          # Value  (allow or deny) for test ACL management

#---------- Values for attributes in voms-admin commands
export ATTRIBUTE="TEST_ATTRIBUTE"
export ATTVALUE="TEST Attribute value"
export ATTDESC="Test Attribute description"

#--------- temporary files ------------------------------------
export voms_tmp=$SAME_SENSOR_WORK/nodes/$nodeName/voms_tmp
export voms_stderr=$SAME_SENSOR_WORK/nodes/$nodeName/voms_stderr
export tempo=$SAME_SENSOR_WORK/nodes/$nodeName/voms_tempo
export cert_dir=$SAME_SENSOR_WORK/nodes/$nodeName/voms_certdir
