#!/bin/bash
#  Config file for testing "voms-proxy-init" command

export vo_name="test"                                        # Virtuale organization
export USER="$SAME_SENSOR_HOME/tests/test_user_cert.pem"     # test_user_2_cert.pem
export CA="/C=CH/O=CERN/OU=GD/CN=The Certification CA"
export CA_CERN="/C=CH/O=CERN/OU=GRID/CN=CERN CA"
export CA_0="/etc/grid-security/certificates/1cda0759.0"                   # for option -certdir
export CA_policy="/etc/grid-security/certificates/1cda0759.signing_policy" # for option -certdir
export GLOBUS=2                                                # used Globus version (for -proxyver)
export VOMSES="$SAME_SENSOR_HOME/vomses-1928"                  # vomses file for lxb1928.cern.ch
export USERCERT="$SAME_SENSOR_HOME/tests/test_user_cert.pem"   # test_user_2_cert.pem
export USERKEY="$SAME_SENSOR_HOME/tests/test_user_key.pem"     # test_user_2_key.pem
export PWS="$SAME_SENSOR_HOME/tests/pws"                       # password file for $USER

#--------- temporary files ---------------
export voms_tmp=$SAME_SENSOR_WORK/nodes/$nodeName/voms_tmp
export voms_stderr=$SAME_SENSOR_WORK/nodes/$nodeName/voms_stderr
export tempo=$SAME_SENSOR_WORK/nodes/$nodeName/voms_tempo
export cert_dir=$SAME_SENSOR_WORK/nodes/$nodeName/voms_certdir # directory for test -certdir
