#!/bin/bash
export vo_name="test"       # Virtuale organization
export USER="$SAME_SENSOR_HOME/tests/test_user_cert.pem"
export CA="/C=CH/O=CERN/OU=GD/CN=The Certification CA"
export CA_CERN="/C=CH/O=CERN/OU=GRID/CN=CERN CA"

#--------- temporary files ---------------
export voms_tmp=/tmp/$voms_host.$UID"_tmp"
export voms_stderr=/tmp/$voms_host.$UID"_stderr"
export tempo=/tmp/$voms_host.$UID"_string"
export cert_dir=/tmp/$voms_host.$UID"_certdir"

export VOMSES="$SAME_SENSOR_HOME/vomses-1928"
export USERCERT="$SAME_SENSOR_HOME/tests/test_user_cert.pem"
export USERKEY="$SAME_SENSOR_HOME/tests/test_user_key.pem"
export PWS="$SAME_SENSOR_HOME/tests/pws"

