#!/bin/bash
# Date: 21/03/2007                                                                          #
# Revised: March 2008                                                                       #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'certdir' for voms-proxy-init                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
#       - cert. directory
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="certdir"
#cdir="/etc/grid-security/certificates"

echo "CA.0: $CA_0"
echo "CA.signing_policy: $CA_policy"

rm -rf $voms_tmp

echo "Remove directory $cert_dir"
rm -rf $cert_dir/*
rmdir $cert_dir 2> /dev/null

date
echo "VOMS-PROXY-INIT: check option - $OPTION"
echo "Create directory: $cert_dir"
mkdir $cert_dir

echo "Copy CA files into new directory"
cp $CA_0  $cert_dir
cp $CA_policy $cert_dir

USER_SUBJECT=$(openssl x509 -in $USERCERT -noout -subject | sed -e 's/^subject=[ ]*//')
USER_ISSUER=$(openssl x509 -in $USERCERT -noout -issuer | sed -e 's/^issuer=[ ]*//')

echo "1. Create new user and proxy"
voms-admin --vo=$vo_name --host $voms_host create-user $USER


voms-proxy-init -voms $vo_name -vomses $VOMSES --debug -cert $USERCERT -key $USERKEY -$OPTION $cert_dir -pwstdin < $PWS

if [ $? = 0 ]; then
  echo "Test is OK"
else 
  echo "Test is failed"
  voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER"
  rm -rf $voms_tmp
  rm -rf $cert_dir/*
  rmdir $cert_dir
  exit $SAME_ERROR
fi

echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"

#user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$USER_SUBJECT"

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp
echo "voms-proxy-info:"
echo
#cat $voms_tmp
echo "2.3. Check user DN"
grep "$USER_SUBJECT" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER"
    rm -rf $voms_tmp
    rm -rf $cert_dir/*
    rmdir  $cert_dir
    exit $SAME_ERROR
fi

echo "3. Check if option -ceretdir points to noncorrect directory (doesn't contents trusted CA files)" 

voms-proxy-init -voms $vo_name -vomses $VOMSES --debug -cert $USERCERT -key $USERKEY -$OPTION "/tmp" -pwstdin < $PWS

if [ $? = 1 ]; then
  echo "Test is OK"
else 
  echo "Test is failed"
  voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER"
  rm -rf $voms_tmp
  rm -rf $cert_dir/*
  rmdir $cert_dir
  exit $SAME_ERROR
fi


echo "Test is OK"
echo "Task cleanning"
voms-admin --vo=$vo_name --host $voms_host --nousercert delete-user "$USER_SUBJECT" "$USER_ISSUER"
rm -rf $voms_tmp
rm -rf $cert_dir/*
rmdir $cert_dir

echo "</pre>"
exit $SAME_OK


