#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Add  one user as member to group                                 #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - User certificate file path                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#       - user certificate                                                                  #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-addMember:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"
echo "User=$USER"
echo "<br>"

user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`

echo "SCENARIO: VO empty"
echo "<br>"
echo "Add non existing user in non existing group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create new group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
echo "Add non existing user in group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
echo "Add user in group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp
grep "$user_subject" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Error when adding user to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi

echo "SCENARIO: User is already a member of the group"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER 2> $voms_stderr
grep "is already a member of group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Cleaning tasks"

voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP $USER
voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
