#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Revised: March 2008                                                                       #
# Description of the test: Create Role for VO                                               #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                       #
#       - VO host name                                                                      #
#       - Role                                                                              #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
###########################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-crRole:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"

USER_SUBJECT=$(openssl x509 -in $USER -noout -subject | sed -e 's/^subject=[ ]*//')
USER_ISSUER=$(openssl x509 -in $USER -noout -issuer | sed -e 's/^issuer=[ ]*//')

echo "SCENARIO: Role doesn't exist"
echo "<br>"
echo "Create new Role"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host create-role $ROLE
voms-admin --vo=$vo_name --host $voms_host list-roles > $voms_tmp
echo "Check role"
grep "$ROLE" $voms_tmp   > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-role $ROLE
    echo "Error creating the role"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO 2: Role already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host create-role $ROLE > $voms_stderr
grep "org.glite.security.voms.admin.database.AlreadyExistsException: Role " $voms_stderr > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name --host $voms_host delete-role $ROLE
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host delete-role $ROLE

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
