#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test user list command                                           #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - trusted  certificate authority                                                       #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
#rm -rf $tempo

echo ""
date
echo "VOMS-listUsers - started, VO=$vo_name, CA=$CA"


user1="DN_USER1"
user2="DN_USER2"
user3="DN_USER3"
user4="DN_USER4"

echo "Step 1: Create 4 nocert users: $user1, $user2, $user3, $user4"

voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user2" "$CA" "CN-User2" "user2@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user3" "$CA" "CN-User3" "user3@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user4" "$CA" "CN-User4" "user4@cern.ch"
echo "OK"

echo "Step 2: Check list users"

voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp

#cat $voms_tmp

echo "Check Subject name, "

grep "$user1" $voms_tmp

if [ $? == 1 ]; then
   echo "User $user1 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user2" $voms_tmp

if [ $? == 1 ]; then
   echo "User $user2 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user3" $voms_tmp

if [ $? == 1 ]; then
   echo "User $user3 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi

grep "$user4" $voms_tmp

if [ $? == 1 ]; then
   echo "User $user4 not created"
   echo "LIST:<"
   cat $voms_tmp
   echo ">"
   echo "Test has failed"
   exit $SAME_ERROR
fi
echo "OK"

echo "Clear Created users"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test is OK"
exit $SAME_OK
