#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete group for VO                                              #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - Group name                                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-delGroup:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$GROUP"
echo "<br>"

echo "SCENARIO: Group doesn't exist"
echo "<br>"
echo "Delete Group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr > /dev/null

if [ $? == 1 ]; then
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: Group already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp
grep "$GROUP" $voms_tmp > /dev/null

if [ $? == 0 ]; then
   echo "Error deleting the group"
   echo "<br>"
   cat $voms_tmp
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
