#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test user list command                                           #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - trusted  certificate authority                                                       #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-listUsers:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "CA=$CA"
echo "<br>"

user1="DN_USER1"
user2="DN_USER2"
user3="DN_USER3"
user4="DN_USER4"

echo "SCENARIO: Create 4 users: $user1, $user2, $user3, $user4"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user2" "$CA" "CN-User2" "user2@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user3" "$CA" "CN-User3" "user3@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user4" "$CA" "CN-User4" "user4@cern.ch"

echo "SCENARIO: List users"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp
echo "Check DN"
echo "<br>"
grep "$user1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   echo "Error creating user $user1"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   echo "Error creating user $user2"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user3" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   echo "Error creating user $user3"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user4" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   echo "Error creating user $user4"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
