#!/bin/bash
# Date: 12/02/2007                                                                          #
# Revised: March 2008                                                                       #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Set Attribute to group                                           #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group name                                                                        #
#       - VO host name                                                                      #
#       - Attribute                                                                         #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-setGroupAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Attribute value=$ATTVALUE"
echo "<br>"
echo "Attribute description=$ATTDESC"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"

USER_SUBJECT=$(openssl x509 -in $USER -noout -subject | sed -e 's/^subject=[ ]*//')
USER_ISSUER=$(openssl x509 -in $USER -noout -issuer | sed -e 's/^issuer=[ ]*//')

echo "SCENARIO: VO empty"
echo "<br>"

voms-admin --vo=$vo_name --host $voms_host  set-group-attribute  > $voms_stderr
grep "Missing group argument!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

voms-admin --vo=$vo_name --host $voms_host  set-group-attribute "/$vo_name/$GROUP"  > $voms_stderr
grep "Missing string argument!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

voms-admin --vo=$vo_name --host $voms_host  set-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" > $voms_stderr
grep "Missing string argument!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create group"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host create-group "/$vo_name/$GROUP"
voms-admin --vo=$vo_name --host $voms_host create-attribute-class $ATTRIBUTE "$ATTDESC" 0

echo "OK, assign attribte  $ATTRIBUTE, value=$ATTVALUE and description=$ATTDESC to new group $GROUP"
echo "<br>"
echo "1. set-group-attribute"
voms-admin --vo=$vo_name --host $voms_host  set-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" "$ATTVALUE" 
echo "2. OK, list-group-attribute"
voms-admin --vo=$vo_name --host $voms_host  list-group-attributes "/$vo_name/$GROUP" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
    echo "Error when assigning attribute to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi

grep "$ATTVALUE" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
    echo "Error when assigning attribute to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name --host $voms_host delete-group "/$vo_name/$GROUP"        
voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
	
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK

