#!/bin/bash
# Date: 13/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: List attributes for the specified group and Role in VO           #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group name                                                                        #
#       - Role name                                                                         #
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-listRoleAttributes:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"

echo "1. SCENARIO: VO empty"
echo "<br>"

echo "1.1.  List non existing role attributes without parameters"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes 2> $voms_stderr
grep "No group name given" $voms_stderr > /dev/null
    
if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "1.2. List non existing role attributes"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" 2> $voms_stderr
grep "No role name given" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "OK"

echo "1.3. List non existing role attributes of nonexisting group"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" "Role=$ROLE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
                        
echo "OK"

echo "2. SCENARIO: Create group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"

echo "OK"
echo "<br>"
echo "2.1. create new Role"
voms-admin --vo=$vo_name -h $voms_host create-role "Role=$ROLE"

echo "2.2. List role attributes (role doesn't have attributes)"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" "Role=$ROLE" 2> $voms_stderr
grep "No attributes are returned" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "2.3. Set 3 attributes for role"
voms-admin --vo=$vo_name -h $voms_host  set-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE" "$ATTVALUE" "$ATTDESC"
voms-admin --vo=$vo_name -h $voms_host  set-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "ATTRIBUTE1" "ATTVALU1" "ATTDESC_1"
voms-admin --vo=$vo_name -h $voms_host  set-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "ATTRIBUTE2" "ATTVALU2" "ATTDESC_2"

echo "3. List role attributes"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" "Role=$ROLE" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Error when listing role attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

grep "ATTRIBUTE1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Error when listing role attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi


grep "ATTRIBUTE2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Error when listing role attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "OK"
echo "Cleaning tasks"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
