#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove one user using its user certificate                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - file config_file  (User certificate file path)                                    #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#                                                                                           #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-delUser:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "User=$USER"
echo "<br>"

user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`

echo "DN=$user_subject"
echo "<br>"

echo "SCENARIO: User doesn't exist"
echo "<br>"
echo "Remove non existing user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr  > /dev/null

if [ $? == 1 ]; then
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: User already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
echo "Remove existing user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
voms-admin --vo=$vo_name -h $voms_host list-users > $voms_tmp
grep "$user_subject" $voms_tmp  > /dev/null

if [ $? == 0 ]; then
    echo "Error deleting the user"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi


echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
