#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test roles list command                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-listRoles:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"

role1="ROLE1"
role2="ROLE2"
role3="ROLE3"
role4="ROLE4"

echo "SCENARIO: Create 4 roles : $role1, $role2, $role3, $role4"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host create-role  $role1
voms-admin --vo=$vo_name -h $voms_host create-role  $role2
voms-admin --vo=$vo_name -h $voms_host create-role  $role3
voms-admin --vo=$vo_name -h $voms_host create-role  $role4

echo "SCENARIO: List roles"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
echo "Check roles"
echo "<br>"
grep "$role1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-role $role1
   voms-admin --vo=$vo_name -h $voms_host delete-role $role2
   voms-admin --vo=$vo_name -h $voms_host delete-role $role3
   voms-admin --vo=$vo_name -h $voms_host delete-role $role4
   echo "Error creating role $role1"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$role2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-role $role1
   voms-admin --vo=$vo_name -h $voms_host delete-role $role2
   voms-admin --vo=$vo_name -h $voms_host delete-role $role3
   voms-admin --vo=$vo_name -h $voms_host delete-role $role4
   echo "Error creating role $role2"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$role3" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-role $role1
   voms-admin --vo=$vo_name -h $voms_host delete-role $role2
   voms-admin --vo=$vo_name -h $voms_host delete-role $role3
   voms-admin --vo=$vo_name -h $voms_host delete-role $role4
   echo "Error creating role $role3"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$role4" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-role $role1
   voms-admin --vo=$vo_name -h $voms_host delete-role $role2
   voms-admin --vo=$vo_name -h $voms_host delete-role $role3
   voms-admin --vo=$vo_name -h $voms_host delete-role $role4
   echo "Error creating role $role4"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi


echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-role $role1
voms-admin --vo=$vo_name -h $voms_host delete-role $role2
voms-admin --vo=$vo_name -h $voms_host delete-role $role3
voms-admin --vo=$vo_name -h $voms_host delete-role $role4

echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
