#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'conf' for voms-proxy-init                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="conf"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"
echo "conf file $VOMS_CNF :"
cat $VOMS_CNF

echo "1. Create new user and proxy"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
echo "1.1. voms-proxy-init"
voms-proxy-destroy
voms-proxy-init -vomses $VOMSES -cert $USERCERT -key $USERKEY -conf $VOMS_CNF -pwstdin < $PWS
#voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS

if [ $? = 0 ]; then
   echo "OK"
else 
   echo "Test is failed, exit code=1"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

sleep 5

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp
cat $voms_tmp


echo "2.3. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi

echo "2.4. Check strength"
grep "strength  : 512 bits" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "OK"

echo "2.5. Check vomslife"

echo "Check timeleft"
H1="12"
H2=`grep "timeleft" $voms_tmp | cut -d":" -f2`

echo "Compare $H1 (set time)  and $H2 (left time)"

if [ ${H2} \< ${H1} ]; then
   echo "OK"
else
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
               
echo "2.6. Check VO:"
VO="VO        : $vo_name"
voms-proxy-info -all > $voms_tmp

grep "$VO" $voms_tmp
if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi               
               

echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
echo "</pre>"
exit $SAME_OK