#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'failonwarn' for voms-proxy-init                    #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="failonwarn"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"


echo "1. Create new user and proxy with warning"
voms-admin --vo=$vo_name -h $voms_host create-user $USER

voms-proxy-init -voms $vo_name -vomses $VOMSES -valid 200:59 -cert $USERCERT -key $USERKEY -pwstdin < $PWS 2> $voms_tmp
cat $voms_tmp

grep "Warning" $voms_tmp

if [ $? = 0 ]; then
   echo "OK, Warning exists"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

echo "2. Create proxy with option -$OPTION"

voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -valid 200:59   -cert $USERCERT -key $USERKEY -pwstdin < $PWS

if [ $? = 0 ]; then
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
echo "</pre>"
exit $SAME_OK

