#!/bin/bash
# Date: 13/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove group's Attribute                                         #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group                                                                             #
#       - Attribute                                                                         #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured and empty VO                                                         #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-delGroupAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"

echo "SCENARIO: VO empty"
echo "<br>"

echo "1. Delete-group-attribute without parameters"
voms-admin --vo=$vo_name -h $voms_host  delete-group-attribute  2> $voms_stderr
grep "No group name given" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "2. Remove non existing Attribute of non existing group without attribute"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host  delete-group-attribute "/$vo_name/$GROUP" 2> $voms_stderr
grep "No attribute name specified!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"   
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "3. Remove non existing Attribute of non existing group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host  delete-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi                    



echo "SCENARIO: Create group"
echo "<br>Create group"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"
echo "OK, delete-group-attribute"
voms-admin --vo=$vo_name -h $voms_host delete-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" 2> $voms_stderr


grep "org.glite.security.voms.service.NotInDatabase: Not in database: Attribute" $voms_stderr > /dev/null
if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "$/vo_name/$GROUP"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Assign attribute to group"	
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host set-group-attribute  "/$vo_name/$GROUP" "$ATTRIBUTE" "$ATTVALUE" "$ATTDESC"


echo "Check group's attribute"
voms-admin --vo=$vo_name -h $voms_host list-group-attributes "/$vo_name/$GROUP" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null
if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Incorrect list message:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "<br>Delete groups attribute"

voms-admin --vo=$vo_name -h $voms_host  delete-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE"

echo "<br>Check deleted group attribute"
echo "list-group-attributes"

voms-admin --vo=$vo_name -h $voms_host list-group-attributes "/$vo_name/$GROUP" 2> $voms_stderr

grep "No attributes are returned" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
