#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete Role for VO                                               #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                       #
#       - VO host name                                                                      #
#       - file config_file (Role)                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-delRole:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"

echo "SCENARIO: Role doesn't exist"
echo "<br>"
echo "Delete Role"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase:" $voms_stderr   > /dev/null

if [ $? == 1 ]; then
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: Role already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
voms-admin --vo=$vo_name -h $voms_host list-roles > $voms_tmp
grep "$ROLE" $voms_tmp > /dev/null

if [ $? == 0 ]; then
   echo "Error deleting the role"
   echo "<br>"
   cat $voms_tmp
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK


