#!/bin/bash
# Date: 13/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: List attributes for the specified group in VO                    #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group name                                                                        #
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-listGroupAttributes:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"

echo "SCENARIO: VO empty"
echo "<br>"
echo "1. List non existing attributes without groupname"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-group-attributes 2> $voms_stderr
grep "No group name given" $voms_stderr > /dev/null
    
if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "2. List non existing attributes of nonexisting group"
voms-admin --vo=$vo_name -h $voms_host list-group-attributes "/$vo_name/$GROUP" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "OK"

echo "3. SCENARIO: Create group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"

echo "4. List attributes (group doesn't have attributes)"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-group-attributes "/$vo_name/$GROUP" 2> $voms_stderr
grep "No attributes are returned" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "OK"
echo "5. SCENARIO: Set new group 3 attributes"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host set-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" "$ATTVALUE" "$ATTDESC"
voms-admin --vo=$vo_name -h $voms_host set-group-attribute "/$vo_name/$GROUP" "ATTRIBUTE1" "ATTVALUE1" "ATTDESC1"
voms-admin --vo=$vo_name -h $voms_host set-group-attribute "/$vo_name/$GROUP" "ATTRIBUTE2" "ATTVALUE2" "ATTDESC2"



echo "6. List group attributes and check 3 assigned attributes"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-group-attributes "/$vo_name/$GROUP" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when listing group attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

grep "ATTRIBUTE1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when listing group attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi


grep "ATTRIBUTE2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when listing group attributes:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "OK"
echo "Cleaning tasks"
voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
