#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test subgroups list command                                      #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file


rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-listSubgroups:"
echo "VO=$vo_name"
echo "<br>"


group1="GROUP1"
group2="GROUP2"
group3="GROUP3"
group4="GROUP4"

echo "SCENARIO: Create 4 groups: $group1, $group2, $group3, $group4"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group1"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group1/$group2"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group1/$group2/$group3"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group1/$group2/$group3/$group4"

echo "SCENARIO: List groups"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-sub-groups "/$vo_name" > $voms_tmp
echo "Check 4 groups, "
echo "<br>"

grep "$group1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3/$group4"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1"
   echo "Error creating group $group1"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

voms-admin --vo=$vo_name -h $voms_host list-sub-groups "/$vo_name/$group1" > $voms_tmp
grep "$group2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3/$group4"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1"
   echo "Error creating group $group2"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

voms-admin --vo=$vo_name -h $voms_host list-sub-groups "/$vo_name/$group1/$group2" > $voms_tmp
grep "$group3" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3/$group4"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1"
   echo "Error creating group $group3"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

voms-admin --vo=$vo_name -h $voms_host list-sub-groups "/$vo_name/$group1/$group2/$group3" > $voms_tmp
grep "$group4" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3/$group4"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2"
   voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1"
   echo "Error creating group $group4"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3/$group4"
voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2/$group3"
voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1/$group2"
voms-admin --vo=$vo_name -h $voms_host delete-group "$vo_name/$group1"
rm -rf $voms_tmp
rm -rf $voms_stderr
echo "Test OK"
exit $SAME_OK
