#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'debug' for voms-proxy-init                         #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="debug"
rm -rf $voms_tmp
rm -rf $tempo


echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"

echo "1. Create new user and proxy"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
voms-proxy-init -voms $vo_name -vomses $VOMSES -$OPTION -cert $USERCERT -key $USERKEY -pwstdin < $PWS 1> $tempo

if [ $? = 0 ]; then
   echo "OK"
else 
   echo "Test is failed, exit code=1"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi


echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "2.3. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi

echo "3. Check debug info"
cat $tempo

grep "Detected Globus version: 22" $tempo

if [ $? = 0 ]; then
   echo "OK"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

grep "Unspecified proxy version, settling on Globus version: 2" $tempo

if [ $? = 0 ]; then
   echo "OK"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi
grep "Number of bits in key :512" $tempo

if [ $? = 0 ]; then
   echo "OK"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi


echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
echo "</pre>"
exit $SAME_OK

