#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: List members of group                                            #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - User certificate file path                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#       - user certificate                                                                  #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-listMembers:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"
echo "User=$USER_subject"
echo "<br>"

echo "SCENARIO: VO empty"
echo "<br>"
echo "List non existing members of non existing group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create new group"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host  create-group "/"$vo_name"/"$GROUP
echo "List non existing members of group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-members "/"$vo_name"/"$GROUP 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr
grep "No users are returned" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create users"
echo "<br>"
user1="DN_USER1"
user2="DN_USER2"
user3="DN_USER3"
user4="DN_USER4"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user2" "$CA" "CN-User2" "user2@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user3" "$CA" "CN-User3" "user3@cern.ch"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user4" "$CA" "CN-User4" "user4@cern.ch"
echo "Add members to group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"
echo "List members of group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host list-members "/"$vo_name"/"$GROUP > $voms_tmp

grep "$user1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
   echo "Error creating user $user1"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
   echo "Error creating user $user2"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user3" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
   echo "Error creating user $user3"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$user4" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user2" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user3" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user4" "$CA"
   voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
   echo "Error creating user $user4"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi


echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user1 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user2 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user3 "$CA"
voms-admin --vo=$vo_name -h $voms_host remove-member "/"$vo_name"/"$GROUP --nousercert $user4 "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user1 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user2 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user3 "$CA"
voms-admin --vo=$vo_name -h  $voms_host delete-user -nousercert $user4 "$CA"
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
