#!/bin/bash
# Date: 06/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Create Attribute for VO                                               #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                       #
#       - VO host name                                                                      #
#       - Attribute                                                                              #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
###########################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-crAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "Attribute value=$ATTVALUE"
echo "Attribute description=$ATTDESC"
echo "<br>"

USER_SUBJECT=$(openssl x509 -in $USER -noout -subject | sed -e 's/^subject=[ ]*//')
USER_ISSUER=$(openssl x509 -in $USER -noout -issuer | sed -e 's/^issuer=[ ]*//')

echo "SCENARIO: Attribute doesn't exist"
echo "<br>"
echo "Create new Attribute"
echo "<br>"

# TO DO:  Add checks for missing description or unique. Add unique tests.

#voms-admin --vo=$vo_name --host $voms_host create-attribute "$ATTRIBUTE" 2> $voms_stderr 
#grep "No description for attribute" $voms_stderr > /dev/null

#if [ $? == 1 ]; then
#    echo "Incorrect error message:"
#    echo "<br>"
#    cat $voms_stderr
#    echo "<br>"
#    echo "Test has failed"
#    echo "<br>"
#    exit $SAME_ERROR
#fi

voms-admin --vo=$vo_name --host $voms_host create-attribute-class "$ATTRIBUTE" "$ATTDESC" 0

voms-admin --vo=$vo_name --host $voms_host list-attribute-classes > $voms_tmp
echo "Check created attribute"
grep "$ATTRIBUTE" $voms_tmp   > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
    echo "Error creating the attribute"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

grep "$ATTDESC" $voms_tmp   > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
    echo "Error creating the description of attribute"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"
echo "<br>"
echo "SCENARIO 2: Attribute already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host create-attribute-class "$ATTRIBUTE" "$ATTDESC" 0 > $voms_stderr
grep "org.glite.security.voms.admin.database.AlreadyExistsException: Attribute" $voms_stderr > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
