#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'certdir' for voms-proxy-init                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
#       - cert. directory
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="certdir"
rm -rf $voms_tmp

echo "Remove directory $cert_dir"
rm -rf $cert_dir/*
rmdir $cert_dir 2> /dev/null

date
echo "VOMS-PROXY-INIT: check option - $OPTION"
echo "Create directory: $cert_dir"
mkdir $cert_dir

echo "Copy user certificate and key into new directory $cert_dir"
cp $USERCERT $cert_dir/usercert.pem
cp $USERKEY $cert_dir/userkey.pem

echo "1. Create new user and proxy"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
voms-proxy-init -voms $vo_name -userconf $VOMSES -$OPTION $cert_dir -pwstdin < $PWS

if [ $? = 0 ]; then
   echo "Test is OK"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   rm -rf $voms_tmp
   rm -rf $cert_dir/*
   rmdir $cert_dir
   exit $SAME_ERROR
fi

echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "2.3. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    rm -rf $voms_tmp
    rm -rf $cert_dir/*
    rmdir $cert_dir
    exit $SAME_ERROR
fi
echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
rm -rf $voms_tmp
rm -rf $cert_dir/*
rmdir $cert_dir

exit $SAME_OK                  

echo "/pre"


