#!/bin/bash
# Date: 09/11/2006                                                                          #
# Revised: March 2008                                                                       #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Delete Attribute for VO                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                       #
#       - VO host name                                                                      #
#       - file config_file (Attribute)                                                      #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-delAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"

USER_SUBJECT=$(openssl x509 -in $USER -noout -subject | sed -e 's/^subject=[ ]*//')
USER_ISSUER=$(openssl x509 -in $USER -noout -issuer | sed -e 's/^issuer=[ ]*//')

echo "SCENARIO: Attribute doesn't exist"
echo "<br>"
echo "Delete attribute"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE > $voms_stderr
grep "org.glite.security.voms.admin.database.NoSuchAttributeException: Attribute" $voms_stderr   > /dev/null

if [ $? == 1 ]; then
   echo "Incorrect error message:"
   echo "<br>"
   cat $voms_stderr
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: Attribute already exists in the VO"
echo "<br>"
voms-admin --vo=$vo_name --host $voms_host create-attribute-class "$ATTRIBUTE" "$ATTDESC" 0
voms-admin --vo=$vo_name --host $voms_host delete-attribute-class $ATTRIBUTE
voms-admin --vo=$vo_name --host $voms_host list-attribute-classes > $voms_tmp
grep "$ATTRIBUTE" $voms_tmp > /dev/null

if [ $? == 0 ]; then
   echo "Error deleting the attribute"
   echo "<br>"
   cat $voms_tmp
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
