#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'bits' for voms-proxy-init                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file
OPTION="bits"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"

echo "1. Create new user and proxy"
voms-admin --vo=$vo_name -h $voms_host create-user $USER

echo "Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "1.1. Check 512 bits"
voms-proxy-init -voms $vo_name  -$OPTION 512 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
if [ $? = 1 ]; then
    echo "Test is failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Execute voms-proxy-info"
voms-proxy-info -all > $voms_tmp

echo "1.2. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi

echo "1.3. Check strength"
grep "strength  : 512 bits" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "OK"


echo "2. Check 1024 bits"
voms-proxy-init -voms $vo_name  -$OPTION 1024 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS

if [ $? = 1 ]; then
    echo "Test is failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "2.1. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "2.2. Check strength"
grep "strength  : 1024 bits" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "OK"

echo "3. Check 2048  bits"
voms-proxy-init -voms $vo_name  -$OPTION 2048 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
if [ $? = 1 ]; then
    echo "Test is failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "3.1. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi

echo "3.2. Check strength"
grep "strength  : 2048 bits" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "OK"

echo "4. Check 4096 bits"
voms-proxy-init -voms $vo_name  -$OPTION 4096 -vomses $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
if [ $? = 1 ]; then
   echo "Test is failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "4.1. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "4.2. Check strength"
grep "strength  : 4096 bits" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi

echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER

echo "</pre>"
exit $SAME_OK


