#!/bin/bash
# Date: 01/12/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test ACL  create entry  command (add--acl-entry) for Role        #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - groupname                                                                         #
#       - fake user certificate file path                                                   #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

date
echo "<br>"
echo "Test VOMS-crACLRole:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"
echo "fake user=$USER"
echo "<br>"

oper=( all create delete add remove set-acl get-acl set-default-acl get-default-acl list )

echo "SCENARIO: empty VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr

if [ $? == 1 ]; then
    echo "Error creating the role"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create Role <$ROLE> and add 10 ACL entries"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
for ind in 0 1 2 3 4 5 6 7 8 9
do
 OP=${oper[ind]}
 echo "Create ACL entry $OP for user for Role $ROLE"
 voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
done
voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp

user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
grep "$user_subject" $voms_tmp > $tempo

echo "Check added ACL entries"
echo "<br>"
ops=`cat $tempo | cut -d"|" -f3`
echo $ops > $tempo
for ind in 0 1 2 3 4 5 6 7 8 9
do
 OP=${oper[ind]}
 grep $OP $tempo > /dev/null

 if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
    echo "Error creating the ACL"
    echo "<br>"
    cat $tempo
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
 fi
 
done

echo "SCENARIO: Add existing ACL entry in role $ROLE"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "list" $USER 2> $voms_stderr
grep "org.glite.security.voms.service.AlreadyExists:" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
    echo "Incorrect error message"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Try to create an ACL entry for an unknown operation"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW "lllist" $USER 2> $voms_stderr
grep "Unknown operation:" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
    echo "Incorrect error message"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo "Test OK"
echo "</pre>"
exit $SAME_OK
