#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Generate grid-mapfile                                            #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - User certificate file path                                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#       - user certificate                                                                  #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

export mkgrid="/opt/edg/libexec/edg-mkgridmap"

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

date
echo "<br>"
echo "Test VOMS-genGM:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "CA1=$CA"
echo "<br>"
echo "CA2=$CA_CERN"
echo "<br>"

user1="DN_USER1"
user2="DN_USER2"

echo "SCENARIO: Create gridmap file for empty VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-users 2> $voms_stderr
grep "No users are returned" $voms_stderr

if [ $? == 1 ]; then
    echo "The VO is not empty. Test needs an empty VO"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Generate gridmap file for empty VO"
echo "<br>"
$mkgrid --conf=$GRIDMAP --output=$voms_tmp

echo "Check gridmap file"
echo "<br>"
if test -s $voms_tmp
then
   echo "gridmap file should be empty for an empty VO"
   echo "<br>"
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: Create gridmap file for one user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA" "CN-User1" "user1@cern.ch"
rm -rf $tempo
$mkgrid --conf=$GRIDMAP --output=$voms_tmp
usr=`cat $voms_tmp | cut -d" " -f1`
acc=`cat $voms_tmp | cut -d" " -f2`
grep "$user1" $voms_tmp > $tempo

if [ $? == 1 ]; then
   echo "Incorrect User DN in gridmap file"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

if [ $acc != $ACCOUNT ]; then
   echo "Incorrect user account in gridmap file"
   echo "<br>"
   echo $acc
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "SCENARIO: Create gridmap file for same user DN but different CA"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user1" "$CA_CERN" "CN-User1" "user1@cern.ch"
$mkgrid --conf=$GRIDMAP --output=$voms_tmp
lines=`grep -c "$user1" $voms_tmp` 

if [ $lines != 1 ]; then
   echo "Incorrect gridmap file"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA"
voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user1" "$CA_CERN"


UMAX=3
echo "SCENARIO: Create gridmap file for $UMAX users"
echo "<br>"
counter=0
while [ $counter -lt $UMAX ]; do
  user="DN User"$counter
  voms-admin --vo=$vo_name -h $voms_host create-user --nousercert "$user" "$CA" "CN-User1" "user1@cern.ch"
  let counter=counter+1
done

$mkgrid --conf=$GRIDMAP --output=$voms_tmp

counter=0
while [ $counter -lt $UMAX ]; do
  user="DN User"$counter
  grep "$user" $voms_tmp > /dev/null
  
  if [ $? == 1 ]; then
   echo "User DN=$user is not mapped in the gridmap file"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi
  let counter=counter+1
done

counter=0
while [ $counter -lt $UMAX ]; do
  user="DN User"$counter
  voms-admin --vo=$vo_name -h $voms_host delete-user --nousercert "$user" "$CA"
  let counter=counter+1
done

echo "Cleaning tasks"
echo "<br>"

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo "Test is OK"
echo "</pre>"
exit $SAME_OK
