#!/bin/bash
# Date: 04/04/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'noregen' for voms-proxy-init                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

function clearTask {
echo "Create normal proxy, for delete user"
voms-proxy-init -voms $vo_name -vomses $VOMSES  -cert $USERCERT -key $USERKEY -pwstdin < $PWS
echo "Delete user"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
}

OPTION="noregen"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"


echo "1. Create new user"
voms-admin --vo=$vo_name -h $voms_host create-user $USER


echo "1.1. voms-proxy-destroy"
voms-proxy-destroy

echo "1.2. Create normal VOMS proxy"
voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY  -pwstdin < $PWS
echo "voms-proxy-info:"
voms-proxy-info

echo "1.3. Create proxy with option -noregen"
voms-proxy-init -voms $vo_name -vomses $VOMSES  -valid 5:00 -noregen #cert $USERCERT -key $USERKEY -noregen #"-$OPTION #  -pwstdin < $PWS

if [ $? == 1 ]; then
    #echo "Exit code=$?"
    echo "Test has failed, exit code=1"
    clearTask
    exit $SAME_ERROR
fi

echo "voms-proxy-info:"
voms-proxy-info > $voms_tmp

echo "2. Check proxy info"
voms-proxy-info > $voms_tmp

echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "2.2. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    clearTask
    exit $SAME_ERROR
fi
echo "2.2. Check /CN=proxy/CN=proxy"

grep "/CN=proxy/CN=proxy" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    clearTask
    exit $SAME_ERROR
fi
echo "Test is OK"
clearTask

echo "</pre>"
exit $SAME_OK


