#!/bin/bash
# Date: 01/12/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test list default ACL entrys for group(get-default-acl)          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - groupname                                                                         #
#       - fake user certificate file path                                                   #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

date
echo "<br>"
echo "Test VOMS-listDefaultACL:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "group=$GROUP"
echo "<br>"
echo "fake user=$USER"
echo "<br>"

op1="list"
op2="create"
op3="delete"
allow="allow"

echo "SCENARIO: empty VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create group <$GROUP> and add 3 default ACL entries"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/"$vo_name"/"$GROUP
voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op1 $USER
voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op2 $USER
voms-admin --vo=$vo_name -h $voms_host add-default-acl-entry  "/"$vo_name"/"$GROUP $allow $op3 $USER
voms-admin --vo=$vo_name -h $voms_host get-default-acl "/"$vo_name"/"$GROUP > $voms_tmp

user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
grep "$user_subject" $voms_tmp > $tempo
echo "Check added ACL entries"
echo "<br>"
ops=`cat $tempo | cut -d"|" -f3`
echo $ops > $tempo

grep "$op1" $tempo > /dev/null

 if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Error listing the ACL"
    echo "<br>"
    cat $tempo
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
 fi

grep "$op2" $tempo > /dev/null

 if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Error listing the ACL"
    echo "<br>"
    cat $tempo
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
 fi

grep "$op3" $tempo > /dev/null

 if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Error listing the ACL"
    echo "<br>"
    cat $tempo
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
 fi

echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo "Test OK"
echo "</pre>"
exit $SAME_OK
