#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test group list command                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#                                                                                           #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "Test VOMS-listGroups:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "CA=$CA"
echo "<br>"

group1="GROUP1"
group2="GROUP2"
group3="GROUP3"
group4="GROUP4"

echo "SCENARIO: Create 4 groups: $group1, $group2, $group3, $group4"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group1"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group2"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group3"
voms-admin --vo=$vo_name -h $voms_host create-group  "/$vo_name/$group4"

echo "SCENARIO: List groups"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-groups > $voms_tmp
echo "Check groups"
echo "<br>"
grep "$group1" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group1
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group2
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group3
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group4
   echo "Error creating group $group1"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$group2" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group1
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group2
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group3
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group4
   echo "Error creating group $group2"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$group3" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group1
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group2
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group3
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group4
   echo "Error creating group $group3"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

grep "$group4" $voms_tmp > /dev/null

if [ $? == 1 ]; then
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group1
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group2
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group3
   voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group4
   echo "Error creating group $group4"
   echo "<br>"
   cat $voms_tmp
   echo "Test has failed"
   echo "<br>"
   exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group1
voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group2
voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group3
voms-admin --vo=$vo_name -h $voms_host delete-group $vo_name/$group4

rm -rf $voms_tmp
rm -rf $voms_stderr
echo "Test OK"
echo "</pre>"
exit $SAME_OK
