#!/bin/bash
# Date: 09/11/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Test group list of user                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - path user certificate file -  usercert.pem                                        #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr


date
echo "<br>"
echo "Test VOMS-listUserGroups:"
echo "VO=$vo_name"
echo "Group=$GROUP"
echo "User=$USER_subject"
echo "<br>"

echo "SCENARIO: VO empty"
echo "<br>"
echo "List non existing groups of non existing user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: user" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
echo "List non existing groups of user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER > $voms_tmp
mainGroup=`cat $voms_tmp`
echo "Main group: $mainGroup" 

if [ $mainGroup = "/"$vo_name ]; then
   echo "VO group is always present"
fi

echo "SCENARIO: Create new group"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host create-group "/"$vo_name"/"$GROUP
echo "Add user as member of group $GROUP"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host add-member "/"$vo_name"/"$GROUP $USER
echo "List existing group $GROUP of user"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host list-user-groups $USER > $voms_tmp
grep "$GROUP" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    voms-admin --vo=$vo_name -h $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Error when listing user groups:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Cleaning tasks"
echo "<br>"
voms-admin --vo=$vo_name  -h $voms_host delete-user $USER
voms-admin --vo=$vo_name  -h $voms_host delete-group "/"$vo_name"/"$GROUP
echo "Test OK"
exit $SAME_OK
