#!/bin/bash
# Date: 15/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove role's Attribute                                          #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group                                                                             #
#       - Role                                                                              #
#       - Attribute                                                                         #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured and empty VO                                                         #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-delRoleAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"
echo "Role=$ROLE"

echo "1. SCENARIO: VO empty"
echo "<br>"

echo "1.1.  Delete role attribute without parameters"
voms-admin --vo=$vo_name -h $voms_host  delete-role-attribute  2> $voms_stderr
grep "No group name given" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "1.2.  Delete role attribute without parameters"
voms-admin --vo=$vo_name -h $voms_host  delete-role-attribute  "/$vo_name/$GROUP" 2> $voms_stderr
grep "No role name given." $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "1.3. Remove non existing Attribute of non existing group and role without attribute"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host  delete-role-attribute "/$vo_name/$GROUP"  "Role=$ROLE"  2> $voms_stderr
grep "No attribute name specified!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"   
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

echo "1.4. Remove non existing Attribute of non existing group and role"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host  delete-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi                    



echo "2. SCENARIO: Create group"
echo "<br>Create group $GROUP"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"
echo "2.1. delete-role-attribute"
voms-admin --vo=$vo_name -h $voms_host delete-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "$/vo_name/$GROUP"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "2.2. create new Role $ROLE"
voms-admin --vo=$vo_name -h $voms_host create-role "Role=$ROLE"                            

echo "2.3. delete-role-attribute"
voms-admin --vo=$vo_name -h $voms_host delete-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: Attribute" $voms_stderr > /dev/null
if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "$/vo_name/$GROUP"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "2.4. Assign attribute '$ATTRIBUTE' to Role '$ROLE' in group '$GROUP'"	
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host set-role-attribute  "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE" "$ATTVALUE" "$ATTDESC"


echo "2.5. Check role's attribute"
voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" "Role=$ROLE" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null
if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Incorrect list message:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "<br>"
echo "2.6. Delete role attribute"

voms-admin --vo=$vo_name -h $voms_host  delete-role-attribute "/$vo_name/$GROUP" "Role=$ROLE" "$ATTRIBUTE"

echo "<br>"
echo "2.7. Check deleted role attribute"
echo "list-role-attributes"

voms-admin --vo=$vo_name -h $voms_host list-role-attributes "/$vo_name/$GROUP" "Role=$ROLE" 2> $voms_stderr

grep "No attributes are returned" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "3. Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    voms-admin --vo=$vo_name -h $voms_host delete-role "Role=$ROLE"
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK
