#!/bin/bash
# Date: 12/02/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Set Attribute to group                                           #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - Group name                                                                        #
#       - VO host name                                                                      #
#       - Attribute                                                                         #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#                                                                                           #
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr

date
echo "<br>"
echo "test VOMS-setGroupAttribute:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Attribute=$ATTRIBUTE"
echo "<br>"
echo "Attribute value=$ATTVALUE"
echo "<br>"
echo "Attribute description=$ATTDESC"
echo "<br>"
echo "Group=$GROUP"
echo "<br>"

echo "SCENARIO: VO empty"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host  set-group-attribute  2> $voms_stderr
grep "No group name given" $voms_stderr 2> /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

voms-admin --vo=$vo_name -h $voms_host  set-group-attribute "/$vo_name/$GROUP"  2> $voms_stderr
grep "No attribute name specified!" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi
echo "OK"

voms-admin --vo=$vo_name -h $voms_host  set-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: group" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message:"
    echo "<br>"
    cat $voms_stderr
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create group"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-group "/$vo_name/$GROUP"

echo "OK, assign attribte  $ATTRIBUTE, value=$ATTVALUE and description=$ATTDESC to new group $GROUP"
echo "<br>"
echo "1. set-group-attribute"
voms-admin --vo=$vo_name -h $voms_host  set-group-attribute "/$vo_name/$GROUP" "$ATTRIBUTE" "$ATTVALUE" "$ATTDESC"
echo "2. OK, list-group-attribute"
voms-admin --vo=$vo_name -h $voms_host  list-group-attributes "/$vo_name/$GROUP" > $voms_tmp

grep "$ATTRIBUTE" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    #voms-admin --vo=$vo_name -h $voms_host delete-attribute $ATTRIBUTE
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when assigning attribute to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi

grep "$ATTVALUE" $voms_tmp > /dev/null


if [ $? == 1 ]; then
    #voms-admin --vo=$vo_name -h $voms_host delete-attribute $ATTRIBUTE
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when assigning attribute to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi

grep "$ATTDESC" $voms_tmp > /dev/null

if [ $? == 1 ]; then
    #voms-admin --vo=$vo_name -h $voms_host delete-attribute $ATTRIBUTE
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"
    echo "Error when assigning attribute to group:"
    echo "<br>"
    cat $voms_tmp
    echo "Test has failed"
    echo
    exit $SAME_ERROR
fi
echo "OK"

echo "Cleaning tasks"
echo "<br>"
    #voms-admin --vo=$vo_name -h $voms_host delete-attribute $ATTRIBUTE
    voms-admin --vo=$vo_name -h $voms_host delete-group "/$vo_name/$GROUP"        
	
rm -rf $voms_tmp
rm -rf $voms_stderr

echo "Test OK"
echo "</pre>"
exit $SAME_OK

