#!/bin/bash
# Date: 21/03/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'pwstdin' for voms-proxy-init                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="pwstdin"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"
echo "VO: $vo_name"
echo "VOMS: $VOMSES"
echo "cert: $USERCERT"
echo "key: $USERKEY"
echo "PWS": $PWS"




echo "1. Create new user and proxy"
voms-admin --vo=$vo_name -h $voms_host create-user $USER
voms-proxy-init -voms $vo_name -userconf $VOMSES -cert $USERCERT -key $USERKEY -pwstdin < $PWS
voms-admin --vo=$vo_name -h voms_host list-users

if [ $? = 0 ]; then
   echo "Test is OK"
   #exit $SAME_OK
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "2.3. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
exit $SAME_OK                  

echo "/pre"


