#!/bin/bash
# Date: 04/04/2007                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: check option 'noregen' for voms-proxy-init                       #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #
#       - VO host name                                                                      #
#       - User certificate                                                                  #
# Requisites:                                                                               #
#       - VOMS server                                                                       #
#       - 1 configured VO                                                                   #
#       - user certificate                                                                  #
#       - user key                                                                          #
#       - vomses:  VOMS description                                                         # 
#                                                                                           #
#############################################################################################
#                                                                                           #
# Note on security issues: the host and user certificates used by this test are dummy ones  #
# provided by the test utils package.                                                       #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/pr_config_file

OPTION="noregen"
rm -rf $voms_tmp

echo
date
echo "VOMS-PROXY-INIT: check option - $OPTION"


echo "1. Create new user"
voms-admin --vo=$vo_name -h $voms_host create-user $USER


echo "1.1. voms-proxy-destroy"
voms-proxy-destroy

echo "1.2. Create proxy with option -noregen"
voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -noregen -pwstdin  2> $voms_tmp < $PWS
#echo "Command result:"
#cat $voms_tmp

grep "Failed to find valid user certificate!" $voms_tmp
#grep "Unable to find user certificate" $voms_tmp

if [ $? = 0 ]; then
   echo "Step  is OK"
else 
   echo "Test is failed"
   voms-admin --vo=$vo_name -h $voms_host delete-user $USER
   exit $SAME_ERROR
fi

echo "1.3. Create normal VOMS proxy"
voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -valid "11:11" -pwstdin < $PWS

echo "1.4. Create proxy with option -noregen"
voms-proxy-init -voms $vo_name -vomses $VOMSES -cert $USERCERT -key $USERKEY -$OPTION -pwstdin < $PWS


echo "2. Check proxy info"
echo "2.1.Extract by openssl from usercert.pem"
user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
echo "DN=$user_subject"

echo "2.2. Execute voms-proxy-info"
voms-proxy-info > $voms_tmp

echo "2.3. Check user DN"
grep "$user_subject" $voms_tmp

if [ $? == 1 ]; then
    echo "Test has failed"
    voms-admin --vo=$vo_name -h $voms_host delete-user $USER
    exit $SAME_ERROR
fi
echo "Test is OK"
voms-admin --vo=$vo_name -h $voms_host delete-user $USER
echo "</pre>"
exit $SAME_OK


