#!/bin/bash
# Date: 01/12/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove ACL entry of Role                                         #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - rolename                                                                          #
#       - fake user certificate file path                                                   #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

date
echo "<br>"
echo "Test VOMS-removeACLRole:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "Role=$ROLE"
echo "<br>"
echo "fake user=$USER"
echo "<br>"

echo "SCENARIO: empty VO"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: role" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Incorrect error message"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create role <$ROLE> and add ACL entry"
echo "<br>"
voms-admin --vo=$vo_name -h $voms_host create-role $ROLE
voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER 2> $voms_stderr
grep "org.glite.security.voms.service.NotInDatabase: Not in database: There is no entry in ACL for role" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
    echo "Incorrect error message"
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

voms-admin --vo=$vo_name -h $voms_host add-acl-entry  "Role=$ROLE" $ALLOW $OP $USER
voms-admin --vo=$vo_name -h $voms_host remove-acl-entry "Role=$ROLE"  $ALLOW $OP $USER

user_subject=`openssl x509 -in $USER -noout -subject | cut -d" " -f2-5`
voms-admin --vo=$vo_name -h $voms_host get-acl "Role=$ROLE" > $voms_tmp
grep "$user_subject" $voms_tmp > /dev/null

 if [ $? == 0 ]; then
    voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
    echo "Error removing the ACL"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
 fi

echo "Cleaning tasks"
echo "<br>"

voms-admin --vo=$vo_name -h $voms_host delete-role $ROLE
rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo "Test OK"
echo "</pre>"
exit $SAME_OK
