#!/bin/bash
# Date: 01/12/2006                                                                          #
# Author: Victor Galaktionov e-mail: victor.galaktionov@cern.ch                             #
# Description of the test: Remove Default ACL entry of a group                              #
#                                                                                           #
# Input Parameters:                                                                         #
#       - VO name                                                                           #                                    
#       - VO host name                                                                      #
#       - groupname                                                                         #
#       - fake user certificate file path                                                   #
# Requisites:                                                                               #
#	- VOMS server                                                                       #
#       - 1 configured VO which is empty                                                    #
#                                                                                           #
#                                                                                           #                                                               
#############################################################################################
#                                                                                           #
#                                                                                           #
#############################################################################################
echo "<pre>"
export voms_host=$1
source $SAME_SENSOR_HOME/tests/config_file

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

date
echo "<br>"
echo "Test VOMS-removeDefaultACL:"
echo "<br>"
echo "VO=$vo_name"
echo "<br>"
echo "group=$GROUP"
echo "<br>"
echo "fake user=$USER"
echo "<br>"

# Discover the subject of the user running the tests using the proxy
EXEC_USER_SUBJECT=$(voms-proxy-info -identity -dont-verify-ac)
if [ $? == 1 ]; then
    echo "Cannot discover the subject of the user running the test. voms-proxy-info returned an error.Skipping the test."
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test was skipped"
    echo "<br>"
    exit $SAME_ERROR
fi

# Discover the issuer for this user (this user should be granted ALL rights for the top group)
voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name > $voms_tmp
if [ $? == 1 ]; then
    echo "Cannot fetch ACL for top group. Skipping test."
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test was skipped"
    echo "<br>"
    exit $SAME_ERROR
fi

EXEC_USER_ISSUER=$(grep "$EXEC_USER_SUBJECT" $voms_tmp | head -1 | cut -f 2 -d ',' | cut -f 1 -d ')')
if [ -z "$EXEC_USER_ISSUER" ]; then
    echo "Cannot find the CA subject. Skipping the test."
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test was skipped"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "Starting the test..."
echo "Executed by: $EXEC_USER_SUBJECT, $EXEC_USER_ISSUER"

echo "SCENARIO: Try to remove an ACL entry for a non-existent group (empty VO)"
echo "<br>"

voms-admin --vo=$vo_name --host $voms_host remove-default-ACL-entry "/"$vo_name"/"$GROUP $USER > $voms_stderr
grep "org.glite.security.voms.admin.database.NoSuchGroupException" $voms_stderr > /dev/null

if [ $? == 1 ]; then
    echo "Unexpected error when trying to remove a default ACL entry for a non-existent group."
    echo "<br>"
    cat $voms_stderr
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "SCENARIO: Create a group /$vo_name/$GROUP, setup a default ACL and test removal effect."
echo "<br>"

voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP

voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "$EXEC_USER_SUBJECT" "$EXEC_USER_ISSUER" ALL

ACE_RIGHTS=( CONTAINER_READ MEMBERSHIP_READ ACL_READ REQUESTS_READ ATTRIBUTES_READ CONTAINER_WRITE MEMBERSHIP_WRITE ACL_WRITE REQUESTS_WRITE ATTRIBUTES_WRITE ACL_DEFAULT CONTAINER_READ)

COUNTER=0
while [ $COUNTER -lt 11 ]; do
   voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER" ${ACE_RIGHTS[COUNTER]}
   COUNTER=$[$COUNTER+1]
done

COUNTER=100
while [ $COUNTER -lt 111 ]; do
   voms-admin --vo=$vo_name --host $voms_host --nousercert add-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER" ${ACE_RIGHTS[COUNTER-100]}
   COUNTER=$[$COUNTER+1]
done

echo "Create subgroup that should inherit all ACEs"
voms-admin --vo=$vo_name --host $voms_host create-group "/"$vo_name"/"$GROUP"/"del_test_group

echo "<BR>Checking default ACL count for parent"
voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_tmp
if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then 
    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Missing default ACL entry for the parent"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "<BR>Checking ACL count for del_test_group"
voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP"/"del_test_group > $voms_tmp
if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then
    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
    voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
    echo "Missing ACL entry for the subgroup immediately after creation"
    echo "<br>"
    cat $voms_tmp
    echo "<br>"
    echo "Test has failed"
    echo "<br>"
    exit $SAME_ERROR
fi

echo "<BR>Start removing entries from the Default ACL of the parent"

COUNTER=0
while [ $COUNTER -lt 11 ]; do

  voms-admin --vo=$vo_name --host $voms_host --nousercert remove-default-ACL-entry "/"$vo_name"/"$GROUP "/C=CH/O=CERN/OU=GD/CN=Fake user $COUNTER" "$EXEC_USER_ISSUER"
  voms-admin --vo=$vo_name --host $voms_host get-default-ACL "/"$vo_name"/"$GROUP > $voms_tmp

  if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne $[23-$COUNTER-1] ]; then
      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
      echo "Missing default ACL entry for the parent"
      echo "<br>"
      cat $voms_tmp
      echo "<br>"
      echo "Test has failed"
      echo "<br>"
      exit $SAME_ERROR
  fi

  voms-admin --vo=$vo_name --host $voms_host get-ACL "/"$vo_name"/"$GROUP"/"del_test_group > $voms_tmp
  if [ $(wc -l $voms_tmp | cut -f 1 -d " ") -ne 23 ]; then
      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
      voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP
      echo "Missing ACL entry for the subgroup immediately after creation"
      echo "<br>"
      cat $voms_tmp
      echo "<br>"
      echo "Test has failed"
      echo "<br>"
      exit $SAME_ERROR
  fi

  COUNTER=$[$COUNTER+1]
done

echo "Cleaning tasks."
echo "<br>"

voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP"/"del_test_group
voms-admin --vo=$vo_name --host $voms_host delete-group "/"$vo_name"/"$GROUP

rm -rf $voms_tmp
rm -rf $voms_stderr
rm -rf $tempo

echo "Test OK"
echo "</pre>"
exit $SAME_OK

