#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Dimitar Shiyachki <Dimitar.Shiyachki@cern.ch>
#
##############################################################################


dpns-ping
if [ $? -ne 0 ]; then
   echo "dpns-ping exited with error"
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

dpns-ping -h $DPNS_HOST
if [ $? -ne 0 ]; then
   echo "dpns-ping -h <hostname> exited with error"
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

dpns-ping -h non-existing-host.non-existing-domain.non-existing-tld
if [ $? -ne 1 ]; then
   echo "dpns-ping against non-existing host did not exit with error "
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

echo
echo "OVERALL RESULT: SUCCESS"
exit 0

