#!/bin/bash
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Dimitar Shiyachki <Dimitar.Shiyachki@cern.ch>
#
##############################################################################

dpm_exec ()
{
   ssh root@"$DPNS_HOST" "$1"
}

echo "Pinging $DPNS_HOST"
dpns-ping -h $DPNS_HOST
if [ $? -ne 0 ]; then
   echo "$DPNS_HOST is already down. Test failed."
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

echo "Shutting down"
dpm_exec "/opt/lcg/bin/dpns-shutdown -h $DPNS_HOST"
ret=$?
if [ $ret -ne 0 ]; then
   echo "dpns-shutown exited with code $ret"
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

echo "Pinging $DPNS_HOST"
dpns-ping -h $DPNS_HOST
if [ $? -eq 1 ]; then
   echo "Server was shut down successfully"
else
   echo "Server still running. Shutdown unsuccessfull."
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

echo "Starting server back up."
dpm_exec "/sbin/service dpnsdaemon start"
if [ $? -ne 0 ]; then
   echo "Error starting up the DPNS daemon."
   echo "OVERALL RESULT: FAILURE"
   exit 1
fi

echo
echo "OVERALL RESULT: SUCCESS"
exit 0

