#!/bin/sh
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Alejandro Alvarez Ayllon, CERN
# LINK:    https://savannah.cern.ch/bugs/?31012
#
##############################################################################

log() {
  echo "`date`: $1"
}

test_bug31012_pre () {
# Check for variables that are needed in test_bug1 and which should be defined globally in
# the *sh that is sourced in regTest
# Return REGTEST_FAIL if something is not O.K. otherwise return $REGTEST_OK
  return $REGTEST_OK
}
                                                                                                                      
test_bug31012_post () {
  echo
  # Cleanup after running test_bug1. Unset all variables that were set in test_bug
  # Delete files created during the test run.
  cd - >/dev/null
  return $REGTEST_OK  
}


test_bug31012 () {
  # Main test
  # Return values REGTEST_FAIL, REGTEST_TIMEOUT or REGTEST_OK

  app_path=`pwd`

  sanity_check() { # 1 - test_dir  2 - wms.conf
    bad=0
    if [ -z $1 ]; then
      bad=1
    else
      if [ -z $2 ]; then
        bad=1
      fi
    fi
    if [ $bad -eq 1 ]; then
      echo "usage: testplan_list test_dir wms.conf"
      return 1
    fi
    if [ -r "$app_path/config/testplan_functions" ]; then
      . $app_path/config/testplan_functions
    else
      echo "File testplan_functions not found. Quitting.."
      return 1
    fi
    return 0
  }
                                                                                                                   
  sanity_check $1 $2
  if [ $? -eq 0 ]; then
	  report_name="$app_path/reports/report31012.html"
	  rm -rf $report_name
          report_header "Test results: WMS Client does not print properly WMProxy server version"  $report_name
	  cd $1

    # Call glite-wms-job-submit with --debug and --version
    output=`glite-wms-job-submit --debug --version --config $app_path/$2`

    # Get printed version
    printedVersion=`echo $output | grep "Version successfully retrieved" | cut -d ':' -f 5 | sed "s/ //g"`

    # Get debug version
    debugVersion=`echo $output | grep "WMProxy Version" | cut -d ':' -f 2 | sed "s/ //g"`

    # Compare
    if [ ! $printedVersion == $debugVersion ]; then
      log "The obtained version and the notified one do not match"
      report_line "" "The obtained version and the notified one do not match" $report_name
      return $REGTEST_FAIL
    else
      log "The obtained version and the notified one match"
      report_line "" "The obtained version and the notified one match" $report_name
      return $REGTEST_OK
    fi
  fi
}

