#!/bin/bash

siteName=$1
nodeName=$2
inMaintenance=$3
#echo "SAME_SENSOR_WORK=$SAME_SENSOR_WORK"
envName=`cat $SAME_SENSOR_WORK/envName`
realLFCserver="lxb1941.cern.ch"

if [ "x$1" == "x--publish" ] ; then
    shift    
    echo "$nodeName: published" >&2
else
    echo "check-LFC - started"                # my insert
    #echo "$nodeName: started" >&2
    mkdir -p $SAME_SENSOR_WORK/nodes/$nodeName
    cd $SAME_SENSOR_WORK/nodes/$nodeName
    rm -f *.result
    count=0
    for test in `cat $SAME_SENSOR_HOME/test-sequence.lst` ; do
	#echo
	#date
	let count=count+1
        #echo "$count	check-LFC: $test,	nodename: $nodeName,	VO: $SAME_VO"
        same-run-test -v $SAME_VO -t $test -n $nodeName -e $envName -d $SAME_SENSOR_HOME/tests $nodeName > $test.result
        ret=$?
        retcode="FAILED"
        #echo "Retcode=$ret"
        if [ $ret == $SAME_OK ]; then
           retcode="OK"
           #echo "Test is OK"
        #else
        #   echo "Test is failed"
        fi
        echo "$count	check-LFC: $test,	nodename: $nodeName,	VO: $SAME_VO"	==$retcode
        #echo "<<<<<<<<<<<<<<<<<<<<<"
        #cat $test.result
        #echo ">>>>>>>>>>>>>>>>>>>>>"
    done
    echo "$nodeName: publishing" >&2
    same-publish-tuples TestData *.result >&2
    echo "$nodeName: finished" >&2
fi

