#!/bin/bash

#------  Testbed servers  -----------------
export SE=lxbra1910.cern.ch
export LCG_GFAL_INFOSYS=lxbra2305.cern.ch:2170
export LFC_HOST="lxb7608v3.cern.ch"
#The hostname of the LCG File Catalog


#VO name
export VO="dteam"

export STATE_OK=0
export STATE_WARNING=1
export STATE_CRITICAL=2
export STATE_UNKNOWN=3

#----- for compatibale for sAM tests -----
export SAME_VO=$VO
export vo_name=$VO
export SAME_OK=$STATE_OK
export SAME_ERROR=$STATE_CRITICAL

#----  working directory in LFC
export D_LFC=/grid/$VO/nagios/LFC
export LFCDIR=/grid/$VO/nagios/LFC/$LFC_HOST

#----- Check all access (pointed in var MODE)
export SHORT=1                  # Check short access: 000, 777
#export MODE=8                  # Check all var acesses: 000 - 777, 512 variants . Running very long time (1 hour)
export MODE=4                   # Check acesss: 000 - 222 (--- -wx-wx-wx )
export DMAX=5                   # check deletion subdirectories (DMAX chaines)

#--------- temporary files ---------------
export lfc_tmp=/tmp/$LFC_HOST.lfc_tmp
export lfc_stderr=/tmp/$LFC_HOST.lfc_stderr
export tempo=/tmp/$LFC_HOST.lfc_tempo

#------ Tests to be executed {yes|no}
export CLI="no"
export API_PYTHON="no"
export UI="no"
SEQUENCE="no"

