#!/bin/sh
#****** SRMv2/SRMv2-put
# NAME
# SRMv2-put - Copy a local file to the SRM into default space area(s).
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2008-07-18
#
# LANGUAGE
#
# bash
#
# SOURCE

nodeName=$1

. config.sh

fn_uniq="$(date '+%Y%m%d-%H%M%S')-$(uuidgen|cut -d'-' -f5)"
VO=$SAME_VO
RETCODE=$SAME_OK
FILE_OUT=/tmp/testFile.txt
echo "this is a test file" > $FILE_OUT

do_cleanup() {
    return 0
}

echo_config

check_dep_comm

if [ -s $FILE_ENDPNT ] ; then
    echo "Testing SRMv2 endpoint "
    #port=`cat $FILE_ENDPNT | cut -d : -f3 | cut -d / -f1`
    #srmv2=srm://$nodeName:$port/srm/managerv2
    srmv2=srm://$(cat $FILE_ENDPNT|head -1|sed -e 's|^.*://||')
    echo "<pre>$srmv2</pre>"
else
    no_srmv2_endpoint
fi

echo "<p>"
echo "Using lcg-utils version:"
echo "<p>"
echo "<pre>"
set -x
lcg-cp --version
set +x
echo "</pre>"

rm -f $FILE_SURL

if [ -s $FILE_SAPATH ] ; then
    # we may have more than one SAPath
    while read SAPATH ; do
        echo "<p>"
        echo "Testing storage space in path:"
        echo "</p>"
        echo "<pre>"
        echo $SAPATH
        echo "</pre>"
        SURL=$srmv2?SFN=$SAPATH/testfile-cp-${fn_uniq}.txt
        echo "<p>"
        echo "Testing with SURL:"
        echo "</p>"
        echo "<pre>"
        echo $SURL
        echo "</pre>"
        echo "<i>*** Copy local file to storage ***</i>"
        echo "<p>"
        echo "<pre>"
        echo "$(date -u) [$(date +%s)]"
        set -x
        lcg-cp $LCG_UTIL_TIMEOUT -b --vo ${VO} -D srmv2 -U srmv2 -v file:${FILE_OUT} ${SURL}
        retcode=$?
        set +x
        echo "$(date -u) [$(date +%s)]"
        echo "</pre>"
        if [ $retcode -ne 0 ] ; then
            echo "<p>"
            echo "<font color='#cc0000'><b>ERROR</b></font>: <b>lcg-cp</b> failed with exit status: $retcode"
            echo "</p>"
            # HACK:
            # Sometimes zero size files are left on SEs when lcg-cp to SEs fails. Just try to delete the file.
            lcg-del -t 10 -b -l -D srmv2 -T srmv2 --vo ${VO} ${SURL} > /dev/null 2>&1
            #
            if [ ${RETCODE} -lt $SAME_ERROR ] ; then
                RETCODE=$SAME_ERROR
            fi
            continue
        else
            echo "<p>"
            echo "<b>OK</b>: File ${SURL} copied successfully."
            echo "</p>"
        fi

        echo "$SAPATH $SURL" >> $FILE_SURL
    done < $FILE_SAPATH
else
     echo "<pre>"
     echo "<font color='#cc0000'><b>WARNING</b></font>: Default storage path not defined"
     echo "</pre>"
     RETCODE=$SAME_WARNING
fi

echo "<p>Test status: <b>${RET_CODES[${RETCODE}]}</b></p>"

do_cleanup
exit ${RETCODE}

#****
