#!/bin/sh
#****** SRMv2/SRMv2-ls-dir
# NAME
# SRMv2-ls-dir - List content of VO's top level space area(s) in SRM.
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2008-06-30
#
# LANGUAGE
#
# bash
#
# SOURCE

nodeName=$1

. config.sh

VO=$SAME_VO
RETCODE=$SAME_OK

do_cleanup() {
    return 0
}

echo_config

check_dep_comm

if [ -s $FILE_ENDPNT ] ; then
    echo $FILE_ENDPNT
    echo "Testing SRMv2 endpoint"
    #port=`cat $FILE_ENDPNT | cut -d : -f3 | cut -d / -f1`
    #srmv2=srm://$nodeName:$port/srm/managerv2
    srmv2=srm://$(cat $FILE_ENDPNT|head -1|sed -e 's|^.*://||')
    echo "<pre>$srmv2</pre>"
else
    no_srmv2_endpoint
fi

echo "<p>"
echo "Using lcg-utils version:"
echo "<p>"
echo "<pre>"
set -x
lcg-ls --version
set +x
echo "</pre>"

if [ -s $FILE_SAPATH ] ; then
    # we may have more than one SAPath
    while read SAPATH ; do
        echo "<p>"
        echo "Testing storage space in path:"
        echo "</p>"
        echo "<pre>"
        echo $SAPATH
        echo "</pre>"
        SURL=$srmv2?SFN=$SAPATH
        echo "<p>"
        echo "SURL of the directory to test:"
        echo "</p>"
        echo "<pre>"
        echo $SURL
        echo "</pre>"
        echo "<i>*** List storage area path ***</i>"        
        echo "<p>"
        echo "<pre>"
        echo "$(date -u) [$(date +%s)]"        
        set -x
        lcg-ls $LCG_UTIL_TIMEOUT -b -T srmv2 -l -d ${SURL}
        retcode=$?
        set +x
        echo "$(date -u) [$(date +%s)]"        
        echo "</pre>"
        if [ $retcode -ne 0 ] ; then
            echo "<p>"
            echo "<font color='#cc0000'><b>ERROR</b></font>: <b>lcg-ls</b> failed with exit status: $retcode"
            echo "</p>"
            if [ ${RETCODE} -lt $SAME_ERROR ] ; then
                RETCODE=$SAME_ERROR
            fi
            continue
        else
            echo "<p>"
            echo "<b>OK</b>: Storage area ${SURL} was listed successfully."
            echo "</p>"
        fi
    done < $FILE_SAPATH
else
     echo "<pre>"
     echo "<font color='#cc0000'><b>WARNING</b></font>: Default storage path not defined"
     echo "</pre>"
     RETCODE=$SAME_WARNING
fi

echo "<p>Test status: <b>${RET_CODES[${RETCODE}]}</b></p>"

do_cleanup
exit ${RETCODE}

#****
