#ifndef EDG_WORKLOAD_COMMON_CONFIGURATION_CWRAPPER_H
#define EDG_WORKLOAD_COMMON_CONFIGURATION_CWRAPPER_H

#include "initializer.h"

/* Tmpl: wrap class CommonConfiguration */
/* Tmpl: wrap class JCConfiguration */
/* Tmpl: wrap class LMConfiguration */
/* Tmpl: wrap class NSConfiguration */
/* Tmpl: wrap class WMConfiguration */

#endif /* EDG_WORKLOAD_COMMON_CONFIGURATION_CWRAPPER_H */

// Local Variables:
// mode: c
// End:
