#ifndef GLITE_WMS_COMMON_CONFIGURATION_CWRAPPER_H
#define GLITE_WMS_COMMON_CONFIGURATION_CWRAPPER_H

#include "glite/wms/common/configuration/initializer.h"

/* Tmpl: wrap class CommonConfiguration */
/* Tmpl: wrap class JCConfiguration */
/* Tmpl: wrap class LMConfiguration */
/* Tmpl: wrap class NSConfiguration */
/* Tmpl: wrap class WMConfiguration */
/* Tmpl: wrap class WMPConfiguration */
/* Tmpl: wrap class ICEConfiguration *

#endif /* GLITE_WMS_COMMON_CONFIGURATION_CWRAPPER_H */

// Local Variables:
// mode: c
// End:
