#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHORS: Victor Galaktionov, JINR/CERN 
##############################################################################

#Script for testing FTS channel add operation



#source functions definitions
source FTS-common
source FTS-V-common

echo "1) Test if channel exists"

is-channel-exists $NEW_CHANNEL
if [ $? != 0 ]; then
    echo "Drop nonexisting channel"
    channel-drop $NEW_CHANNEL
    if [ $? == 0 ]; then
	echo "Noncorrect operation"
	exit 1
    fi
    grep "does not exist" message
    if [ $? != 0 ]; then
	echo " Noncorrect operation"
	exit 1
    fi
    echo "OK"
    echo "Channel not exists, create it"
 
    SITE_A="CERN-TB-CERN"
    SITE_B="CINPCERTTB"

    echo "Add new channel"
    simple-channel-add $NEW_CHANNEL $SITE_A $SITE_B
    if [ $? != 0 ]; then
	echo "Add channel - failed"
	exit 1
    fi
fi        
echo "OK"

echo "Drop channel"
channel-drop $NEW_CHANNEL
if [ $? != 0 ]; then
    echo "Drop channel - failed"
    exit 1
fi        
echo "OK"

echo "Drop special parameters"
special-check-channel-drop $NEW_CHANNEL
if [ $? != 0 ]; then
    echo "Special Drop channel - failed"
    exit 1
fi        

echo "-TEST PASSED-"
exit 0
