#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHORS: Victor Galaktionov, JINR/CERN 
##############################################################################

#source functions definitions
source FTS-common

#Script for testing FTS channel add operation

showUsage()
{
 echo "Usage: FTS-channel-setvolimit --fts <fts hostname> --channel <channel name>"
 echo "Options: "
 echo "          --fts  <fts hostname> "
 echo "                   The name of the FTS host."
 echo "          --channel  <channel name> "
 echo "                   The channel to use for submitting a file transfer"
}

# FTS_HOST must be set.
# Added by Victor Galaktionov 24/11/209
function channel-setvolimit()
{
    echo "channel-setvolimit($1, $2, $3 $4)"
    echo "1. glite-transfer-channel-setvolimit  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2 $3"
    glite-transfer-channel-setvolimit --verbose  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2 $3 2> message
    if [ $? == 0 ]; then
    echo "setvolimit channel command - failed, MUST BE diagnose - not shared VO"
    return 1
    fi
    grep "VO does not have a share defined for this channel" message
    if [ $? != 0 ]; then
        echo "Not correct performs glite-transfer-channel-setvolimit"
        cat message
        return 1
    fi
    echo "Temporary skip setvoshare operation"
    echo "OK, define shared VO for this channel $1"
#  
#    echo "2. glite-transfer-channel-setvoshare  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2 $4"
#    glite-transfer-channel-setvoshare  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2 $4
#    if [ $? != 0 ]; then
#        echo "Not correct performs glite-transfer-channel-setvoshare"
#   return 1
#    fi
#
#  echo "Set VO share - OK"
#  echo "3. Again glite-transfer-channel-setvolimit  -q -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement  $1 $2 $3"
#  glite-transfer-channel-setvolimit  -q -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2 $3
#  if [ $? != 0 ]; then
#    echo "setvolimit channel command - failed"
#    return 1
#  fi

    echo "OK, check special parameters"

    echo "4. glite-transfer-channel-setvolimit  -h"
    glite-transfer-channel-setvolimit  -h > /dev/null
    if [ $? != 0 ]; then
    echo "glite-transfer-channel-setvolimit -h - failure"
    return 1
    fi

    echo "5. glite-transfer-channel-setvolimit  -V"
    glite-transfer-channel-setvolimit  -V
    if [ $? != 0 ]; then
    echo "glite-transfer-channel-setvolimit -V - failure"
    return 1
    fi

    echo "6. glite-transfer-channel-list -q"
    glite-transfer-channel-list -q
    if [ $? != 0 ]; then
        echo "glite-transfer-channel-list -q  - failure"
        return 1
    fi

    return 0
}


if [ $# -ne 4 ];then
  showUsage
  echo
  echo "-TEST FAILED-"
  exit 2
fi

until [ -z "$1" ] 
do
  case "$1" in
     --fts) 
           if [ -z "$2" ]; then
                shift 1 
           else
                FTS_HOST=$2
                shift 2
           fi
     ;;
     --channel)
           if [ -z "$2" ]; then
                shift 1
           else
                CHANNEL=$2
                shift 2
           fi
     ;;
          *)
           showUsage
           exit 2
    ;;
  esac
done

#0.1) Check for valid proxy
if [ $FTS_HOST != "localhost" ]; then
  ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
  ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

  if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
           echo ""
           echo "Using proxy from: $X509_USER_PROXY"
  else
           echo ""
           echo ">>> NOTE: Valid proxy is needed for this test!"
           echo ""
           if [ $ProxyExpired -gt 0 ]; then
              echo ">>> NOTE: Proxy credential expired!"
           fi
           echo "-TEST FAILED-"
           exit 1
  fi
fi

echo "1. Test if channel exists"

channel-exists $CHANNEL
if [ $? != 0 ]; then
    echo "Channel not exists, create it"
 
    SITE_A="CERN-TB-CERN"
    SITE_B="SINPCERTTB"

    echo "Add new channel"
    simple-channel-add $CHANNEL $SITE_A $SITE_B
    if [ $? != 0 ]; then
	echo "Add channel - failed"
	exit 1
    fi
fi        
echo "OK"

LIMIT=33
SHARE=43
echo "Set VO limit for  channel $CHANNEL"
channel-setvolimit $CHANNEL $VO_NAME $LIMIT $SHARE
if [ $? != 0 ]; then
    echo "setvolimit channel - failed"
    channel-drop $CHANNEL
    exit 1
fi        
echo "OK"

channel-drop $CHANNEL
if [ $? != 0 ]; then
    echo "Channel dropped bad"
    exit 1
fi

echo "-TEST PASSED-"
exit 0
