#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Alejandro Álvarez Ayllón, CERN
#
##############################################################################

# Script for testing corrupted submissions

#source functions definitions
source FTS-common

#Script for testing FTS file transfer submission

showUsage()
{
 echo "Usage: FTS-corrupt --fts <fts hostname> --channel <channel name>"
 echo "Options: "
 echo "          --fts  <fts hostname> "
 echo "                   The name of the FTS host."
 echo "          --channel  <channel name> "
 echo "                   The channel to use for submitting a file transfer"
 echo "          --bdii  <bdii hostname> "
 echo "                   The top-level BDII hostname"
 echo "          --vo  <VO name> "
 echo "                   VO name"
 echo "          --timeout  <timeout> "
 echo "                   timeout in seconds"
 echo "          --gsiftp   [yes|no]"
 echo "                   If set to 'yes', GSIFTP URLs will be used"
 echo "                   (Optional. Default value: No)"
}

until [ -z "$1" ] 
do
  case "$1" in
     --fts)
           if [ -z "$2" ]; then
                shift 1
           else
                FTS_HOST=$2
                shift 2
           fi
     ;;
     --channel)
           if [ -z "$2" ]; then
                shift 1
           else
                CHANNEL=$2
                shift 2
           fi
     ;;
     --bdii)
           if [ -z "$2" ]; then
                shift 1
           else
                BDII_HOST=$2
                shift 2
           fi
     ;;
     --vo)
           if [ -z "$2" ]; then
                shift 1
           else
                VO_NAME=$2
                shift 2
           fi
     ;;
     --timeout)
           if [ -z "$2" ]; then
                shift 1
           else
                TIMEOUT=$2
                shift 2
           fi
     ;;
     --gsiftp)
           if [ -z "$2" ]; then
                shift 1
           else
                GSIFTP_URL=$2
                shift 2
           fi
     ;;
          *)
           showUsage
           exit 2
    ;;
  esac
done

if [ -z "$GSIFTP_URL" ]; then
    GSIFTP_URL="no"
fi

# Check parameters
if [ -z "$FTS_HOST" ]; then
	echo "The FTS host is mandatory"
	exit 1
fi

if [ -z "$CHANNEL" ]; then
	echo "The channel name is mandatory"
	exit 1
fi

if [ -z "$VO_NAME" ]; then
	echo "The VO name is mandatory"
	exit 1
fi

#0.1) Check for valid proxy
ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
         echo ""
         echo "Using proxy from: $X509_USER_PROXY"
else
         echo ""
         echo ">>> NOTE: Valid proxy is needed for this test!"
         echo ""
         if [ $ProxyExpired -gt 0 ]; then
            echo ">>> NOTE: Proxy credential expired!"
         fi
         echo "-TEST FAILED-"
         exit 1
fi

#0.5) Compile, if neccessary, the file corrupt.c
if [ -f corrupt/corrupt ]; then
	echo "The corrupt binary is already present. Using it..."
else
	echo "The corrupt binary is not present. Compiling..."
	pushd corrupt
	make
	if [ $? -ne 0 ]; then
		echo "The corrupt binary could not be compiled"
		exit 1
	fi
	popd
fi

#1) Test if channel exists

#Get Channels list
echo
echo "Retrieving channels list..."
get_channels
if [ "x$Channel_List" == "x" ]; then
  echo "No channels retrieved"
  exit 1
fi

found=0
for Channel in $Channel_List
do
  if [ "$Channel" == "$CHANNEL" ];then 
    echo "Channel exists"
    found=1
    break
  fi
done

if [ $found -eq 0 ];then
  echo "Channel $CHANNEL does not exist"
  echo "-TEST FAILED-"
  exit 1
fi

#2) Check that the channel is active
echo
echo "Checking that $CHANNEL is active..."
is_channel_active $CHANNEL
if [ $? -eq 0 ];then
  echo "Channel $CHANNEL is Active"
else
  echo "Channel $CHANNEL is not Active"
  echo "-TEST FAILED-"
  exit 1
fi


#3) Retrieve SEs from source and destination site
echo
echo "Retrieving SEs info from source and destination sites in $CHANNEL..."

#3.a) Retrieve source and destination sites
get_source_dest_from_channel $CHANNEL
if [ $? -eq 1 ];then
  echo "Failing retrieving source and destination sites"
  echo "-TEST FAILED-"
  exit 1
fi

echo "Source: $Source_Site"
echo "Dest: $Destin_Site"

#3.b) Retrieve good SEs from source and destination sites
get_good_se_from_site $Source_Site
get_def_se_from_site $Source_Site
if [ $? -eq 1 ];then
  echo "Failing retrieving default SE from site $Source_Site"
  exit 1
fi
if [ "x$SE_HOST" != "x" ]; then
  SE_SOURCE=$SE_HOST
  echo "SE_source: $SE_SOURCE"
else
  echo "Failing retrieving default SE from site $Source_Site"
  echo "-TEST FAILED-"
  exit 1
fi


#get_good_se_from_site $Destin_Site
if [ "$Destin_Site" == "$Source_Site" ]; then
  #Select an SE different than SE_SOURCE
  get_def_se_from_site $Destin_Site $SE_SOURCE
else
  get_def_se_from_site $Destin_Site
fi
if [ $? -eq 1 ];then
  echo "Failing retrieving default SE from site $Destin_Site"
  echo "-TEST FAILED-"
  exit 1
fi
if [ "x$SE_HOST" != "x" ]; then
  SE_DEST=$SE_HOST
  echo "SE_dest: $SE_DEST"
else
  echo "Failing retrieving default SE from site $Source_Site"
  echo "-TEST FAILED-"
  exit 1
fi


#3.c) Retrieve SEs path to use for file transfer
get_se_path $SE_SOURCE
if [ $? -eq 1 ];then
  echo "Failing retrieving SAPATH from SE $SE_SOURCE"
  echo "-TEST FAILED-"
  exit 1
fi
if [ "x$SE_SRM_LOC" != "x" ]; then
  SOURCE_SAPATH=$SE_SRM_LOC
  echo "SAPATH_source: $SOURCE_SAPATH"
else
  echo "Failing retrieving SAPATH from SE $SE_SOURCE"
  echo "-TEST FAILED-"
  exit 1
fi


get_se_path $SE_DEST
if [ $? -eq 1 ];then
  echo "Failing retrieving SAPATH from SE $SE_DEST"
  echo "-TEST FAILED-"
  exit 1
fi
if [ "x$SE_SRM_LOC" != "x" ]; then
  DEST_SAPATH=$SE_SRM_LOC
  echo "SAPATH_destination: $DEST_SAPATH"
else
  echo "Failing retrieving SAPATH from SE $SE_SOURCE"
  echo "-TEST FAILED-"
  exit 1
fi

# Submission

SUB_FILE_LOC="$HOME/fts-submission-file"
RESULT_FILE="$HOME/fts-test-results"

DATE=`date | awk '{print $2"_"$3"_"$4}' | sed -e 's/://g'`
TMP_FILE="/tmp/FTS_Test_$DATE"
TEST_FILE_NAME="FTS_Test_$DATE"
ALGO="CRC32"

echo "Creating 10MB local temporary test file for transfer" 

echo "" > $TMP_FILE

dd if=/dev/zero of=$TMP_FILE bs=10MB count=1 2>/dev/null

echo "Using the 10MB temporary test file: $TMP_FILE" 
echo "Copy and register the test file $TMP_FILE on: $SOURCE_SAPATH using $ALGO checksum" 

GUID=`lcg-cr --checksum --checksum-type $ALGO --vo $VO_NAME -d $SOURCE_SAPATH/$TEST_FILE_NAME file://$TMP_FILE 2>message`

result=`cat message | wc -l`

if [ $result -gt 0 ]; then
  echo ">>> NOTE: `cat message`"
  echo ">>> NOTE: lcg-cr command for SRM: $SOURCE_SAPATH failed!"
  exit 1
fi
echo "Removing the 10MB temporary test file: $TMP_FILE"
rm -rf $TMP_FILE

echo "Retrieving the SURL for guid: $GUID"
SURL=`lcg-lr $GUID`

# Get the path without the srm://host
FILE_PATH=`echo $SURL | sed s/srm:\\\\/\\\\/$SE_SOURCE//`

./corrupt/corrupt --verbose $FILE_PATH

# Continue
if [ "x$OPTION" == "x" ]; then
  echo "Retrieving the checksum for $SURL"
  CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk '{print $1}'`
  echo "Creating the submission file with $ALGO:$CHECKSUM in $SUB_FILE_LOC"
  i=0
  echo "" > $SUB_FILE_LOC

  # Process the destination and source URLs depending on
  # the GSIFTP_URL environment variable
  if [ "x$GSIFTP_URL" = "xyes" ]; then
      get_gsiftp_urls "$SOURCE_SAPATH/$TEST_FILE_NAME" "$DEST_SAPATH/$TEST_FILE_NAME$i"
      if [ ! $? -eq 0 ]; then
          echo "get_gsiftp_urls error!"
          exit 1
      fi
      echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
  else
      echo "$SOURCE_SAPATH/$TEST_FILE_NAME $DEST_SAPATH/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
  fi

  echo "Submitting the transfer"  
  echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer -f $SUB_FILE_LOC" 
  SUBID=`glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer -f $SUB_FILE_LOC`
  if [ -z "$SUBID" ]; then
     echo "Job submition failed!"
     exit 1
  fi
elif [ "x$BOTH" == "x" ]; then
  echo "Creating the submission file in $SUB_FILE_LOC"
  i=0
  echo "" > $SUB_FILE_LOC

  # Process the destination and source URLs depending on
  # the GSIFTP_URL environment variable
  if [ "x$GSIFTP_URL" = "xyes" ]; then
      get_gsiftp_urls "$SOURCE_SAPATH/$TEST_FILE_NAME" "$DEST_SAPATH/$TEST_FILE_NAME$i"
      if [ ! $? -eq 0 ]; then
          echo "get_gsiftp_urls error!"
          exit 1
      fi
      echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION" >> $SUB_FILE_LOC
  else
      echo "$SOURCE_SAPATH/$TEST_FILE_NAME $DEST_SAPATH/$TEST_FILE_NAME$i" >> $SUB_FILE_LOC
  fi
  
  echo "Submitting the transfer with $OPTION"  
  echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC" 
  SUBID=`glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC`
  if [ -z "$SUBID" ]; then
     echo "Job submition failed!"
     exit 1
  fi
else
  echo "Retrieving the checksum for $SURL"
  CHECKSUM=`lcg-get-checksum --checksum-type $ALGO $SURL | awk "$AWK_PARAMETER"`
  echo "Creating the submission file with $ALGO:$CHECKSUM in $SUB_FILE_LOC"
  i=0
  echo "" > $SUB_FILE_LOC


  # Process the destination and source URLs depending on
  # the GSIFTP_URL environment variable
  if [ "x$GSIFTP_URL" = "xyes" ]; then
      get_gsiftp_urls "$SOURCE_SAPATH/$TEST_FILE_NAME" "$DEST_SAPATH/$TEST_FILE_NAME$i"
      if [ ! $? -eq 0 ]; then
          echo "get_gsiftp_urls error!"
          exit 1
      fi
      echo "$GSIFTP_SOURCE $GSIFTP_DESTINATION $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
  else
      echo "$SOURCE_SAPATH/$TEST_FILE_NAME $DEST_SAPATH/$TEST_FILE_NAME$i $ALGO:$CHECKSUM" >> $SUB_FILE_LOC
  fi

  echo "Submitting the transfer with $OPTION"  
  echo "glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC" 
  SUBID=`glite-transfer-submit -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $OPTION -f $SUB_FILE_LOC`
  if [ -z "$SUBID" ]; then
     echo "Job submition failed!"
     exit 1
  fi

fi

echo "Job successfully submited"
echo "Transfer ID: $SUBID. " 

#5) Poll for results with timeout
echo
echo "Retrieving the job status..."
#Hardcoded timeout
#TIMEOUT=100
poll_status_with_timeout $SUBID $TIMEOUT
return=$?

if [ "$return" -eq 1 ];then
  echo "Failing retrieving the job status"
  echo "-TEST FAILED-"
  exit 1
elif [ "$return" -eq 2 ];then
  echo "Failing retrieving the job status"
  echo "-TEST FAILED-"
  exit 1
elif [ "$return" -eq 3 ];then
  echo "Job failed"
  echo "-TEST FAILED-"
  exit 1
elif [ "$return" -eq 4 ];then
  echo "Timeout exceeded"
  echo "-TEST FAILED-"
  exit 1
elif [ "$return" -gt 4 ];then
  echo "return code unknown $?"
  echo "-TEST FAILED-"
  exit 1
fi

#6) The source file must exists
lcg-ls $SOURCE_SAPATH/$TEST_FILE_NAME &> /dev/null
if [ $? -ne 0 ]; then
	echo "The source file has been removed!!"
	echo "-TEST FAILED-"
	exit 1
else
	echo "The source file is still there"
fi

#7) The destination file shouldn't be there
lcg-ls $DEST_SAPATH/$TEST_FILE_NAME$i &> /dev/null
if [ $? -eq 0 ]; then
	echo "The destination file is still there"
	echo "-TEST FAILED-"
	exit 1
else
	echo "The destination file has been removed"
fi

echo "-TEST PASSED-"
exit 0

