#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHOR: Victor Galaktionov, JINR/CERN 
##############################################################################

#Script for testing FTS channel add operation


VO_NAME=$1


#source functions definitions
source FTS-common
source FTS-V-common

#0.1) Check for valid proxy
ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
         echo ""
         echo "Using proxy from: $X509_USER_PROXY"
else
         echo ""
         echo ">>> NOTE: Valid proxy is needed for this test!"
         echo ""
         if [ $ProxyExpired -gt 0 ]; then
            echo ">>> NOTE: Proxy credential expired!"
         fi
         echo "-TEST FAILED-"
         exit 1
fi

echo "Set user DN"
echo ""
USERDN=`glite-voms-proxy-info -identity`
echo "User DN: $USERDN"


echo "Check list-vomanagers"
list-vomanagers $VO_NAME
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi
echo "OK"

echo "Check add-vomanager"
add-vomanager $VO_NAME "$USERDN"
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi
echo "OK"

#echo "Again check list-vomanagers"
#list-vomanagers $VO_NAME
#if [ $? != 0 ]; then
#    echo "list-vomanagers - failed"
#    exit 1
#fi
#echo "OK"

echo "Check remove-vomanagers"
remove-vomanager  $VO_NAME "$USERDN"
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi

echo "Check special parameters fo vomanagers"
special-check-vomanagers
if [ $? != 0 ]; then
    echo "vomanagers - failed"
    exit 1
fi
echo "OK"

exit 0