#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHOR: Victor Galaktionov, JINR/CERN 
##############################################################################

#source functions definitions
source FTS-common

#Script for testing FTS channel add operation

showUsage()
{
 echo "Usage: FTS-vomanagers --fts <fts hostname> --channel <channel name>"
 echo "Options: "
 echo "          --fts  <fts hostname> "
 echo "                   The name of the FTS host."
 echo "          --channel  <channel name> "
 echo "                   The channel to use for submitting a file transfer"
 echo "          --bdii  <bdii hostname> "
 echo "                   The top-level BDII hostname"
 echo "          --vo  <VO name> "
 echo "                   VO name"
 echo "          --timeout  <timeout> "
 echo "                   timeout in seconds"
}

function list-vomanagers()
{
    echo "list-vomanagers($1)"
    glite-transfer-listvomanagers  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1
    if [ $? != 0 ]; then
    echo "listvomanager - failed"
    return 1
    fi
    return 0
}

# Added by Victor Galaktionov 04/12/2009
function add-vomanager()
{
    echo "add-vomanager($1, $2)"
    glite-transfer-addvomanager  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1 "$2"
    if [ $? != 0 ]; then
    echo "addvomanager - failed"
    return 1
    fi
    echo "Again add manager"
    glite-transfer-addvomanager  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1 "$2"
    if [ $? == 0 ]; then
    echo "addvomanager - failed"
    return 1
    fi
    echo "Check added manager"    
    glite-transfer-listvomanagers  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1 > message
    grep "$2" message
    if [ $? != 0 ]; then
    echo "addvomanager - failed"
    return 1
    fi

    return 0
}

# Added by Victor Galaktionov 04/12/2009
function remove-vomanager()
{
    echo "remove-vomanagers($1, $2)"
    echo "Remove nonexisting manager in VO"
    glite-transfer-removevomanager  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1 "bla-bla" 2>message
    ret=$?
    #echo "Ret=$ret"

    grep "No such principal on VO" message
    if [ $? != 0 ]; then
    echo "Removevomanager - failed"
    return 1
    fi

    if [ $ret == 0 ]; then
    echo "removevomanager - failed"
    return 1
    fi

    echo "Remove real manager"
    glite-transfer-removevomanager  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1 "$2"
    if [ $? != 0 ]; then
    echo "removevomanager - failed"
    return 1
    fi
    echo "OK"
    glite-transfer-listvomanagers  -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/FileTransfer $1

    return 0
}

function special-check-vomanagers()
{
    echo "1.1. glite-transfer-addvomanager  -h"
    glite-transfer-addvomanager  -h > /dev/null
    if [ $? != 0 ]; then
    echo "glite-transfer-addvomanager -h - failure"
    return 1
    fi

    echo "1.2. glite-transfer-addvomanager  -V"
    glite-transfer-addvomanager  -V
    if [ $? != 0 ]; then
    echo "glite-transfer-addvomanager -V - failure"
    return 1
    fi

    echo "1.3. glite-transfer-addvomanager  -q"
    glite-transfer-addvomanager  -q
    if [ $? == 0 ]; then
    echo "glite-transfer-addvomanager -q - failure"
    return 1
    fi


    echo "2.1. glite-transfer-removevomanager  -h"
    glite-transfer-removevomanager  -h > /dev/null
    if [ $? != 0 ]; then
    echo "glite-transfer-removevomanager -h - failure"
    return 1
    fi

    echo "2.2. glite-transfer-removevomanager  -V"
    glite-transfer-addvomanager  -V
    if [ $? != 0 ]; then
    echo "glite-transfer-removevomanager -V - failure"
    return 1
    fi
    echo "2.3. glite-transfer-removevomanager  -q"
    glite-transfer-removevomanager  -q
    if [ $? == 0 ]; then
    echo "glite-transfer-removevomanager -q - failure"
    return 1
    fi

    echo "3.1. glite-transfer-listvomanagers  -h"
    glite-transfer-listvomanagers  -h > /dev/null
    if [ $? != 0 ]; then
    echo "glite-transfer-listvomanagers -h - failure"
    return 1
    fi

    echo "3.2. glite-transfer-listvomanagers  -V"
    glite-transfer-addvomanager  -V
    if [ $? != 0 ]; then
    echo "glite-transfer-listvomanagers -V - failure"
    return 1
    fi

    echo "3.3. glite-transfer-addvomanager  -q"
    glite-transfer-addvomanager  -q
    if [ $? == 0 ]; then
    echo "glite-transfer-addvomanager -q - failure"
    return 1
    fi
    return 0
}


if [ $# -lt 4 ];then
  showUsage
  echo
  echo "-TEST FAILED-"
  exit 2
fi

until [ -z "$1" ]  
do
  case "$1" in
     --fts)
           if [ -z "$2" ]; then
                shift 1
           else
                FTS_HOST=$2
                shift 2
           fi
     ;;
     --channel)
           if [ -z "$2" ]; then
                shift 1
           else
                CHANNEL=$2
                shift 2
           fi
     ;;
     --vo)
	  if [ -z "$2" ]; then
                shift 1
          else
                VO_NAME=$2
	        shift 2
          fi
     ;;
      *)
	 shift 1
    ;;
  esac
done


#0.1) Check for valid proxy
if [ $FTS_HOST != "localhost" ]; then
  ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
  ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

  if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
           echo ""
           echo "Using proxy from: $X509_USER_PROXY"
  else
           echo ""
           echo ">>> NOTE: Valid proxy is needed for this test!"
           echo ""
           if [ $ProxyExpired -gt 0 ]; then
              echo ">>> NOTE: Proxy credential expired!"
           fi
           echo "-TEST FAILED-"
           exit 1
  fi
fi

echo "Set user DN"
echo ""
USERDN=`glite-voms-proxy-info -identity`
echo "User DN: $USERDN"


echo "Check list-vomanagers"
list-vomanagers $VO_NAME
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi
echo "OK"

echo "Check add-vomanager"
add-vomanager $VO_NAME "$USERDN"
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi
echo "OK"

#echo "Again check list-vomanagers"
#list-vomanagers $VO_NAME
#if [ $? != 0 ]; then
#    echo "list-vomanagers - failed"
#    exit 1
#fi
#echo "OK"

echo "Check remove-vomanagers"
remove-vomanager  $VO_NAME "$USERDN"
if [ $? != 0 ]; then
    echo "list-vomanagers - failed"
    exit 1
fi

echo "Check special parameters fo vomanagers"
special-check-vomanagers
if [ $? != 0 ]; then
    echo "vomanagers - failed"
    exit 1
fi
echo "OK"

exit 0
