#!/bin/bash

##########################################################################################
# Script for testing of FTS services (Basic test: PING, FTS BDII, Top Level BDII, Tomcat)#
##########################################################################################
#                                                       #
# Returned values:                                      #
#                                                       #
#                 Exit  0: Test Passed                  #
#                 Exit  1: Test Failed                  #
#                 Exit  2: Wrong Input                  #
#                                                       #
#########################################################


source ./FTS-common

showUsage ()
{
 echo "Usage:  FTS-basic --fts <fts hostname> [ --bdii <bdii hostname> ] [ --shortinfo] [--longinfo ] "
 echo "Options:    "
 echo "	 obligatory:    								"
 echo "	         --fts   <fts  hostname>				"
 echo "		         The name of the FTS server.		"
 echo "	 optional:									  "
 echo "	         --bdii  <bdii hostname>  				"
 echo "		          The name of the top level BDII. The default is $BDII_HOST "
}

if [ -z "$1" ]; then
  showUsage
  echo
  echo "-TEST FAILED-"
  exit 2
fi

until [ -z "$1" ]
do
  case "$1" in
   
     --fts)
      if [ -z "$2" ]; then
        shift 1
 	  else
        FTS_HOST=$2
        shift 2
      fi
    ;;

    --bdii)
	   if [ -z "$2" ]; then
           shift 1 
 	   else
	       BDII_HOST=$2
 	       shift 2
           fi
    ;;
    --shortinfo )
      echo "FTS basic services availability"
      exit 0
    ;;
    --longinfo )
      echo "FTS basic services availability:"
      echo "  - ping FTS server"
      echo "  - basic ldap query to FTS BDII"
      echo "  - basic ldap query to site/top leavel BDII"
      echo "  - nmap query to check if Tomcart port is open"
      exit 0
    ;;
    *)
        showUsage
        exit 2
    ;;
  esac	
done

if [ -z "$FTS_HOST" ]; then
    echo ""
    echo "FTS hostname is not specified. Option --fts <fts hostname> is obligatory!"
    showUsage
    exit 2
fi

if [ -z "$BDII_HOST" ]; then
    echo ""
    echo "BDII hostname is not specified. Use --bdii <bdii hostname> or \$BDII_HOST"
    showUsage
    exit 2
fi

#################################################################################
# >>>> NOTE:  Hardcoded ports for FTS BDII site/top level BDII and Tomcat!!! <<<<
#################################################################################

BDII_PORT=2170
FTS_BDII_PORT=2170
FTS_TOMCAT_PORT=8443

#####################
# Exporting variables
#####################

export LCG_GFAL_INFOSYS=$BDII_HOST:$BDII_PORT
export GLITE_SD_PLUGIN=bdii

######################
# Function definition
######################

function test_ping
{
  echo " Testing ping to $FTS_HOST" 
  run_command "ping -c 5 $FTS_HOST 2>/dev/null | grep Unreachable | wc -l" || return 1
  return 0
}

function test_ldap
{
  echo " Testing connection to LDAP server on $FTS_HOST"
  run_command "ldapsearch -x -H ldap://$FTS_HOST:$FTS_BDII_PORT -b Mds-vo-name=resource,o=Grid 2>/dev/null | tail -n 6 | grep Success | wc -l" || return 1
  return 0
}

function test_bdii
{
  echo " Testing if there is information for $FTS_HOST on $BDII_HOST"
  run_command "ldapsearch -x -H ldap://$BDII_HOST:$BDII_PORT -b Mds-vo-name=local,o=Grid 2>/dev/null | grep $FTS_HOST | wc -l" || return 1
  return 0
}

function test_tomcat
{
  echo " Testing connection to Tomcat server on $FTS_HOST "
  run_command "nmap -p $1 $FTS_HOST 2>/dev/null | grep open | wc -l" || return 1
  return 0
}

################
# Start testing
###############

echo ""
echo "Testing FTS: $FTS_HOST"
echo ""
echo "Using BDII: $BDII_HOST"
echo ""
echo "Testing...."

###########################################
# Checking if the service is up and running
###########################################

run_function test_ping

#####################################################
# Checking if LDAP Server on FTS is working properely
#####################################################

run_function test_ldap

########################################################################
# Checking if there is information for FTS Server on site/top level BDII
########################################################################

run_function test_bdii

#####################################################################
# Getting Tomcart Port for FTS Server from top level BDII: $BDII_HOST
#####################################################################

#DO NOT USE THE BDII DURING PATCH CERTIFICATION UNTIL AN EFFICIENT WAY
#TO UPDATE THE BDII IS FOUND
#FTS_URL=`glite-sd-query -t org.glite.FileTransfer 2>/dev/null | grep $FTS_HOST | grep Endpoint | sed -e 's/Endpoint://g'`
#FTS_URL=`echo $FTS_URL | awk '{print $1}' | sed -e 's/https:\/\///g' | sed 's/\// /g' | awk '{print $1}' | sed -e 's/:/ /g'`
#FTS_TOMCAT_PORT=`echo $FTS_URL | awk '{print $2}'`

#FTS PORT HARDCODED
FTS_TOMCAT_PORT=8443

#######################################################
# Checking if Tomcat Server on FTS is working properely
#######################################################

run_function test_tomcat $FTS_TOMCAT_PORT

echo ""
echo "FTS basic service availability: Passed"
echo ""
exit 0


