#!/bin/bash 
    
##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
#
# AUTHORS: Gianni Pucciani, CERN
#
##############################################################################

#
# This script just does a simple transfer submission without checking
# the status of the transfer
#

#source functions definitions
source FTS-common
source ../FTS-certconfig

#0.1) Check for valid proxy
ProxyExist=`voms-proxy-info 2>/dev/null | grep timeleft | wc -l`
ProxyExpired=`voms-proxy-info 2>/dev/null | grep  "timeleft  : 0:00:00" | wc -l`

if [ $ProxyExist -gt 0 -a $ProxyExpired -eq 0 ]; then
         echo ""
         echo "Using proxy from: $X509_USER_PROXY"
else
         echo ""
         echo ">>> NOTE: Valid proxy is needed for this test!"
         echo ""
         if [ $ProxyExpired -gt 0 ]; then
            echo ">>> NOTE: Proxy credential expired!"
         fi
         echo "-TEST FAILED-"
         exit 1
fi

#Retrieve SEs from source and destination site
echo
echo "Retrieving SEs info from source and destination sites in $CHANNEL..."

#Retrieve source and destination sites
get_source_dest_from_channel $CHANNEL
if [ $? = 1 ];then
  echo "Failing retrieving source and destination sites"
  echo "-TEST FAILED-"
  exit 1
fi

echo "Source: $Source_Site"
echo "Dest: $Destin_Site"

#Retrieve good SEs from source and destination sites
#get_good_se_from_site $Source_Site
get_def_se_from_site $Source_Site
if [ $? = 1 ];then
  echo "Failing retrieving good SE from site $Source_Site"
  echo "-TEST FAILED-"
  exit 1
fi
SE_SOURCE=$SE_HOST
echo "SE_source: $SE_SOURCE"

#get_good_se_from_site $Destin_Site
get_def_se_from_site $Destin_Site
if [ $? = 1 ];then
  echo "Failing retrieving good SE from site $Destin_Site"
  echo "-TEST FAILED-"
  exit 1
fi
SE_DEST=$SE_HOST
echo "SE_dest: $SE_DEST"

#Retrieve SEs path to use for file transfer
export VO_NAME=$VO
get_se_path $SE_SOURCE
if [ $? = 1 ];then
  echo "Failing retrieving SAPATH from SE $SE_SOURCE"
  echo "-TEST FAILED-"
  exit 1
fi
SOURCE_SAPATH=$SE_SRM_LOC
echo "SAPATH_source: $SOURCE_SAPATH"

get_se_path $SE_DEST
if [ $? = 1 ];then
  echo "Failing retrieving SAPATH from SE $SE_DEST"
  echo "-TEST FAILED-"
  exit 1
fi
DEST_SAPATH=$SE_SRM_LOC
echo "SAPATH_destination: $DEST_SAPATH"

#Submitting a file transfer
echo
echo "Submitting a file transfer job..."
FILE_SIZE=10
file_transfer_skip_tape $SOURCE_SAPATH $DEST_SAPATH $FILE_SIZE

if [ $? = 1 ];then
  echo "Failing submitting a job"
  echo "-TEST FAILED-"
  exit 1
fi

echo "-TEST PASSED-"
exit 0

