#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHOR: Victor Galaktionov, JINR/CERN 
##############################################################################

#Script for testing FTS channel manager  operations

#source functions definitions
source FTS-common
source FTS-V-common


echo " Test if channel exists"

is-channel-exists $NEW_CHANNEL

if [ $? != 0 ]; then
    echo "Channel is not exists, create it"
    BANDWIDTH=100
    CONTACT="vgalakti@cern.ch"
    STATE="Stopped"
    STREAMS=5
    FILES=10
    SITE_A="CERN-TB-CERN"
    SITE_B="SINPCERTTB"

    echo "Add new channel"
    simple-channel-add $NEW_CHANNEL  $SITE_A $SITE_B
#    channel-add $NEW_CHANNEL $BANDWIDTH $CONTACT $STATE $STREAMS $FILES $SITE_A $SITE_B
    if [ $? != 0 ]; then
	echo "Add channel - failed"
	exit 1
    fi        
fi

echo "Add new channel manager"
echo "Set user DN"
echo ""
USERDN=`glite-voms-proxy-info -identity`
echo "User DN: $USERDN"
        
echo "1. Add manager"
channel-addmanager $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
   echo "channel-addmanager - failed"
   exit 1
fi
echo "OK"

echo "2. list channel managers"
channel-listmanagers $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
    echo "channel-listmanagers - failed"
    exit 1
fi
echo "OK"

echo "3. Remove channel manager"
channel-removemanager $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
    echo "channel-removemanager - failed"
fi
echo "OK"

channel-drop $NEW_CHANNEL
if [ $? != 0 ]; then
    echo "Not dropped channel"
    exit 1
fi
echo "OK"

exit 0