#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHOR: Victor Galaktionov, JINR/CERN 
##############################################################################

#Script for testing FTS channel add operation

showUsage()
{
 echo "Usage: FTS-channel-managers --fts <fts hostname> --channel <channel name>"
 echo "Options: "
 echo "          --fts  <fts hostname> "
 echo "                   The name of the FTS host."
 echo "          --channel  <channel name> "
 echo "                   The channel to use for submitting a file transfer"
 echo "          --bdii  <bdii hostname> "
 echo "                   The top-level BDII hostname"
 echo "          --vo  <VO name> "
 echo "                   VO name"
 echo "          --timeout  <timeout> "
 echo "                   timeout in seconds"
}

# FTS_HOST must be set.
# Added by Victor Galaktionov 24/11/209
function channel-addmanager()
{   
    echo "channel-addmanager($1, $2)"
    echo "Add manager for nonexisting channel"
    glite-transfer-channel-addmanager --verbose -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement "NOCHANNEL" "$2" 2> message
    if [ $? == 0 ]; then
    echo "Channel-addmanager - failed"
    return 1
    fi
    grep "does not exist" message
    if [ $? != 0 ]; then
        echo "Channel-addmanager - failed"
        return 1
    fi
     
    echo "Add manager for existing channel"
    echo "glite-transfer-channel-addmanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2"
    glite-transfer-channel-addmanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 "$2"
    if [ $? != 0 ]; then
    echo "Channel-addmanager - failed"
    return 1
    fi

    echo "Again add the same manager"
    echo "glite-transfer-channel-addmanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 $2"
    glite-transfer-channel-addmanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 "$2" #2> message
    if [ $? == 0 ]; then
    echo "Channel-addmanager - failed"
    cat message
    return 1
    fi
    cat message
    echo "OK"
    echo "Check special parameters"
    echo "glite-transfer-channel-addmanager -h"
    glite-transfer-channel-addmanager -h > /dev/null

    if [ $? != 0 ]; then
    echo "Channel-addmanager - failed"
    return 1
    fi

    echo "glite-transfer-channel-addmanager -V"
    glite-transfer-channel-addmanager -V
    if [ $? != 0 ]; then
    echo "Channel-addmanager - failed"
    return 1
    fi

    echo "glite-transfer-channel-addmanager -q"
    glite-transfer-channel-addmanager -q
    if [ $? == 0 ]; then
    echo "Channel-addmanager - failed"
    return 1
    fi
    return 0
}

# FTS_HOST must be set.
# Added by Victor Galaktionov 24/11/209
function channel-listmanagers()
{
    echo "channel-listmanagers($1, $2)"
    echo "List managers"
    echo "glite-transfer-channel-listmanagers -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1"
    glite-transfer-channel-listmanagers -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 > message
    if [ $? != 0 ]; then
    echo "Channel-listmanagers - failed"
    return 1
    fi
    cat message

    echo "Check special parameters"
    echo "glite-transfer-channel-listmanagers -h"
    glite-transfer-channel-listmanagers -h
    if [ $? != 0 ]; then
    echo "Channel-listmanagers - failed"
    return 1
    fi

    echo "glite-transfer-channel-listmanagers -V"
    glite-transfer-channel-listmanagers -V
    if [ $? != 0 ]; then
    echo "Channel-listmanagers - failed"
    return 1
    fi

    echo "glite-transfer-channel-listmanagers -q"
    glite-transfer-channel-listmanagers -q
    if [ $? == 0 ]; then
    echo "Channel-listmanagers - failed"
    return 1
    fi
    return 0

}

# FTS_HOST must be set.
# Added by Victor Galaktionov 24/11/209
function channel-removemanager()
{
    echo "channel-removemanager($1, $2)"
    echo "Remove nonexisting manager"
    echo "glite-transfer-channel-removemanager -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 'bla-bla-bla'"
    glite-transfer-channel-removemanager -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 "bla-bla-bla" 2> message
    if [ $? == 0 ]; then
    echo "Channel-removemanager - failed"
    return 1
    fi
    #cat message
    grep "No such principal on channel" message
    if [ $? != 0 ]; then
    echo "Channel-removemanager - failed"
    return 1
    fi
    echo "OK"

    echo "2. Remove real manager"
    echo "glite-transfer-channel-removemanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 '$2'"
    glite-transfer-channel-removemanager -v -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 "$2" 2> message
    if [ $? != 0 ]; then
    echo "Channel-removemanager - failed"
    cat message
    return 1
    fi
    echo "OK"
    echo "Check removed manager"
    echo "glite-transfer-channel-listmanagers -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1"
    glite-transfer-channel-listmanagers -s https://$FTS_HOST:8443/glite-data-transfer-fts/services/ChannelManagement $1 > message
    if [ $? != 0 ]; then
    echo "Channel-listmanagers - failed"
    return 1
    fi
    grep "$2" message
    if [ $? == 0 ]; then
    echo "Manager not removed"
    cat message
    return 1
    fi

    echo "Check special parameters"
    echo "glite-transfer-channel-removemanager -h"
    glite-transfer-channel-removemanager -h
    if [ $? != 0 ]; then
    echo "Channel-removemanager - failed"
    return 1
    fi

    echo "glite-transfer-channel-removemanager -V"
    glite-transfer-channel-removemanager -V
    if [ $? != 0 ]; then
    echo "Channel-removemanager - failed"
    return 1
    fi

    echo "glite-transfer-channel-listmanager -q"
    glite-transfer-channel-removemanager -q
    if [ $? == 0 ]; then
    echo "Channel-removemanager - failed"
    return 1
    fi
    return 0
}


if [ $# -ne 10 ];then
  showUsage
  echo
  echo "-TEST FAILED-"
  exit 2
fi

until [ -z "$1" ] 
do
  case "$1" in
     --fts)
           if [ -z "$2" ]; then
                shift 1
           else
                FTS_HOST=$2
                shift 2
           fi
     ;;
     --channel)
           if [ -z "$2" ]; then
                shift 1
           else
                CHANNEL=$2
                shift 2
           fi
     ;;
     --bdii)
           if [ -z "$2" ]; then
                shift 1
           else
                BDII_HOST=$2
                shift 2
           fi
     ;;
     --vo)
           if [ -z "$2" ]; then
                shift 1
           else
                VO_NAME=$2
                shift 2
           fi
     ;;
     --timeout)
           if [ -z "$2" ]; then
                shift 1
           else
                TIMEOUT=$2
                shift 2
           fi
     ;;
          *)
           showUsage
           exit 2
    ;;
  esac
done

#source functions definitions
source FTS-common
#source FTS-V-common


echo " Test if channel exists"

channel-exists $CHANNEL

if [ $? != 0 ]; then
    echo "Channel is not exists, create it"
    BANDWIDTH=100
    CONTACT="vgalakti@cern.ch"
    STATE="Stopped"
    STREAMS=5
    FILES=10
    SITE_A="CERN-TB-CERN"
    SITE_B="SINPCERTTB"
    THROUGHPUT="10"    

    echo "Add new channel"
    channel-add $CHANNEL $BANDWIDTH $CONTACT $STATE $STREAMS $FILES $THROUGHPUT $SITE_A $SITE_B
    if [ $? != 0 ]; then
	echo "Add channel - failed"
	exit 1
    fi        
fi

echo "Add new channel manager"
echo "Set user DN"
echo ""
MYUSERDN=`glite-voms-proxy-info -identity`
#Modify it to avoid duplication error
USERDN="test"

echo "User DN: $MYUSERDN"
echo "manager DN: $USERDN"
        
echo "1. Add manager"
channel-addmanager $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
   echo "channel-addmanager - failed"
   exit 1
fi
echo "OK"

echo "2. list channel managers"
channel-listmanagers $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
    echo "channel-listmanagers - failed"
    exit 1
fi
echo "OK"

echo "3. Remove channel manager"
channel-removemanager $NEW_CHANNEL "$USERDN"
if [ $? != 0 ]; then
    echo "channel-removemanager - failed"
fi
echo "OK"

channel-drop $NEW_CHANNEL
if [ $? != 0 ]; then
    echo "Not dropped channel"
    exit 1
fi
echo "OK"

exit 0
