#!/bin/bash

##############################################################################
# Copyright (c) Members of the EGEE Collaboration. 2004.
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
# 18.11.2009
# AUTHORS: Victor Galaktionov, JINR/CERN 
# Script based on Gianni Pucciani script FTS-submission
#
##############################################################################

#Script for testing FTS file transfer submission


CHANNEL=$1

#source functions definitions
source FTS-common
source FTS-V-common



#1) Test if channel exists

#Get Channels list
echo
echo "Retrieving channels list..."
get_channels
echo "List=$Channel_List"
if [ "x$Channel_List" == "x" ]; then
  echo "No channels retrieved"
  exit 1
fi

found=0
for Channel in $Channel_List
do
  if [ "$Channel" == "$CHANNEL" ];then 
    echo "Channel exists"
    found=1
    break
  fi
done

if [ $found -eq 0 ];then
  echo "Channel $CHANNEL does not exist"
  echo "-TEST FAILED-"
  exit 1
fi

#2) Check that the channel is active
echo
echo "Checking that $CHANNEL is active..."
is_channel_active $CHANNEL
if [ $? -eq 0 ];then
  echo "Channel $CHANNEL is Active"
else
  echo "Channel $CHANNEL is not Active"
  echo "-TEST FAILED-"
  exit 1
fi


echo "Check special parameters "
special-check-channel-list $CHANNEL
if [ $? != 0 ]; then
   echo "-TEST FAILED-"
   exit 1
fi

echo "-TEST PASSED-"
exit 0
