#!/usr/bin/python

import os, os.path
import sys
import re, string
from CREAMTestUtils import testsuite_utils, job_utils, job_poller

from CREAMTestUtils.submit_pool import JobSubmitterPool

def failure(reason):
    print reason
    sys.exit(1)

class JobProcessed(job_utils.JobProcessed):
    
    badStatusList = ['ABORTED', 'CANCELLED']
    
    def __init__(self):
        job_utils.JobProcessed.__init__(self)
        
    def canPurge(self, jobStatus, failureReason=''):
        return not jobStatus in JobProcessed.badStatusList
    
class JobPoller(job_poller.JobPoller):
    
    def __init__(self, parameters, pManager=None):
        job_poller.JobPoller.__init__(self, parameters, pManager)
        self.finishedJobs = JobProcessed()
        
    def shutdown(self):
        job_poller.JobPoller.shutdown(self)
        if self.tableOfResults['ABORTED']>0 or self.tableOfResults['CANCELLED']>0:
            return 1
        return 0
    
def main():
    
    parameters = testsuite_utils.Parameters(\
                                            'submit a sequence of jobs and enable the lease renew process',\
                                            '[OPTION] -R | --resourceURI RESOURCEURI',\
                                            '''Submit a given number of jobs registering using either one lease
for all jobs or one lease per job; \
the expiring lease is renewed so the job must not be cancelled by the service. \
The status of the job is retrieved using the GetStatus command.\
The test keeps a given number of job running on the CE.''')
    
    parameters.register('rate', 'd', 30, testsuite_utils.checkRate, descr='''\
set the sleep time in seconds between two polling operations \
(DEFAULT 30s, Min 5s)''')
    
    parameters.register('numberOfJob', 'd', 1, testsuite_utils.atLeastOne, descr='''\
set the number of jobs to submit (DEFAULT 1)''')
    
    parameters.register('maxRunningJobs', 'd', 100, testsuite_utils.atLeastOne, descr='''\
set the max number of job which can be enqueued in the service (DEFAULT 100)''')
    
    parameters.register('delegationType', 's', 'single', testsuite_utils.checkRenewType,\
                        'D', descr='''\
specify the delegation management type: single, one delegated proxy for all submissions,\
or multiple, one delegated proxy per job (DEFAULT is single)''')
    
    parameters.register('leaseType', 's', 'single', testsuite_utils.checkRenewType, \
                        'L', descr='''specify the lease management type: single, \
one lease for all submissions, or multiple, one lease per job (DEFAULT is single)''')
    
    parameters.register('leaseTime', 'd', 1200, optChar='W', descr='''\
define the lease time for a lease, if it is not used a pre-registered lease id \
(DEFAULT 20m)''')
    
    parameters.register('resourceURI', 's', '', testsuite_utils.checkResourceURI, 'R',\
                        descr='''define the URI of the resource under testing, the format is \
<host>[:<port>]/cream-<lrms>-<queue>. \
This option is mandatory and no default value is defined''')
    
    parameters.register('maxConcurrentSubmit', 'd', 1, testsuite_utils.atLeastOne, 'C',\
                        descr='''define the number of concurrent submit, (DEFAULT is 1)''')
    
    parameters.addEnvItem(('GLITE_LOCATION', 'location of gLite packages (DEFAULT=/opt/glite)'))
    parameters.addEnvItem(('X509_USER_PROXY', 'location of the user proxy'))
    parameters.addEnvItem(('MONITORED_LEASE_UP_CONFIG_FILE','''\
location of the configuration file for this test'''))

    if os.environ.has_key("MONITORED_LEASE_UP_CONFIG_FILE"):
        confFileName = os.environ["MONITORED_LEASE_UP_CONFIG_FILE"]
    else:
        confFileName = None

    try:

        parameters.parseConfigFileAndOptList(sys.argv[1:], confFileName)
        
    except testsuite_utils.BadValueException, ex:
        print "ERROR: %s\n\nUsage:" % ex
        parameters.display()
        sys.exit(1)
    except IOError, ioError:
        failure("Cannot read configuration file: " + confFileName + " " + str(ioError))
    except Exception, exception:
        failure("Error parsing parameters " + str(exception))
        
    if parameters.help:
        parameters.display()
        sys.exit(0)
        
    testsuite_utils.mainLogger.setup(parameters.logConf)

    parameters.jdl = testsuite_utils.createTempJDL(parameters.leaseTime*5)
    if parameters.jdl==None:
        sys.exit(1)

    vomsManager = job_utils.VOMSProxyManager(parameters)
    pollerThread = JobPoller(parameters, vomsManager)
    leaseRenewer = job_utils.LeaseRenewer(parameters, pollerThread)
    renewalManager = job_utils.ProxyRenewer(parameters, pollerThread, \
                                            vomsManager)
    
    pollerThread.start()
    leaseRenewer.start()
    #renewalManager.start()
    pollerThread.join()
    renewalManager.halt()
    leaseRenewer.halt()
    exitCode = pollerThread.shutdown()
    
    sys.exit(exitCode)


if __name__ == "__main__":
    main()
