#!/usr/bin/python

import os, os.path
import sys
import re, string
import threading
import time

from CREAMTestUtils import testsuite_utils, job_utils, CEMonitorConsumer
from CREAMTestUtils import job_monitor

def usage():
    manPage = testsuite_utils.ManPage()
    
    manPage.shortDescr = 'submit and cancel a sequence of jobs'
    manPage.synopsis = '[OPTION] -R | --resourceURI RESOURCEURI'
    manPage.description = '''Submit a sequence of simple jobs with a specified rate \
and then try to cancel them any changes in the job status \
are monitored via cemonitor notifications'''

    manPage.parameters.append(('-h', '--help' , '', 'print this message and exit'))
    manPage.parameters.append(('-r', '--rate', 'SLEEP_TIME', '''\
the sleep time in seconds between two consecutive notifications(Default 30s, Min 5s)'''))
    manPage.parameters.append(('-n', '--numberOfJob', 'NUM', 'the number of jobs to submit (Default 1)'))
    manPage.parameters.append(('-m', '--maxRunningJobs', 'NUM', '''\
the max number of job which can be enqueued in the service (Default 100)'''))
    manPage.parameters.append(('-D', '--delegationType', 'DELEGATIONTYPE','''\
specify the delegation management type: single, one delegated proxy for all submissions,\
or multiple, one delegated proxy per job (DEFAULT is single)'''))
    manPage.parameters.append(('-R', '--resourceURI', 'RESOURCEURI','''\
define the URI of the resource under testing, the format is \
<host>[:<port>]/cream-<lrms>-<queue>. \
This option is mandatory and no default value is defined'''))
    manPage.parameters.append(('-C', '--maxConcurrentSubmit', 'NUM', '''\
define the number of concurrent submit, (DEFAULT is 1)'''))
    manPage.parameters.append(('-j', '--jdl', 'JDLFILE', '''\
define the path for the jdl file, if omitted a predefined jdl will \
be used with simple sleep as executable'''))
    manPage.parameters.append(('-P', '--consumerPort', 'PORT', '''\
define the port for the consumer service (DEFAULT is 9000)'''))
    
    manPage.env.append(('GLITE_LOCATION', 'location of gLite packages (DEFAULT=/opt/glite)'))
    manPage.env.append(('X509_USER_PROXY', 'location of the user proxy'))
    manPage.env.append(('NOTIFIED_CANCEL_CONFIG_FILE','''\
location of the configuration file for this test'''))
    
    manPage.display()
    
    sys.exit(0)


def failure(reason):
    print reason
    sys.exit(1)
    
class JobProcessed(job_utils.JobProcessed):
    
    def __init__(self):
        job_utils.JobProcessed.__init__(self)
        
    def canPurge(self, jobStatus, failureReason=''):
        return jobStatus=='CANCELLED'

class JobMonitor(job_monitor.JobMonitor):
    
    def __init__(self, parameters, pManager=None):
        job_monitor.JobMonitor.__init__(self, parameters, pManager)
        self.finishedJobs = JobProcessed()
        #two different buffers are required:
        #one buffer for the purger process
        self.toCancel = []
        #one buffer for the notification mechanism
        self.runningJobs = []
        
    def manageNotifications(self):
        for (job, status) in self.runningJobs:
            if job in self.table:
                if self.table[job].scheduled:
                    JobMonitor.logger.warn("Cannot reschedule cancel for job %s (status %s)" \
                                           % (job, status))
                else:
                    JobMonitor.logger.info("Cancel job %s (status %s)" % (job, status))
                    self.toCancel.append(job)
        self.runningJobs = []
    
    def processNotifiedJobs(self):
        job_utils.eraseJobs(self.toCancel, cmd='cancel')
        for item in self.toCancel:
            self.table[item].scheduled = True
        self.toCancel = []

    def put(self, uri, timestamp):
        self.lock.acquire()
        JobMonitor.logger.info("Submitted job: " + uri)
        self.table[uri] = job_utils.BooleanTimestamp(timestamp)
        self.lock.release()

    def notify(self, jobHistory):
        self.lock.acquire()
        self.lastNotifyTS = time.time()
        (jobId, status) = jobHistory[-1]
        JobMonitor.logger.debug("Notify %s (%s)" % (jobId, status))
        if status in JobMonitor.finalStates:
            self.notified.append((jobId, status))
        if status in JobMonitor.runningStates:
            self.runningJobs.append((jobId, status))
        self.lock.release()

    def shutdown(self):
        job_monitor.JobMonitor.shutdown(self)
        if self.tableOfResults['CANCELLED']<>self.parameters.numberOfJob:
            return 1
        return 0
        
        
def main():

    parameters = testsuite_utils.Parameters()
    parameters.register('rate', 'd', 30, testsuite_utils.checkRate)
    parameters.register('numberOfJob', 'd', 1, testsuite_utils.atLeastOne)
    parameters.register('maxRunningJobs', 'd', 100, testsuite_utils.atLeastOne)
    parameters.register('delegationType', 's', 'single', testsuite_utils.checkRenewType,'D')
    parameters.register('resourceURI', 's', '', testsuite_utils.checkResourceURI, 'R')
    parameters.register('maxConcurrentSubmit', 'd', 1, testsuite_utils.atLeastOne, 'C')
    parameters.register('jdl', 's')
    parameters.register('consumerPort', 'd', 9000, testsuite_utils.checkPort, 'p')

    if os.environ.has_key("NOTIFIED_CANCEL_CONFIG_FILE"):
        confFileName = os.environ["NOTIFIED_CANCEL_CONFIG_FILE"]
    else:
        confFileName =None

    try:

        parameters.parseConfigFileAndOptList(sys.argv[1:], confFileName)
        
    except testsuite_utils.BadValueException, ex:
        print "ERROR: %s\n\nUsage:" % ex
        usage()
    except IOError, ioError:
        failure("Cannot read configuration file: " + confFileName + " " + str(ioError))
    except Exception, exception:
        failure("Error parsing parameters " + str(exception))
        
    if parameters.help:
        usage()
    
    testsuite_utils.mainLogger.setup(parameters.logConf)
    
    if parameters.jdl=='':
        parameters.jdl = testsuite_utils.createTempJDL(parameters.rate*5)
        if parameters.jdl==None:
            sys.exit(1)

    try:
        vomsManager = job_utils.VOMSProxyManager(parameters)
        monitorThread = JobMonitor(parameters, vomsManager)
        renewalManager = job_utils.ProxyRenewer(parameters, monitorThread, vomsManager)
        
        address = ('', parameters.consumerPort)
        consumer = CEMonitorConsumer.ConsumerServer(address, parameters, monitorThread)
        
        consumerThread = threading.Thread(target=consumer)
        consumerThread.start()
        
        monitorThread.start()
        #renewalManager.start()
        monitorThread.join()
        renewalManager.halt()
        
        exitCode = monitorThread.shutdown()
        
        consumer.halt()
        
    except Exception, e:
        failure(e)
        exitCode = 1
        
    sys.exit(exitCode)
        

if __name__ == "__main__":
    main()
