#!/usr/bin/python

import os,sys
import re, string

from CREAMTestUtils import testsuite_utils, job_utils, job_poller

def failure(reason):
    print reason
    sys.exit(1)

class JobProcessed(job_utils.JobProcessed):
    
    def __init__(self):
        job_utils.JobProcessed.__init__(self)
        
    def canPurge(self, jobStatus, failureReason=''):
        return jobStatus=='CANCELLED'


class JobPoller(job_poller.JobPoller):
    
    def __init__(self, parameters, pManager=None):
        job_poller.JobPoller.__init__(self, parameters, pManager)
        self.finishedJobs = JobProcessed()
        self.runningJobs = []
        
    def put(self, uri, timestamp):
        self.lock.acquire()
        job_poller.JobPoller.logger.info("Submitted job: " + uri)
        self.table[uri] = job_utils.BooleanTimestamp(timestamp)
        self.lock.release()

    def manageRunningState(self, currId):
        if self.table[currId].scheduled:
            job_poller.JobPoller.logger.debug("Cannot reschedule cancel for job %s" % currId)
        else:
            self.table[currId].scheduled = True
            job_poller.JobPoller.logger.debug("Scheduling %s for cancel" % currId)
            self.runningJobs.append(currId)
    
    def processRunningJobs(self):
        job_utils.eraseJobs(self.runningJobs, cmd='cancel')
        self.runningJobs = []
    
    def shutdown(self):
        job_poller.JobPoller.shutdown(self)
        if self.tableOfResults['CANCELLED']<>self.parameters.numberOfJob:
            return 1
        return 0



def main():
    
    parameters = testsuite_utils.Parameters('submit and cancel a sequence of jobs',\
                                            '[OPTION] -R | --resourceURI RESOURCEURI',\
                                            '''Submit a given number of jobs with a specified rate \
and then try to cancel them. The status of each job is monitored polling the service. \
The test keeps a given number of job running on the CE.''')
    
    parameters.register('rate', 'd', 30, testsuite_utils.checkRate, descr='''\
set the sleep time in seconds between two polling operations \
(DEFAULT 30s, Min 5s)''')
    
    parameters.register('numberOfJob', 'd', 1, testsuite_utils.atLeastOne, descr='''\
set the number of jobs to submit (DEFAULT 1)''')
    
    parameters.register('maxRunningJobs', 'd', 100, testsuite_utils.atLeastOne, descr='''\
set the max number of job which can be enqueued in the service (DEFAULT 100)''')
    
    parameters.register('delegationType', 's', 'single', testsuite_utils.checkRenewType,'D',\
                        descr='''\
specify the delegation management type: single, one delegated proxy for all submissions,\
or multiple, one delegated proxy per job (DEFAULT is single)''')
    
    parameters.register('resourceURI', 's', '', testsuite_utils.checkResourceURI, 'R', \
                        descr='''define the URI of the resource under testing, the format is \
<host>[:<port>]/cream-<lrms>-<queue>. \
This option is mandatory and no default value is defined''')
    
    parameters.register('maxConcurrentSubmit', 'd', 1, testsuite_utils.atLeastOne, 'C',\
                        descr='''define the number of concurrent submit, (DEFAULT is 1)''')
    
    parameters.register('jdl', 's', descr='''define the path for the jdl file, \
if omitted a predefined jdl will be used with simple sleep as executable (5 times the rate)''')
    
    parameters.addEnvItem(('GLITE_LOCATION', 'location of gLite packages (DEFAULT=/opt/glite)'))
    parameters.addEnvItem(('X509_USER_PROXY', 'location of the user proxy'))
    parameters.addEnvItem(('MONITORED_CANCEL_CONFIG_FILE','''\
location of the configuration file for this test'''))

    if os.environ.has_key("MONITORED_CANCEL_CONFIG_FILE"):
        confFileName = os.environ["MONITORED_CANCEL_CONFIG_FILE"]
    else:
        confFileName = None

    try:

        parameters.parseConfigFileAndOptList(sys.argv[1:], confFileName)

    except testsuite_utils.BadValueException, ex:
        print "ERROR: %s\n\nUsage:" % ex
        parameters.display()
        sys.exit(1)
    except IOError, ioError:
        failure("Cannot read configuration file: " + confFileName + " " + str(ioError))
    except Exception, exception:
        failure("Error parsing parameters " + str(exception))
        
    if parameters.help:
        parameters.display()
        sys.exit(1)
        
    testsuite_utils.mainLogger.setup(parameters.logConf)

    if parameters.jdl=='':
        parameters.jdl = testsuite_utils.createTempJDL(parameters.rate*10)
        if parameters.jdl==None:
            sys.exit(1)
    
    vomsManager = job_utils.VOMSProxyManager(parameters)
    pollerThread = JobPoller(parameters, vomsManager)
    renewalManager = job_utils.ProxyRenewer(parameters, pollerThread, vomsManager)

    pollerThread.start()
    #renewalManager.start()
    pollerThread.join()
    renewalManager.halt()

    exitCode = pollerThread.shutdown()
    
    sys.exit(exitCode)
    
if __name__ == "__main__":
    main()
