#!/usr/bin/python

import os, os.path
import sys
import re, string
import getopt
import threading
import log4py

from CREAMTestUtils import testsuite_utils, job_utils, CEMonitorConsumer, job_monitor

def usage():
    manPage = testsuite_utils.ManPage()
    
    manPage.shortDescr = 'submit and cancel a sequence of jobs'
    manPage.synopsis = '[OPTION]'
    manPage.description = '''Submit a sequence of simple jobs and manage their \
status via cemonitor notifications'''

    manPage.parameters.append(('-h', '--help' , '', 'print this message and exit'))
    manPage.parameters.append(('-r', '--rate', 'SLEEP_TIME', '''\
the sleep time in seconds between two consecutive notifications(Default 30s, Min 5s)'''))
    manPage.parameters.append(('-n', '--numberOfJob', 'NUM', 'the number of jobs to submit (Default 1)'))
    manPage.parameters.append(('-m', '--maxRunningJobs', 'NUM', '''\
the max number of job which can be enqueued in the service (Default 100)'''))
    manPage.parameters.append(('-D', '--delegationID', 'DELEGATIONID','''\
disable the auto-delegation for each submission and reuse the specified delegation ID'''))
    manPage.parameters.append(('-R', '--resourceURI', 'RESOURCEURI','''\
define the URI of the resource under testing, the format is \
<host>[:<port>]/cream-<lrms>-<queue>. \
This option is mandatory and no default value is defined'''))
    manPage.parameters.append(('-C', '--maxConcurrentSubmit', 'NUM', '''\
define the number of concurrent submit, (DEFAULT is 1)'''))
    manPage.parameters.append(('-j', '--jdl', 'JDLFILE', '''\
define the path for the jdl file, if omitted a predefined jdl will \
be used with simple sleep as executable'''))
    manPage.parameters.append(('-P', '--consumerPort', 'PORT', '''\
define the port for the consumer service (DEFAULT is 9000)'''))
    
    manPage.env.append(('GLITE_LOCATION', 'location of gLite packages (DEFAULT=/opt/glite)'))
    manPage.env.append(('X509_USER_PROXY', 'location of the user proxy'))
    manPage.env.append(('NOTIFIED_SUBMIT_CONFIG_FILE','''\
location of the configuration file for this test'''))
    
    manPage.display()
    
    sys.exit(0)


def failure(reason):
    print reason
    sys.exit(1)

class JobMonitor(job_monitor.JobMonitor):
    
    def __init__(self, parameters):
        job_monitor.JobMonitor.__init__(self, parameters)
        
    def shutdown(self):
        job_monitor.JobMonitor.shutdown(self)
        if self.tableOfResults['ABORTED']>0 or self.tableOfResults['CANCELLED']>0:
            return 1
        return 0

def main():
    logger = log4py.Logger().get_instance(classid="main")

    parameters = testsuite_utils.Parameters()
    parameters.register('rate', 'd', 30, testsuite_utils.checkRate)
    parameters.register('numberOfJob', 'd', 1, testsuite_utils.atLeastOne)
    parameters.register('maxRunningJobs', 'd', 100, testsuite_utils.atLeastOne)
    parameters.register('delegationID', 's', optChar='D')
    parameters.register('resourceURI', 's', optChar='R')
    parameters.register('maxConcurrentSubmit', 'd', 1, testsuite_utils.atLeastOne, 'C')
    parameters.register('jdl', 's')
    parameters.register('consumerPort', 'd', 9000, testsuite_utils.checkPort, 'p')
    parameters.register('help', 'b')

    if os.environ.has_key("NOTIFIED_SUBMIT_CONFIG_FILE"):
        confFileName = os.environ["NOTIFIED_SUBMIT_CONFIG_FILE"]
        try:
            parameters.parseConfigFile(confFileName)
        except IOError, ioError:
            failure("Cannot read configuration file: " + confFileName + " " + str(ioError))
        except Exception, exception:
            failure("Cannot parse configuration file: " + confFileName + " " + str(exception))

    try:
        optlist, args = getopt.getopt(sys.argv[1:], parameters.getShortOptString(),
                                      parameters.getLongOptList())
        parameters.parseOptList(optlist)
    except getopt.GetoptError:
        print "Wrong arguments\n\nUsage:\n"
        usage()
    except Exception, exception:
        failure("Cannot parse option list " + str(exception))
        
    if parameters.help:
        usage()

    if parameters.resourceURI=='':
        print "Resource URI is not defined"
        usage()
        
    if parameters.jdl=='':
        parameters.jdl = testsuite_utils.createTempJDL(parameters.rate*5, logger)
        if parameters.jdl==None:
            sys.exit(1)

    proxyFile = testsuite_utils.getProxyFile()

    servicePrefix = 'https://' + parameters.resourceURI[:string.find(parameters.resourceURI,'/') + 1]
    cemonURL = servicePrefix + "ce-monitor/services/CEMonitor"
        
    try:
        monitorThread = JobMonitor(parameters)
        
        address = ('', parameters.consumerPort)
        consumer = CEMonitorConsumer.ConsumerServer(address, monitorThread, servicePrefix)
        
        subscrId = job_utils.subscribeToCREAMJobs(cemonURL, parameters, proxyFile, logger)
        
        consumerThread = threading.Thread(target=consumer)
        consumerThread.start()
        
        monitorThread.start()
        monitorThread.join()
        exitCode = monitorThread.shutdown()
        
        #TODO unsubscribe hangs up
#        job_utils.unSubscribeToCREAMJobs(cemonURL, subscrId, parameters, proxyFile, logger)
        
        consumer.halt()
        
    except Exception, e:
        failure(e)
        exitCode = 1

    sys.exit(exitCode)
        

if __name__ == "__main__":
    main()
